// Code generated by chiptool; DO NOT EDIT.

package pac

import "github.com/kyanitecomputer/aspeed-go/reg"

// SspV2SSP CM4F coprocessor control registers (AST2700 SSP/TSP). SSP base: SCU0+0x120 (0x72C0_2120), TSP base: SCU0+0x160 (0x72C0_2160).
type SspV2SSP struct {
    Base uintptr
}

// ReadCTRL reads CM4F Coprocessor Control Register (SCU120/SCU160).
func (p *SspV2SSP) ReadCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0000))
}

// WriteCTRL writes CM4F Coprocessor Control Register (SCU120/SCU160).
func (p *SspV2SSP) WriteCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x0000, uint32(val))
}

// ReadSRAMREMAPBASE reads System SRAM Remap Base (SCU124/SCU164). Physical = field_value << 4. Maps system SRAM into CM4F virtual space.
func (p *SspV2SSP) ReadSRAMREMAPBASE() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0004))
}

// WriteSRAMREMAPBASE writes System SRAM Remap Base (SCU124/SCU164). Physical = field_value << 4. Maps system SRAM into CM4F virtual space.
func (p *SspV2SSP) WriteSRAMREMAPBASE(val uint32) {
    reg.Write(uint32(p.Base)+0x0004, uint32(val))
}

// ReadDRAMREMAPBASE reads DRAM Remap Base (SCU128/SCU168). Physical = field_value << 4. Maps DRAM into CM4F virtual space.
func (p *SspV2SSP) ReadDRAMREMAPBASE() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0008))
}

// WriteDRAMREMAPBASE writes DRAM Remap Base (SCU128/SCU168). Physical = field_value << 4. Maps DRAM into CM4F virtual space.
func (p *SspV2SSP) WriteDRAMREMAPBASE(val uint32) {
    reg.Write(uint32(p.Base)+0x0008, uint32(val))
}

// ReadICACHEAREA reads I-Bus Cacheable Area Declaration (SCU12C/SCU16C). Same 32×16 MB bitfield as AST2600 CACHE_AREA but I-bus only.
func (p *SspV2SSP) ReadICACHEAREA() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x000c))
}

// WriteICACHEAREA writes I-Bus Cacheable Area Declaration (SCU12C/SCU16C). Same 32×16 MB bitfield as AST2600 CACHE_AREA but I-bus only.
func (p *SspV2SSP) WriteICACHEAREA(val uint32) {
    reg.Write(uint32(p.Base)+0x000c, uint32(val))
}

// ReadDCACHEAREA reads D-Bus Cacheable Area Declaration (SCU130/SCU170). Same 32×16 MB bitfield as AST2600 CACHE_AREA but D-bus only.
func (p *SspV2SSP) ReadDCACHEAREA() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0010))
}

// WriteDCACHEAREA writes D-Bus Cacheable Area Declaration (SCU130/SCU170). Same 32×16 MB bitfield as AST2600 CACHE_AREA but D-bus only.
func (p *SspV2SSP) WriteDCACHEAREA(val uint32) {
    reg.Write(uint32(p.Base)+0x0010, uint32(val))
}

// ReadCACHEINVAL reads Cache Invalidation Control Register (SCU134/SCU174).
func (p *SspV2SSP) ReadCACHEINVAL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0014))
}

// WriteCACHEINVAL writes Cache Invalidation Control Register (SCU134/SCU174).
func (p *SspV2SSP) WriteCACHEINVAL(val uint32) {
    reg.Write(uint32(p.Base)+0x0014, uint32(val))
}

// ReadCACHEFUNC reads Cache Function Control Register (SCU138/SCU178). Incompatible with ssp_v1 — separate I/D enable bits, no CCM.
func (p *SspV2SSP) ReadCACHEFUNC() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0018))
}

// WriteCACHEFUNC writes Cache Function Control Register (SCU138/SCU178). Incompatible with ssp_v1 — separate I/D enable bits, no CCM.
func (p *SspV2SSP) WriteCACHEFUNC(val uint32) {
    reg.Write(uint32(p.Base)+0x0018, uint32(val))
}

// ReadTCMVIRTSTART reads TCM Virtual Start Address (SCU140/SCU180).
func (p *SspV2SSP) ReadTCMVIRTSTART() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0020))
}

// WriteTCMVIRTSTART writes TCM Virtual Start Address (SCU140/SCU180).
func (p *SspV2SSP) WriteTCMVIRTSTART(val uint32) {
    reg.Write(uint32(p.Base)+0x0020, uint32(val))
}

// ReadTCMVIRTSIZE reads TCM Virtual Size (SCU144/SCU184).
func (p *SspV2SSP) ReadTCMVIRTSIZE() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0024))
}

// WriteTCMVIRTSIZE writes TCM Virtual Size (SCU144/SCU184).
func (p *SspV2SSP) WriteTCMVIRTSIZE(val uint32) {
    reg.Write(uint32(p.Base)+0x0024, uint32(val))
}

// ReadSRAMVIRTSTART reads System SRAM Virtual Start Address (SCU148/SCU188).
func (p *SspV2SSP) ReadSRAMVIRTSTART() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0028))
}

// WriteSRAMVIRTSTART writes System SRAM Virtual Start Address (SCU148/SCU188).
func (p *SspV2SSP) WriteSRAMVIRTSTART(val uint32) {
    reg.Write(uint32(p.Base)+0x0028, uint32(val))
}

// ReadSRAMVIRTSIZE reads System SRAM Virtual Size (SCU14C/SCU18C).
func (p *SspV2SSP) ReadSRAMVIRTSIZE() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x002c))
}

// WriteSRAMVIRTSIZE writes System SRAM Virtual Size (SCU14C/SCU18C).
func (p *SspV2SSP) WriteSRAMVIRTSIZE(val uint32) {
    reg.Write(uint32(p.Base)+0x002c, uint32(val))
}

// ReadDRAMVIRTSTART reads DRAM Virtual Start Address (SCU150/SCU190).
func (p *SspV2SSP) ReadDRAMVIRTSTART() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0030))
}

// WriteDRAMVIRTSTART writes DRAM Virtual Start Address (SCU150/SCU190).
func (p *SspV2SSP) WriteDRAMVIRTSTART(val uint32) {
    reg.Write(uint32(p.Base)+0x0030, uint32(val))
}

// ReadDRAMVIRTSIZE reads DRAM Virtual Size (SCU154/SCU194).
func (p *SspV2SSP) ReadDRAMVIRTSIZE() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0034))
}

// WriteDRAMVIRTSIZE writes DRAM Virtual Size (SCU154/SCU194).
func (p *SspV2SSP) WriteDRAMVIRTSIZE(val uint32) {
    reg.Write(uint32(p.Base)+0x0034, uint32(val))
}

