// Code generated by chiptool; DO NOT EDIT.

package pac

import "github.com/kyanitecomputer/aspeed-go/reg"

// BootmcuTimerV1TIMER AST2700 BootMCU 64-bit free-running timer with alarm interrupt. Clocked at 1 MHz; INTR_STS is cleared by writing ALARM_L and ALARM_H. Base address: 0x14C36000 (IO-die, BootMCU view).
type BootmcuTimerV1TIMER struct {
    Base uintptr
}

// ReadCOUNTL reads Counter low 32 bits (read-only, free-running).
func (p *BootmcuTimerV1TIMER) ReadCOUNTL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0000))
}

// ReadCOUNTH reads Counter high 32 bits (read-only, free-running).
func (p *BootmcuTimerV1TIMER) ReadCOUNTH() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0004))
}

// ReadALARML reads Alarm compare value — low 32 bits. Writing this register also clears TMR_CTRL.INTR_STS.
func (p *BootmcuTimerV1TIMER) ReadALARML() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0008))
}

// WriteALARML writes Alarm compare value — low 32 bits. Writing this register also clears TMR_CTRL.INTR_STS.
func (p *BootmcuTimerV1TIMER) WriteALARML(val uint32) {
    reg.Write(uint32(p.Base)+0x0008, uint32(val))
}

// ReadALARMH reads Alarm compare value — high 32 bits. Writing this register also clears TMR_CTRL.INTR_STS.
func (p *BootmcuTimerV1TIMER) ReadALARMH() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x000c))
}

// WriteALARMH writes Alarm compare value — high 32 bits. Writing this register also clears TMR_CTRL.INTR_STS.
func (p *BootmcuTimerV1TIMER) WriteALARMH(val uint32) {
    reg.Write(uint32(p.Base)+0x000c, uint32(val))
}

// ReadCTRL reads Timer control and interrupt status register. Bits written 1 in this register set the corresponding function. Use CTRL_CLR to clear bits.
func (p *BootmcuTimerV1TIMER) ReadCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0010))
}

// WriteCTRL writes Timer control and interrupt status register. Bits written 1 in this register set the corresponding function. Use CTRL_CLR to clear bits.
func (p *BootmcuTimerV1TIMER) WriteCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x0010, uint32(val))
}

// ReadCTRLCLR reads Write-1-clear mirror of CTRL. Write 1 to a bit to clear the corresponding CTRL bit. Example: write TMR_CTRL_EN to stop the timer.
func (p *BootmcuTimerV1TIMER) ReadCTRLCLR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0014))
}

// WriteCTRLCLR writes Write-1-clear mirror of CTRL. Write 1 to a bit to clear the corresponding CTRL bit. Example: write TMR_CTRL_EN to stop the timer.
func (p *BootmcuTimerV1TIMER) WriteCTRLCLR(val uint32) {
    reg.Write(uint32(p.Base)+0x0014, uint32(val))
}

