// Code generated by chiptool; DO NOT EDIT.

package pac

// Peripheral base addresses
const (
    // TIMER_BASE AST2700 BootMCU 64-bit timer @ 1 MHz (IRQ 7, MTIP)
    TIMER_BASE = 0x14c36000
    // WDT0_BASE AST2700 G7 watchdog timer 0
    WDT0_BASE = 0x14c37000
    // UART12_BASE UART12 (16550, 4-byte stride, 1846153 Hz clock)
    UART12_BASE = 0x14c33b00
    // IPC1_BASE IPC1 data-channel bus (4 sub-channels, polling)
    IPC1_BASE = 0x14c39000
)

