// Code generated by chiptool; DO NOT EDIT.

package pac

// bootmcu_timer_v1::CTRL Timer control register (used for both CTRL and CTRL_CLR).
const (
    // EN Timer enable. 1 = timer counting enabled. Write to CTRL_CLR to stop.
    BootmcuTimerV1CTRLENPos = 0
    BootmcuTimerV1CTRLENMsk = 0x1 << 0
    // RESETEN Reset-on-alarm enable. 1 = counter resets to 0 when ALARM is reached.
    BootmcuTimerV1CTRLRESETENPos = 3
    BootmcuTimerV1CTRLRESETENMsk = 0x1 << 3
    // COUNTCLR Counter clear (self-clearing). Write 1 to reset the 64-bit counter to 0.
    BootmcuTimerV1CTRLCOUNTCLRPos = 4
    BootmcuTimerV1CTRLCOUNTCLRMsk = 0x1 << 4
    // INTRSTS Interrupt status. Set when COUNT reaches ALARM. Cleared by writing ALARM_L or ALARM_H (not by writing CTRL_CLR).
    BootmcuTimerV1CTRLINTRSTSPos = 16
    BootmcuTimerV1CTRLINTRSTSMsk = 0x1 << 16
)

// ipc1_v1::ID_MASK 4-bit mask, one bit per message ID (IDs 0–3).
const (
    // ID0 Message ID 0.
    Ipc1V1IDMASKID0Pos = 0
    Ipc1V1IDMASKID0Msk = 0x1 << 0
    // ID1 Message ID 1.
    Ipc1V1IDMASKID1Pos = 1
    Ipc1V1IDMASKID1Msk = 0x1 << 1
    // ID2 Message ID 2.
    Ipc1V1IDMASKID2Pos = 2
    Ipc1V1IDMASKID2Msk = 0x1 << 2
    // ID3 Message ID 3 (Caliptra/reserved).
    Ipc1V1IDMASKID3Pos = 3
    Ipc1V1IDMASKID3Msk = 0x1 << 3
)

// uart_v1::DATA8 8-bit data register (RBR/THR and SCR share this layout).
const (
    // DATA Data byte (bits [7:0]).
    UartV1DATA8DATAPos = 0
    UartV1DATA8DATAMsk = 0xff << 0
)

// uart_v1::FCR_IIR FIFO Control Register (write) / Interrupt Identification Register (read). Write access configures FIFO; read access returns interrupt status.
const (
    // FIFOEORIP Write (FCR): FIFO Enable.  1 = enable TX and RX FIFOs; clearing this bit resets both FIFOs. Read (IIR): Interrupt Pending (active-low).  0 = interrupt pending.
    UartV1FCRIIRFIFOEORIPPos = 0
    UartV1FCRIIRFIFOEORIPMsk = 0x1 << 0
    // RFIFORORIID1 Write (FCR): Receiver FIFO Reset.  Write 1 to flush RX FIFO. Read (IIR): Interrupt ID bit 1.
    UartV1FCRIIRRFIFORORIID1Pos = 1
    UartV1FCRIIRRFIFORORIID1Msk = 0x1 << 1
    // XFIFORORIID2 Write (FCR): Transmitter FIFO Reset.  Write 1 to flush TX FIFO. Read (IIR): Interrupt ID bit 2.
    UartV1FCRIIRXFIFORORIID2Pos = 2
    UartV1FCRIIRXFIFORORIID2Msk = 0x1 << 2
    // DMAORIID3 Write (FCR): DMA mode select.  0 = mode 0; 1 = mode 1. Read (IIR): Interrupt ID bit 3 (FIFO timeout indicator on 16550D).
    UartV1FCRIIRDMAORIID3Pos = 3
    UartV1FCRIIRDMAORIID3Msk = 0x1 << 3
    // TXTRIG Write (FCR): TX FIFO trigger threshold. 00=empty; 01=2 bytes; 10=quarter full; 11=half full.
    UartV1FCRIIRTXTRIGPos = 4
    UartV1FCRIIRTXTRIGMsk = 0x3 << 4
    // RXTRIG Write (FCR): RX FIFO trigger threshold. 00=1 byte; 01=quarter full; 10=half full; 11=2 from full. Read (IIR): FIFO enabled status bits [7:6] (11=FIFOs enabled).
    UartV1FCRIIRRXTRIGPos = 6
    UartV1FCRIIRRXTRIGMsk = 0x3 << 6
)

// uart_v1::IER Interrupt Enable Register (DLAB=0).
const (
    // ERBFI Enable Received Data Available Interrupt. 1 = generate IRQ when RBR has received data (LSR.DR=1) or FIFO reaches trigger level.
    UartV1IERERBFIPos = 0
    UartV1IERERBFIMsk = 0x1 << 0
    // ETBEI Enable Transmitter Holding Register Empty Interrupt. 1 = generate IRQ when THR is empty (LSR.THRE=1).
    UartV1IERETBEIPos = 1
    UartV1IERETBEIMsk = 0x1 << 1
    // ELSI Enable Receiver Line Status Interrupt. 1 = generate IRQ on OE/PE/FE/BI errors (LSR bits 1-4).
    UartV1IERELSIPos = 2
    UartV1IERELSIMsk = 0x1 << 2
    // EDSSI Enable Modem Status Interrupt. 1 = generate IRQ on CTS/DSR/RI/DCD changes (MSR bits 0-3).
    UartV1IEREDSSIPos = 3
    UartV1IEREDSSIMsk = 0x1 << 3
)

// uart_v1::LCR Line Control Register.
const (
    // WLS Word Length Select. 00=5 bits; 01=6 bits; 10=7 bits; 11=8 bits.
    UartV1LCRWLSPos = 0
    UartV1LCRWLSMsk = 0x3 << 0
    // STB Stop Bits. 0 = 1 stop bit; 1 = 2 stop bits (or 1.5 for 5-bit words).
    UartV1LCRSTBPos = 2
    UartV1LCRSTBMsk = 0x1 << 2
    // PEN Parity Enable. 1 = enable parity generation/checking.
    UartV1LCRPENPos = 3
    UartV1LCRPENMsk = 0x1 << 3
    // EPS Even Parity Select (when PEN=1). 0 = odd parity; 1 = even parity.
    UartV1LCREPSPos = 4
    UartV1LCREPSMsk = 0x1 << 4
    // SP Stick Parity. 1 = parity bit forced to 0 (EPS=1) or 1 (EPS=0).
    UartV1LCRSPPos = 5
    UartV1LCRSPMsk = 0x1 << 5
    // BC Break Control. 1 = force TX line to spacing (break) state.
    UartV1LCRBCPos = 6
    UartV1LCRBCMsk = 0x1 << 6
    // DLAB Divisor Latch Access Bit. 1 = offsets 0x00 and 0x04 address DLL/DLH (baud rate divisor); 0 = offsets 0x00 and 0x04 address RBR/THR and IER. Clear to 0 after configuring baud rate.
    UartV1LCRDLABPos = 7
    UartV1LCRDLABMsk = 0x1 << 7
)

// uart_v1::LSR Line Status Register. Read-only status bits.
const (
    // DR Data Ready. 1 = at least one character is in the RX buffer / RX FIFO.
    UartV1LSRDRPos = 0
    UartV1LSRDRMsk = 0x1 << 0
    // OE Overrun Error. 1 = a new character arrived before the previous was read. Cleared by reading LSR.
    UartV1LSROEPos = 1
    UartV1LSROEMsk = 0x1 << 1
    // PE Parity Error. 1 = received character has wrong parity. Cleared by reading LSR.
    UartV1LSRPEPos = 2
    UartV1LSRPEMsk = 0x1 << 2
    // FE Framing Error. 1 = received character has no valid stop bit. Cleared by reading LSR.
    UartV1LSRFEPos = 3
    UartV1LSRFEMsk = 0x1 << 3
    // BI Break Interrupt. 1 = RX line has been held at 0 (spacing) for more than one character time. Cleared by reading LSR.
    UartV1LSRBIPos = 4
    UartV1LSRBIMsk = 0x1 << 4
    // THRE Transmitter Holding Register Empty. 1 = THR is empty; safe to write next byte (or FIFO below threshold).
    UartV1LSRTHREPos = 5
    UartV1LSRTHREMsk = 0x1 << 5
    // TEMT Transmitter Empty. 1 = both THR and transmitter shift register are empty.
    UartV1LSRTEMTPos = 6
    UartV1LSRTEMTMsk = 0x1 << 6
    // FIFOERR FIFO data error (FIFO mode only). 1 = at least one PE/FE/BI error is present in the RX FIFO. Cleared when the erroneous byte is read out.
    UartV1LSRFIFOERRPos = 7
    UartV1LSRFIFOERRMsk = 0x1 << 7
)

// uart_v1::MCR Modem Control Register.
const (
    // DTR Data Terminal Ready output (active-low nDTR pin).
    UartV1MCRDTRPos = 0
    UartV1MCRDTRMsk = 0x1 << 0
    // RTS Request To Send output (active-low nRTS pin).
    UartV1MCRRTSPos = 1
    UartV1MCRRTSMsk = 0x1 << 1
    // OUT1 Output 1 (general-purpose output, active-low).
    UartV1MCROUT1Pos = 2
    UartV1MCROUT1Msk = 0x1 << 2
    // OUT2 Output 2 (active-low). On PC hardware this gates the interrupt; on ASPEED UARTs it must be set to 1 to enable interrupts.
    UartV1MCROUT2Pos = 3
    UartV1MCROUT2Msk = 0x1 << 3
    // LOOP Internal loopback mode. 1 = TX connected to RX internally; modem lines looped.
    UartV1MCRLOOPPos = 4
    UartV1MCRLOOPMsk = 0x1 << 4
)

// uart_v1::MSR Modem Status Register. CTS/DSR/RI/DCD change and current state.
const (
    // DCTS Delta CTS – CTS changed since last MSR read.
    UartV1MSRDCTSPos = 0
    UartV1MSRDCTSMsk = 0x1 << 0
    // DDSR Delta DSR – DSR changed since last MSR read.
    UartV1MSRDDSRPos = 1
    UartV1MSRDDSRMsk = 0x1 << 1
    // TERI Trailing Edge Ring Indicator – RI went from active to inactive.
    UartV1MSRTERIPos = 2
    UartV1MSRTERIMsk = 0x1 << 2
    // DDCD Delta DCD – DCD changed since last MSR read.
    UartV1MSRDDCDPos = 3
    UartV1MSRDDCDMsk = 0x1 << 3
    // CTS Clear To Send (complement of nCTS input).
    UartV1MSRCTSPos = 4
    UartV1MSRCTSMsk = 0x1 << 4
    // DSR Data Set Ready (complement of nDSR input).
    UartV1MSRDSRPos = 5
    UartV1MSRDSRMsk = 0x1 << 5
    // RI Ring Indicator (complement of nRI input).
    UartV1MSRRIPos = 6
    UartV1MSRRIMsk = 0x1 << 6
    // DCD Data Carrier Detect (complement of nDCD input).
    UartV1MSRDCDPos = 7
    UartV1MSRDCDMsk = 0x1 << 7
)

// wdt_v1::WDT_COUNTER 32-bit counter / reload value (WDT00 and WDT04 share this layout).
const (
    // VALUE Counter value in microseconds.
    WdtV1WDTCOUNTERVALUEPos = 0
    WdtV1WDTCOUNTERVALUEMsk = 0xffffffff << 0
)

// wdt_v1::WDT_CTRL WDT Control Register (WDT0C).
const (
    // WDTEN WDT Enable. 0 = disabled (counter holds current value); 1 = enabled (counter counts down).
    WdtV1WDTCTRLWDTENPos = 0
    WdtV1WDTCTRLWDTENMsk = 0x1 << 0
    // RSTSYS Reset system after timeout. 0 = disabled; 1 = assert SoC / CPU reset when counter reaches 0. Must clear WDT10[0] before enabling this bit.
    WdtV1WDTCTRLRSTSYSPos = 1
    WdtV1WDTCTRLRSTSYSMsk = 0x1 << 1
    // WDTRESETBYSOC Allow SOC-level reset to reset this WDT instance. 0 = only SRST# or full-chip reset can reset this WDT; 1 = SOC system reset also resets this WDT.
    WdtV1WDTCTRLWDTRESETBYSOCPos = 4
    WdtV1WDTCTRLWDTRESETBYSOCMsk = 0x1 << 4
    // RSTMODE Reset system mode (bits [6:5]). 00 = SOC system reset (gated by reset mask registers); 01 = Full chip reset; 1x = CPU/FMC only (firmware reboot, no peripheral reset).
    WdtV1WDTCTRLRSTMODEPos = 5
    WdtV1WDTCTRLRSTMODEMsk = 0x3 << 5
    // WDTEXT External signal enable after timeout. 1 = pulse generated on an external output pin.
    WdtV1WDTCTRLWDTEXTPos = 27
    WdtV1WDTCTRLWDTEXTMsk = 0x1 << 27
    // WDTINTR Interrupt before timeout. 1 = generate interrupt when counter reaches pre-timeout value (set in CTRL bits [31:10]).
    WdtV1WDTCTRLWDTINTRPos = 28
    WdtV1WDTCTRLWDTINTRMsk = 0x1 << 28
)

// wdt_v1::WDT_RESTART Counter Restart Register (WDT08).
const (
    // KEY Write 0x4755 to reload and restart the counter. Read returns 0 (write-only hardware).
    WdtV1WDTRESTARTKEYPos = 0
    WdtV1WDTRESTARTKEYMsk = 0xffff << 0
)

// wdt_v1::WDT_SW_RESET_CTRL Software Mode Reset Control Register (WDT24).
const (
    // TRIGGER Write 0xAEEDF123 to fire a software-mode SOC reset immediately. After reset this bit clears to 0 automatically. Only SOC reset mode is supported for software-triggered resets.
    WdtV1WDTSWRESETCTRLTRIGGERPos = 0
    WdtV1WDTSWRESETCTRLTRIGGERMsk = 0xffffffff << 0
)

// wdt_v1::WDT_SW_RESET_MASK1 Software Mode Reset Mask Register #1 (WDT28). Each bit enables (1) or disables (0) the reset of the corresponding subsystem when SW_RESET_CTRL is triggered.
const (
    // MASK Subsystem reset enable bitmask. Zephyr sets 0x03FF_FFF1 to reset the standard set of subsystems (ARM, SDRAM, AHB bridges, coprocessor, SOC controllers, USB, etc.).
    WdtV1WDTSWRESETMASK1MASKPos = 0
    WdtV1WDTSWRESETMASK1MASKMsk = 0xffffffff << 0
)

