// Code generated by chiptool; DO NOT EDIT.

package pac

// Ipc1V1SUBCHAN One IPC1 sub-channel consisting of an RX half and a TX half. RX half (remote peer's TX) is at offset 0x000. TX half (this side's TX) is at offset 0x100.
type Ipc1V1SUBCHAN struct {
    Base uintptr
}

// RX returns Receive half — read incoming messages from the remote peer.
func (p *Ipc1V1SUBCHAN) RX() Ipc1V1CHAN {
    return Ipc1V1CHAN{Base: p.Base + 0x0000}
}

// TX returns Transmit half — write outgoing messages to the remote peer.
func (p *Ipc1V1SUBCHAN) TX() Ipc1V1CHAN {
    return Ipc1V1CHAN{Base: p.Base + 0x0100}
}

