// Code generated by chiptool; DO NOT EDIT.

package pac

// Ipc1V1IPC1 AST2700 BootMCU IPC1 bus — 4 sub-channels at stride 0x200. Sub-channel index: 0=secure-CA35, 1=non-secure-CA35, 2=SSP, 3=TSP. Base address: 0x14C39000 (IO-die, BootMCU view).
type Ipc1V1IPC1 struct {
    Base uintptr
}

// CH returns Sub-channels 0–3 (stride 0x200 each).[n] (n < 4)
func (p *Ipc1V1IPC1) CH(n uintptr) Ipc1V1SUBCHAN {
    return Ipc1V1SUBCHAN{Base: p.Base + 0x0000 + n*512}
}

