// Code generated by chiptool; DO NOT EDIT.

package pac

import "github.com/kyanitecomputer/aspeed-go/reg"

// Ipc1V1CHAN One half (TX or RX) of an IPC1 sub-channel. TX half is at sub-channel_base + 0x100; RX half at sub-channel_base + 0x000. Each half supports 4 message IDs (0–3).
type Ipc1V1CHAN struct {
    Base uintptr
}

// ReadTRIG reads Message trigger register. Write BIT(id) to dispatch a message with the given ID to the remote peer. The corresponding bit in STATUS is set on the remote side.
func (p *Ipc1V1CHAN) ReadTRIG() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0000))
}

// WriteTRIG writes Message trigger register. Write BIT(id) to dispatch a message with the given ID to the remote peer. The corresponding bit in STATUS is set on the remote side.
func (p *Ipc1V1CHAN) WriteTRIG(val uint32) {
    reg.Write(uint32(p.Base)+0x0000, uint32(val))
}

// ReadENABLE reads Per-ID receive enable mask. Write BIT(id) to enable reception of messages with that ID. Only enabled IDs set STATUS bits.
func (p *Ipc1V1CHAN) ReadENABLE() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0004))
}

// WriteENABLE writes Per-ID receive enable mask. Write BIT(id) to enable reception of messages with that ID. Only enabled IDs set STATUS bits.
func (p *Ipc1V1CHAN) WriteENABLE(val uint32) {
    reg.Write(uint32(p.Base)+0x0004, uint32(val))
}

// ReadSTATUS reads Pending message status. Bit n is set when a message with ID n has been received and not yet consumed. Write BIT(id) to clear (acknowledge) after reading the payload.
func (p *Ipc1V1CHAN) ReadSTATUS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0008))
}

// WriteSTATUS writes Pending message status. Bit n is set when a message with ID n has been received and not yet consumed. Write BIT(id) to clear (acknowledge) after reading the payload.
func (p *Ipc1V1CHAN) WriteSTATUS(val uint32) {
    reg.Write(uint32(p.Base)+0x0008, uint32(val))
}

// ReadDATA0 reads 32-byte payload for message ID 0 (8 × 32-bit words). The transmitter writes here before triggering; the receiver reads here after detecting STATUS[0].
// [n] (n < 8)
func (p *Ipc1V1CHAN) ReadDATA0(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0010 + uint32(n)*4))
}

// WriteDATA0 writes 32-byte payload for message ID 0 (8 × 32-bit words). The transmitter writes here before triggering; the receiver reads here after detecting STATUS[0].
// [n] (n < 8)
func (p *Ipc1V1CHAN) WriteDATA0(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0010+uint32(n)*4, uint32(val))
}

// ReadDATA1 reads 32-byte payload for message ID 1 (8 × 32-bit words).[n] (n < 8)
func (p *Ipc1V1CHAN) ReadDATA1(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0030 + uint32(n)*4))
}

// WriteDATA1 writes 32-byte payload for message ID 1 (8 × 32-bit words).[n] (n < 8)
func (p *Ipc1V1CHAN) WriteDATA1(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0030+uint32(n)*4, uint32(val))
}

// ReadDATA2 reads 32-byte payload for message ID 2 (8 × 32-bit words).[n] (n < 8)
func (p *Ipc1V1CHAN) ReadDATA2(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0050 + uint32(n)*4))
}

// WriteDATA2 writes 32-byte payload for message ID 2 (8 × 32-bit words).[n] (n < 8)
func (p *Ipc1V1CHAN) WriteDATA2(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0050+uint32(n)*4, uint32(val))
}

// ReadDATA3 reads 32-byte payload for message ID 3 (Caliptra/reserved).[n] (n < 8)
func (p *Ipc1V1CHAN) ReadDATA3(n uintptr) uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0070 + uint32(n)*4))
}

// WriteDATA3 writes 32-byte payload for message ID 3 (Caliptra/reserved).[n] (n < 8)
func (p *Ipc1V1CHAN) WriteDATA3(n uintptr, val uint32) {
    reg.Write(uint32(p.Base)+0x0070+uint32(n)*4, uint32(val))
}

