// Code generated by chiptool; DO NOT EDIT.

package pac

import "github.com/kyanitecomputer/aspeed-go/reg"

// FmcV1SPI ASPEED SPI Flash Controller (SPI1 at 0x7E63_0000, SPI2 at 0x7E64_0000). Two chip-enables per instance. Memory windows: SPI1=0x9000_0000, SPI2=0xB000_0000. Same IP as FMC; no boot WDT/soft-reset; DMA requires arbitration via DMA_CTRL.
type FmcV1SPI struct {
    Base uintptr
}

// ReadCETYPE reads CE type and default write enable configuration.
func (p *FmcV1SPI) ReadCETYPE() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0000))
}

// WriteCETYPE writes CE type and default write enable configuration.
func (p *FmcV1SPI) WriteCETYPE(val uint32) {
    reg.Write(uint32(p.Base)+0x0000, uint32(val))
}

// ReadCECTRL reads CE control — tCSH timing and 4-byte address mode selection.
func (p *FmcV1SPI) ReadCECTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0004))
}

// WriteCECTRL writes CE control — tCSH timing and 4-byte address mode selection.
func (p *FmcV1SPI) WriteCECTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x0004, uint32(val))
}

// ReadIRQCTRL reads Interrupt control and status.
func (p *FmcV1SPI) ReadIRQCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0008))
}

// WriteIRQCTRL writes Interrupt control and status.
func (p *FmcV1SPI) WriteIRQCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x0008, uint32(val))
}

// ReadCMDCTRL reads Command control — address and data byte lane enable/disable.
func (p *FmcV1SPI) ReadCMDCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x000c))
}

// WriteCMDCTRL writes Command control — address and data byte lane enable/disable.
func (p *FmcV1SPI) WriteCMDCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x000c, uint32(val))
}

// ReadCE0CTRL reads CE0 control — I/O mode, clock, SPI command, dummy cycles, access mode.
func (p *FmcV1SPI) ReadCE0CTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0010))
}

// WriteCE0CTRL writes CE0 control — I/O mode, clock, SPI command, dummy cycles, access mode.
func (p *FmcV1SPI) WriteCE0CTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x0010, uint32(val))
}

// ReadCE1CTRL reads CE1 control (same layout as CE0_CTRL).
func (p *FmcV1SPI) ReadCE1CTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0014))
}

// WriteCE1CTRL writes CE1 control (same layout as CE0_CTRL).
func (p *FmcV1SPI) WriteCE1CTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x0014, uint32(val))
}

// ReadCE0ADDRRANGE reads CE0 address decoding range (start/end bits[27:20] in 1 MB units).
func (p *FmcV1SPI) ReadCE0ADDRRANGE() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0030))
}

// WriteCE0ADDRRANGE writes CE0 address decoding range (start/end bits[27:20] in 1 MB units).
func (p *FmcV1SPI) WriteCE0ADDRRANGE(val uint32) {
    reg.Write(uint32(p.Base)+0x0030, uint32(val))
}

// ReadCE1ADDRRANGE reads CE1 address decoding range.
func (p *FmcV1SPI) ReadCE1ADDRRANGE() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0034))
}

// WriteCE1ADDRRANGE writes CE1 address decoding range.
func (p *FmcV1SPI) WriteCE1ADDRRANGE(val uint32) {
    reg.Write(uint32(p.Base)+0x0034, uint32(val))
}

// ReadDUMMYCYCLEDATA reads Data output during head of dummy cycles.
func (p *FmcV1SPI) ReadDUMMYCYCLEDATA() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0054))
}

// WriteDUMMYCYCLEDATA writes Data output during head of dummy cycles.
func (p *FmcV1SPI) WriteDUMMYCYCLEDATA(val uint32) {
    reg.Write(uint32(p.Base)+0x0054, uint32(val))
}

// ReadDMABUFMODELEN reads DMA FIFO buffer mode length in 4-byte units.
func (p *FmcV1SPI) ReadDMABUFMODELEN() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x007c))
}

// WriteDMABUFMODELEN writes DMA FIFO buffer mode length in 4-byte units.
func (p *FmcV1SPI) WriteDMABUFMODELEN(val uint32) {
    reg.Write(uint32(p.Base)+0x007c, uint32(val))
}

// ReadDMACTRL reads DMA control/status. SPI requires DMA arbitration: write 0xAEED_0000 to bit[31] to request, wait for bit[30]=1 (granted). Release with 0xDEEA_0000 after DMA completes.
func (p *FmcV1SPI) ReadDMACTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0080))
}

// WriteDMACTRL writes DMA control/status. SPI requires DMA arbitration: write 0xAEED_0000 to bit[31] to request, wait for bit[30]=1 (granted). Release with 0xDEEA_0000 after DMA completes.
func (p *FmcV1SPI) WriteDMACTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x0080, uint32(val))
}

// ReadDMAFLASHADDR reads DMA flash-side start address.
func (p *FmcV1SPI) ReadDMAFLASHADDR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0084))
}

// WriteDMAFLASHADDR writes DMA flash-side start address.
func (p *FmcV1SPI) WriteDMAFLASHADDR(val uint32) {
    reg.Write(uint32(p.Base)+0x0084, uint32(val))
}

// ReadDMARAMADDR reads DMA DRAM/SRAM-side start address.
func (p *FmcV1SPI) ReadDMARAMADDR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0088))
}

// WriteDMARAMADDR writes DMA DRAM/SRAM-side start address.
func (p *FmcV1SPI) WriteDMARAMADDR(val uint32) {
    reg.Write(uint32(p.Base)+0x0088, uint32(val))
}

// ReadDMALEN reads DMA transfer length in bytes.
func (p *FmcV1SPI) ReadDMALEN() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x008c))
}

// WriteDMALEN writes DMA transfer length in bytes.
func (p *FmcV1SPI) WriteDMALEN(val uint32) {
    reg.Write(uint32(p.Base)+0x008c, uint32(val))
}

// ReadDMACHECKSUM reads Running 32-bit checksum over flash read data.
func (p *FmcV1SPI) ReadDMACHECKSUM() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0090))
}

// WriteDMACHECKSUM writes Running 32-bit checksum over flash read data.
func (p *FmcV1SPI) WriteDMACHECKSUM(val uint32) {
    reg.Write(uint32(p.Base)+0x0090, uint32(val))
}

// ReadCE0READTIMING reads CE0 read timing compensation (per-HCLK-divisor input delay).
func (p *FmcV1SPI) ReadCE0READTIMING() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0094))
}

// WriteCE0READTIMING writes CE0 read timing compensation (per-HCLK-divisor input delay).
func (p *FmcV1SPI) WriteCE0READTIMING(val uint32) {
    reg.Write(uint32(p.Base)+0x0094, uint32(val))
}

// ReadCE1READTIMING reads CE1 read timing compensation.
func (p *FmcV1SPI) ReadCE1READTIMING() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0098))
}

// WriteCE1READTIMING writes CE1 read timing compensation.
func (p *FmcV1SPI) WriteCE1READTIMING(val uint32) {
    reg.Write(uint32(p.Base)+0x0098, uint32(val))
}

// ReadCMDFILTERCTRL reads Command filter control.
func (p *FmcV1SPI) ReadCMDFILTERCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00a0))
}

// WriteCMDFILTERCTRL writes Command filter control.
func (p *FmcV1SPI) WriteCMDFILTERCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x00a0, uint32(val))
}

// ReadWRITEFILTERCTRL reads Write address filter mode (6 filters for SPI vs 8 for FMC).
func (p *FmcV1SPI) ReadWRITEFILTERCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00a4))
}

// WriteWRITEFILTERCTRL writes Write address filter mode (6 filters for SPI vs 8 for FMC).
func (p *FmcV1SPI) WriteWRITEFILTERCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x00a4, uint32(val))
}

// ReadLOCKSRST reads Register lock until SRST#.
func (p *FmcV1SPI) ReadLOCKSRST() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00a8))
}

// WriteLOCKSRST writes Register lock until SRST#.
func (p *FmcV1SPI) WriteLOCKSRST(val uint32) {
    reg.Write(uint32(p.Base)+0x00a8, uint32(val))
}

// ReadLOCKWDT reads Register lock until WDT reset.
func (p *FmcV1SPI) ReadLOCKWDT() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00ac))
}

// WriteLOCKWDT writes Register lock until WDT reset.
func (p *FmcV1SPI) WriteLOCKWDT(val uint32) {
    reg.Write(uint32(p.Base)+0x00ac, uint32(val))
}

// ReadWRITEADDRFILTER1 reads Write address filter
func (p *FmcV1SPI) ReadWRITEADDRFILTER1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00b0))
}

// WriteWRITEADDRFILTER1 writes Write address filter
func (p *FmcV1SPI) WriteWRITEADDRFILTER1(val uint32) {
    reg.Write(uint32(p.Base)+0x00b0, uint32(val))
}

// ReadWRITEADDRFILTER2 reads Write address filter
func (p *FmcV1SPI) ReadWRITEADDRFILTER2() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00b4))
}

// WriteWRITEADDRFILTER2 writes Write address filter
func (p *FmcV1SPI) WriteWRITEADDRFILTER2(val uint32) {
    reg.Write(uint32(p.Base)+0x00b4, uint32(val))
}

// ReadWRITEADDRFILTER3 reads Write address filter
func (p *FmcV1SPI) ReadWRITEADDRFILTER3() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00b8))
}

// WriteWRITEADDRFILTER3 writes Write address filter
func (p *FmcV1SPI) WriteWRITEADDRFILTER3(val uint32) {
    reg.Write(uint32(p.Base)+0x00b8, uint32(val))
}

// ReadWRITEADDRFILTER4 reads Write address filter
func (p *FmcV1SPI) ReadWRITEADDRFILTER4() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00bc))
}

// WriteWRITEADDRFILTER4 writes Write address filter
func (p *FmcV1SPI) WriteWRITEADDRFILTER4(val uint32) {
    reg.Write(uint32(p.Base)+0x00bc, uint32(val))
}

// ReadWRITEADDRFILTER5 reads Write address filter
func (p *FmcV1SPI) ReadWRITEADDRFILTER5() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00c0))
}

// WriteWRITEADDRFILTER5 writes Write address filter
func (p *FmcV1SPI) WriteWRITEADDRFILTER5(val uint32) {
    reg.Write(uint32(p.Base)+0x00c0, uint32(val))
}

// ReadWRITEADDRFILTER6 reads Write address filter
func (p *FmcV1SPI) ReadWRITEADDRFILTER6() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00c4))
}

// WriteWRITEADDRFILTER6 writes Write address filter
func (p *FmcV1SPI) WriteWRITEADDRFILTER6(val uint32) {
    reg.Write(uint32(p.Base)+0x00c4, uint32(val))
}

// ReadFQCD0 reads FQCD entry 0 (predefined: EN4B — enter 4-byte mode).
func (p *FmcV1SPI) ReadFQCD0() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0100))
}

// WriteFQCD0 writes FQCD entry 0 (predefined: EN4B — enter 4-byte mode).
func (p *FmcV1SPI) WriteFQCD0(val uint32) {
    reg.Write(uint32(p.Base)+0x0100, uint32(val))
}

// ReadFQCD1 reads FQCD entry 1 (predefined: EX4B).
func (p *FmcV1SPI) ReadFQCD1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0104))
}

// WriteFQCD1 writes FQCD entry 1 (predefined: EX4B).
func (p *FmcV1SPI) WriteFQCD1(val uint32) {
    reg.Write(uint32(p.Base)+0x0104, uint32(val))
}

// ReadFQCD2 reads FQCD entry 2 (predefined: EQIO).
func (p *FmcV1SPI) ReadFQCD2() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0108))
}

// WriteFQCD2 writes FQCD entry 2 (predefined: EQIO).
func (p *FmcV1SPI) WriteFQCD2(val uint32) {
    reg.Write(uint32(p.Base)+0x0108, uint32(val))
}

// ReadFQCD3 reads FQCD entry 3 (predefined: RSTQIO).
func (p *FmcV1SPI) ReadFQCD3() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x010c))
}

// WriteFQCD3 writes FQCD entry 3 (predefined: RSTQIO).
func (p *FmcV1SPI) WriteFQCD3(val uint32) {
    reg.Write(uint32(p.Base)+0x010c, uint32(val))
}

// ReadFQCD4 reads FQCD entry 4 — general purpose.
func (p *FmcV1SPI) ReadFQCD4() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0110))
}

// WriteFQCD4 writes FQCD entry 4 — general purpose.
func (p *FmcV1SPI) WriteFQCD4(val uint32) {
    reg.Write(uint32(p.Base)+0x0110, uint32(val))
}

// ReadFQCD5 reads FQCD entry 5 — general purpose.
func (p *FmcV1SPI) ReadFQCD5() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0114))
}

// WriteFQCD5 writes FQCD entry 5 — general purpose.
func (p *FmcV1SPI) WriteFQCD5(val uint32) {
    reg.Write(uint32(p.Base)+0x0114, uint32(val))
}

// ReadFQCD6 reads FQCD entry 6 — general purpose.
func (p *FmcV1SPI) ReadFQCD6() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0118))
}

// WriteFQCD6 writes FQCD entry 6 — general purpose.
func (p *FmcV1SPI) WriteFQCD6(val uint32) {
    reg.Write(uint32(p.Base)+0x0118, uint32(val))
}

// ReadFQCD7 reads FQCD entry 7 — general purpose.
func (p *FmcV1SPI) ReadFQCD7() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x011c))
}

// WriteFQCD7 writes FQCD entry 7 — general purpose.
func (p *FmcV1SPI) WriteFQCD7(val uint32) {
    reg.Write(uint32(p.Base)+0x011c, uint32(val))
}

// ReadFQCD8 reads FQCD entry 8 — general purpose.
func (p *FmcV1SPI) ReadFQCD8() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0120))
}

// WriteFQCD8 writes FQCD entry 8 — general purpose.
func (p *FmcV1SPI) WriteFQCD8(val uint32) {
    reg.Write(uint32(p.Base)+0x0120, uint32(val))
}

// ReadFQCD9 reads FQCD entry 9 — general purpose.
func (p *FmcV1SPI) ReadFQCD9() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0124))
}

// WriteFQCD9 writes FQCD entry 9 — general purpose.
func (p *FmcV1SPI) WriteFQCD9(val uint32) {
    reg.Write(uint32(p.Base)+0x0124, uint32(val))
}

// ReadFQCD10 reads FQCD entry 10 — general purpose.
func (p *FmcV1SPI) ReadFQCD10() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0128))
}

// WriteFQCD10 writes FQCD entry 10 — general purpose.
func (p *FmcV1SPI) WriteFQCD10(val uint32) {
    reg.Write(uint32(p.Base)+0x0128, uint32(val))
}

// ReadFQCD11 reads FQCD entry 11 — general purpose.
func (p *FmcV1SPI) ReadFQCD11() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x012c))
}

// WriteFQCD11 writes FQCD entry 11 — general purpose.
func (p *FmcV1SPI) WriteFQCD11(val uint32) {
    reg.Write(uint32(p.Base)+0x012c, uint32(val))
}

// ReadFQCD12 reads FQCD entry 12 — general purpose.
func (p *FmcV1SPI) ReadFQCD12() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0130))
}

// WriteFQCD12 writes FQCD entry 12 — general purpose.
func (p *FmcV1SPI) WriteFQCD12(val uint32) {
    reg.Write(uint32(p.Base)+0x0130, uint32(val))
}

// ReadFQCD13 reads FQCD entry 13 — general purpose.
func (p *FmcV1SPI) ReadFQCD13() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0134))
}

// WriteFQCD13 writes FQCD entry 13 — general purpose.
func (p *FmcV1SPI) WriteFQCD13(val uint32) {
    reg.Write(uint32(p.Base)+0x0134, uint32(val))
}

// ReadFQCD14 reads FQCD entry 14 — general purpose.
func (p *FmcV1SPI) ReadFQCD14() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0138))
}

// WriteFQCD14 writes FQCD entry 14 — general purpose.
func (p *FmcV1SPI) WriteFQCD14(val uint32) {
    reg.Write(uint32(p.Base)+0x0138, uint32(val))
}

// ReadFQCD15 reads FQCD entry 15 — general purpose.
func (p *FmcV1SPI) ReadFQCD15() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x013c))
}

// WriteFQCD15 writes FQCD entry 15 — general purpose.
func (p *FmcV1SPI) WriteFQCD15(val uint32) {
    reg.Write(uint32(p.Base)+0x013c, uint32(val))
}

// ReadFQCD16 reads FQCD entry 16 — general purpose.
func (p *FmcV1SPI) ReadFQCD16() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0140))
}

// WriteFQCD16 writes FQCD entry 16 — general purpose.
func (p *FmcV1SPI) WriteFQCD16(val uint32) {
    reg.Write(uint32(p.Base)+0x0140, uint32(val))
}

// ReadFQCD17 reads FQCD entry 17 — general purpose.
func (p *FmcV1SPI) ReadFQCD17() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0144))
}

// WriteFQCD17 writes FQCD entry 17 — general purpose.
func (p *FmcV1SPI) WriteFQCD17(val uint32) {
    reg.Write(uint32(p.Base)+0x0144, uint32(val))
}

// ReadFQCD18 reads FQCD entry 18 — general purpose.
func (p *FmcV1SPI) ReadFQCD18() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0148))
}

// WriteFQCD18 writes FQCD entry 18 — general purpose.
func (p *FmcV1SPI) WriteFQCD18(val uint32) {
    reg.Write(uint32(p.Base)+0x0148, uint32(val))
}

// ReadFQCD19 reads FQCD entry 19 (predefined: WREAR).
func (p *FmcV1SPI) ReadFQCD19() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x014c))
}

// WriteFQCD19 writes FQCD entry 19 (predefined: WREAR).
func (p *FmcV1SPI) WriteFQCD19(val uint32) {
    reg.Write(uint32(p.Base)+0x014c, uint32(val))
}

// ReadAQCD0 reads AQCD entry 0.
func (p *FmcV1SPI) ReadAQCD0() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0150))
}

// WriteAQCD0 writes AQCD entry 0.
func (p *FmcV1SPI) WriteAQCD0(val uint32) {
    reg.Write(uint32(p.Base)+0x0150, uint32(val))
}

// ReadAQCD1 reads AQCD entry 1.
func (p *FmcV1SPI) ReadAQCD1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0154))
}

// WriteAQCD1 writes AQCD entry 1.
func (p *FmcV1SPI) WriteAQCD1(val uint32) {
    reg.Write(uint32(p.Base)+0x0154, uint32(val))
}

// ReadAQCD2 reads AQCD entry 2.
func (p *FmcV1SPI) ReadAQCD2() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0158))
}

// WriteAQCD2 writes AQCD entry 2.
func (p *FmcV1SPI) WriteAQCD2(val uint32) {
    reg.Write(uint32(p.Base)+0x0158, uint32(val))
}

// ReadAQCD3 reads AQCD entry 3 — general purpose.
func (p *FmcV1SPI) ReadAQCD3() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x015c))
}

// WriteAQCD3 writes AQCD entry 3 — general purpose.
func (p *FmcV1SPI) WriteAQCD3(val uint32) {
    reg.Write(uint32(p.Base)+0x015c, uint32(val))
}

// ReadAQCD4 reads AQCD entry 4 — general purpose.
func (p *FmcV1SPI) ReadAQCD4() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0160))
}

// WriteAQCD4 writes AQCD entry 4 — general purpose.
func (p *FmcV1SPI) WriteAQCD4(val uint32) {
    reg.Write(uint32(p.Base)+0x0160, uint32(val))
}

// ReadAQCD5 reads AQCD entry 5 — general purpose.
func (p *FmcV1SPI) ReadAQCD5() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0164))
}

// WriteAQCD5 writes AQCD entry 5 — general purpose.
func (p *FmcV1SPI) WriteAQCD5(val uint32) {
    reg.Write(uint32(p.Base)+0x0164, uint32(val))
}

// ReadAQCD6 reads AQCD entry 6 — general purpose.
func (p *FmcV1SPI) ReadAQCD6() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0168))
}

// WriteAQCD6 writes AQCD entry 6 — general purpose.
func (p *FmcV1SPI) WriteAQCD6(val uint32) {
    reg.Write(uint32(p.Base)+0x0168, uint32(val))
}

// ReadAQCD7 reads AQCD entry 7 — general purpose.
func (p *FmcV1SPI) ReadAQCD7() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x016c))
}

// WriteAQCD7 writes AQCD entry 7 — general purpose.
func (p *FmcV1SPI) WriteAQCD7(val uint32) {
    reg.Write(uint32(p.Base)+0x016c, uint32(val))
}

// ReadAQCD8 reads AQCD entry 8 — general purpose.
func (p *FmcV1SPI) ReadAQCD8() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0170))
}

// WriteAQCD8 writes AQCD entry 8 — general purpose.
func (p *FmcV1SPI) WriteAQCD8(val uint32) {
    reg.Write(uint32(p.Base)+0x0170, uint32(val))
}

// ReadAQCD9 reads AQCD entry 9 — general purpose.
func (p *FmcV1SPI) ReadAQCD9() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0174))
}

// WriteAQCD9 writes AQCD entry 9 — general purpose.
func (p *FmcV1SPI) WriteAQCD9(val uint32) {
    reg.Write(uint32(p.Base)+0x0174, uint32(val))
}

// ReadAQCD10 reads AQCD entry 10 — general purpose.
func (p *FmcV1SPI) ReadAQCD10() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0178))
}

// WriteAQCD10 writes AQCD entry 10 — general purpose.
func (p *FmcV1SPI) WriteAQCD10(val uint32) {
    reg.Write(uint32(p.Base)+0x0178, uint32(val))
}

// ReadAQCD11 reads AQCD entry 11 — general purpose.
func (p *FmcV1SPI) ReadAQCD11() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x017c))
}

// WriteAQCD11 writes AQCD entry 11 — general purpose.
func (p *FmcV1SPI) WriteAQCD11(val uint32) {
    reg.Write(uint32(p.Base)+0x017c, uint32(val))
}

