// Code generated by chiptool; DO NOT EDIT.

package pac

import "github.com/kyanitecomputer/aspeed-go/reg"

// FmcV1FMC ASPEED Firmware SPI Memory Controller (FMC/BSPI). Base: 0x7E62_0000. Two chip-enables (CE0 = boot flash, CE1 = secondary). Flash memory mapped at 0x0000_0000 and 0x8000_0000.
type FmcV1FMC struct {
    Base uintptr
}

// ReadCETYPE reads CE type / flash configuration. Controls per-CE flash type and default write enable.
func (p *FmcV1FMC) ReadCETYPE() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0000))
}

// WriteCETYPE writes CE type / flash configuration. Controls per-CE flash type and default write enable.
func (p *FmcV1FMC) WriteCETYPE(val uint32) {
    reg.Write(uint32(p.Base)+0x0000, uint32(val))
}

// ReadCECTRL reads CE control — minimum inactive timing (tCSH) and 4-byte address mode.
func (p *FmcV1FMC) ReadCECTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0004))
}

// WriteCECTRL writes CE control — minimum inactive timing (tCSH) and 4-byte address mode.
func (p *FmcV1FMC) WriteCECTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x0004, uint32(val))
}

// ReadIRQCTRL reads Interrupt control and status — DMA done, command abort, write protect.
func (p *FmcV1FMC) ReadIRQCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0008))
}

// WriteIRQCTRL writes Interrupt control and status — DMA done, command abort, write protect.
func (p *FmcV1FMC) WriteIRQCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x0008, uint32(val))
}

// ReadCMDCTRL reads Command control — address and data byte lane enable/disable.
func (p *FmcV1FMC) ReadCMDCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x000c))
}

// WriteCMDCTRL writes Command control — address and data byte lane enable/disable.
func (p *FmcV1FMC) WriteCMDCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x000c, uint32(val))
}

// ReadCE0CTRL reads CE0 control — I/O mode, clock, SPI command, dummy cycles, access mode.
func (p *FmcV1FMC) ReadCE0CTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0010))
}

// WriteCE0CTRL writes CE0 control — I/O mode, clock, SPI command, dummy cycles, access mode.
func (p *FmcV1FMC) WriteCE0CTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x0010, uint32(val))
}

// ReadCE1CTRL reads CE1 control (same layout as CE0_CTRL).
func (p *FmcV1FMC) ReadCE1CTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0014))
}

// WriteCE1CTRL writes CE1 control (same layout as CE0_CTRL).
func (p *FmcV1FMC) WriteCE1CTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x0014, uint32(val))
}

// ReadCE0ADDRRANGE reads CE0 address decoding range (start/end bits[27:19] in 512 KB units).
func (p *FmcV1FMC) ReadCE0ADDRRANGE() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0030))
}

// WriteCE0ADDRRANGE writes CE0 address decoding range (start/end bits[27:19] in 512 KB units).
func (p *FmcV1FMC) WriteCE0ADDRRANGE(val uint32) {
    reg.Write(uint32(p.Base)+0x0030, uint32(val))
}

// ReadCE1ADDRRANGE reads CE1 address decoding range.
func (p *FmcV1FMC) ReadCE1ADDRRANGE() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0034))
}

// WriteCE1ADDRRANGE writes CE1 address decoding range.
func (p *FmcV1FMC) WriteCE1ADDRRANGE(val uint32) {
    reg.Write(uint32(p.Base)+0x0034, uint32(val))
}

// ReadAUTOSOFTRSTCTRL reads Auto soft-reset after watchdog. When enabled, hardware issues 0x66→0x99 after WDT reset to restore SPI volatile configuration bits.
func (p *FmcV1FMC) ReadAUTOSOFTRSTCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0050))
}

// WriteAUTOSOFTRSTCTRL writes Auto soft-reset after watchdog. When enabled, hardware issues 0x66→0x99 after WDT reset to restore SPI volatile configuration bits.
func (p *FmcV1FMC) WriteAUTOSOFTRSTCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x0050, uint32(val))
}

// ReadDUMMYCYCLEDATA reads Data output during head of dummy cycles (shared by all CEs).
func (p *FmcV1FMC) ReadDUMMYCYCLEDATA() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0054))
}

// WriteDUMMYCYCLEDATA writes Data output during head of dummy cycles (shared by all CEs).
func (p *FmcV1FMC) WriteDUMMYCYCLEDATA(val uint32) {
    reg.Write(uint32(p.Base)+0x0054, uint32(val))
}

// ReadWDT1CTRL reads WDT1 — address mode detection watchdog (2s timeout). On timeout, resets CPU and toggles CE0 between 3B/4B address mode. Stops after 2 toggles. Used to auto-detect flash address mode.
func (p *FmcV1FMC) ReadWDT1CTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0060))
}

// WriteWDT1CTRL writes WDT1 — address mode detection watchdog (2s timeout). On timeout, resets CPU and toggles CE0 between 3B/4B address mode. Stops after 2 toggles. Used to auto-detect flash address mode.
func (p *FmcV1FMC) WriteWDT1CTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x0060, uint32(val))
}

// ReadWDT2CTRL reads WDT2 — alternate boot watchdog. On timeout, firmware switches boot flash source (CE0↔CE1 or primary↔alternate depending on ABR mode). Set BOOT_SRC_SEL to indicate current selection.
func (p *FmcV1FMC) ReadWDT2CTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0064))
}

// WriteWDT2CTRL writes WDT2 — alternate boot watchdog. On timeout, firmware switches boot flash source (CE0↔CE1 or primary↔alternate depending on ABR mode). Set BOOT_SRC_SEL to indicate current selection.
func (p *FmcV1FMC) WriteWDT2CTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x0064, uint32(val))
}

// ReadWDT2RELOAD reads WDT2 timer reload value (unit: 0.1 s). Default 0xE0 = 22 s. Firmware must restart within this time by writing 0x4755 to WDT2_RESTART.
func (p *FmcV1FMC) ReadWDT2RELOAD() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0068))
}

// WriteWDT2RELOAD writes WDT2 timer reload value (unit: 0.1 s). Default 0xE0 = 22 s. Firmware must restart within this time by writing 0x4755 to WDT2_RESTART.
func (p *FmcV1FMC) WriteWDT2RELOAD(val uint32) {
    reg.Write(uint32(p.Base)+0x0068, uint32(val))
}

// ReadWDT2RESTART reads Write 0x4755 to reload and restart WDT2 countdown.
func (p *FmcV1FMC) ReadWDT2RESTART() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x006c))
}

// WriteWDT2RESTART writes Write 0x4755 to reload and restart WDT2 countdown.
func (p *FmcV1FMC) WriteWDT2RESTART(val uint32) {
    reg.Write(uint32(p.Base)+0x006c, uint32(val))
}

// ReadDMABUFMODELEN reads DMA FIFO buffer mode length in 4-byte units (0x40 = full 256 bytes).
func (p *FmcV1FMC) ReadDMABUFMODELEN() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x007c))
}

// WriteDMABUFMODELEN writes DMA FIFO buffer mode length in 4-byte units (0x40 = full 256 bytes).
func (p *FmcV1FMC) WriteDMABUFMODELEN(val uint32) {
    reg.Write(uint32(p.Base)+0x007c, uint32(val))
}

// ReadDMACTRL reads DMA control/status — direction, buffer/memory mode, checksum, enable.
func (p *FmcV1FMC) ReadDMACTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0080))
}

// WriteDMACTRL writes DMA control/status — direction, buffer/memory mode, checksum, enable.
func (p *FmcV1FMC) WriteDMACTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x0080, uint32(val))
}

// ReadDMAFLASHADDR reads DMA flash-side start address (4-byte aligned).
func (p *FmcV1FMC) ReadDMAFLASHADDR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0084))
}

// WriteDMAFLASHADDR writes DMA flash-side start address (4-byte aligned).
func (p *FmcV1FMC) WriteDMAFLASHADDR(val uint32) {
    reg.Write(uint32(p.Base)+0x0084, uint32(val))
}

// ReadDMARAMADDR reads DMA DRAM/SRAM-side start address (4-byte aligned, memory mode only).
func (p *FmcV1FMC) ReadDMARAMADDR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0088))
}

// WriteDMARAMADDR writes DMA DRAM/SRAM-side start address (4-byte aligned, memory mode only).
func (p *FmcV1FMC) WriteDMARAMADDR(val uint32) {
    reg.Write(uint32(p.Base)+0x0088, uint32(val))
}

// ReadDMALEN reads DMA transfer length in bytes (counts down during transfer).
func (p *FmcV1FMC) ReadDMALEN() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x008c))
}

// WriteDMALEN writes DMA transfer length in bytes (counts down during transfer).
func (p *FmcV1FMC) WriteDMALEN(val uint32) {
    reg.Write(uint32(p.Base)+0x008c, uint32(val))
}

// ReadDMACHECKSUM reads Running 32-bit checksum over flash read data (reset when DMA disabled).
func (p *FmcV1FMC) ReadDMACHECKSUM() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0090))
}

// WriteDMACHECKSUM writes Running 32-bit checksum over flash read data (reset when DMA disabled).
func (p *FmcV1FMC) WriteDMACHECKSUM(val uint32) {
    reg.Write(uint32(p.Base)+0x0090, uint32(val))
}

// ReadCE0READTIMING reads CE0 SPI flash read timing compensation (per-HCLK-divisor input delay).
func (p *FmcV1FMC) ReadCE0READTIMING() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0094))
}

// WriteCE0READTIMING writes CE0 SPI flash read timing compensation (per-HCLK-divisor input delay).
func (p *FmcV1FMC) WriteCE0READTIMING(val uint32) {
    reg.Write(uint32(p.Base)+0x0094, uint32(val))
}

// ReadCE1READTIMING reads CE1 SPI flash read timing compensation.
func (p *FmcV1FMC) ReadCE1READTIMING() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0098))
}

// WriteCE1READTIMING writes CE1 SPI flash read timing compensation.
func (p *FmcV1FMC) WriteCE1READTIMING(val uint32) {
    reg.Write(uint32(p.Base)+0x0098, uint32(val))
}

// ReadCMDFILTERCTRL reads Command filter control — enable per-CE and always-allow read commands.
func (p *FmcV1FMC) ReadCMDFILTERCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00a0))
}

// WriteCMDFILTERCTRL writes Command filter control — enable per-CE and always-allow read commands.
func (p *FmcV1FMC) WriteCMDFILTERCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x00a0, uint32(val))
}

// ReadWRITEFILTERCTRL reads Write address filter mode per filter entry (2 bits each, up to 8 filters).
func (p *FmcV1FMC) ReadWRITEFILTERCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00a4))
}

// WriteWRITEFILTERCTRL writes Write address filter mode per filter entry (2 bits each, up to 8 filters).
func (p *FmcV1FMC) WriteWRITEFILTERCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x00a4, uint32(val))
}

// ReadLOCKSRST reads Register lock control — bits lock corresponding registers until SRST#.
func (p *FmcV1FMC) ReadLOCKSRST() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00a8))
}

// WriteLOCKSRST writes Register lock control — bits lock corresponding registers until SRST#.
func (p *FmcV1FMC) WriteLOCKSRST(val uint32) {
    reg.Write(uint32(p.Base)+0x00a8, uint32(val))
}

// ReadLOCKWDT reads Register lock control — bits lock corresponding registers until WDT reset.
func (p *FmcV1FMC) ReadLOCKWDT() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00ac))
}

// WriteLOCKWDT writes Register lock control — bits lock corresponding registers until WDT reset.
func (p *FmcV1FMC) WriteLOCKWDT(val uint32) {
    reg.Write(uint32(p.Base)+0x00ac, uint32(val))
}

// ReadWRITEADDRFILTER1 reads Write address filter
func (p *FmcV1FMC) ReadWRITEADDRFILTER1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00b0))
}

// WriteWRITEADDRFILTER1 writes Write address filter
func (p *FmcV1FMC) WriteWRITEADDRFILTER1(val uint32) {
    reg.Write(uint32(p.Base)+0x00b0, uint32(val))
}

// ReadWRITEADDRFILTER2 reads Write address filter
func (p *FmcV1FMC) ReadWRITEADDRFILTER2() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00b4))
}

// WriteWRITEADDRFILTER2 writes Write address filter
func (p *FmcV1FMC) WriteWRITEADDRFILTER2(val uint32) {
    reg.Write(uint32(p.Base)+0x00b4, uint32(val))
}

// ReadWRITEADDRFILTER3 reads Write address filter
func (p *FmcV1FMC) ReadWRITEADDRFILTER3() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00b8))
}

// WriteWRITEADDRFILTER3 writes Write address filter
func (p *FmcV1FMC) WriteWRITEADDRFILTER3(val uint32) {
    reg.Write(uint32(p.Base)+0x00b8, uint32(val))
}

// ReadWRITEADDRFILTER4 reads Write address filter
func (p *FmcV1FMC) ReadWRITEADDRFILTER4() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00bc))
}

// WriteWRITEADDRFILTER4 writes Write address filter
func (p *FmcV1FMC) WriteWRITEADDRFILTER4(val uint32) {
    reg.Write(uint32(p.Base)+0x00bc, uint32(val))
}

// ReadWRITEADDRFILTER5 reads Write address filter
func (p *FmcV1FMC) ReadWRITEADDRFILTER5() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00c0))
}

// WriteWRITEADDRFILTER5 writes Write address filter
func (p *FmcV1FMC) WriteWRITEADDRFILTER5(val uint32) {
    reg.Write(uint32(p.Base)+0x00c0, uint32(val))
}

// ReadWRITEADDRFILTER6 reads Write address filter
func (p *FmcV1FMC) ReadWRITEADDRFILTER6() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00c4))
}

// WriteWRITEADDRFILTER6 writes Write address filter
func (p *FmcV1FMC) WriteWRITEADDRFILTER6(val uint32) {
    reg.Write(uint32(p.Base)+0x00c4, uint32(val))
}

// ReadWRITEADDRFILTER7 reads Write address filter
func (p *FmcV1FMC) ReadWRITEADDRFILTER7() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00c8))
}

// WriteWRITEADDRFILTER7 writes Write address filter
func (p *FmcV1FMC) WriteWRITEADDRFILTER7(val uint32) {
    reg.Write(uint32(p.Base)+0x00c8, uint32(val))
}

// ReadWRITEADDRFILTER8 reads Write address filter
func (p *FmcV1FMC) ReadWRITEADDRFILTER8() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00cc))
}

// WriteWRITEADDRFILTER8 writes Write address filter
func (p *FmcV1FMC) WriteWRITEADDRFILTER8(val uint32) {
    reg.Write(uint32(p.Base)+0x00cc, uint32(val))
}

// ReadFQCD0 reads Fully Qualified Command table entry 0 (predefined: EN4B — enter 4-byte mode).
func (p *FmcV1FMC) ReadFQCD0() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0100))
}

// WriteFQCD0 writes Fully Qualified Command table entry 0 (predefined: EN4B — enter 4-byte mode).
func (p *FmcV1FMC) WriteFQCD0(val uint32) {
    reg.Write(uint32(p.Base)+0x0100, uint32(val))
}

// ReadFQCD1 reads FQCD entry 1 (predefined: EX4B — exit 4-byte mode).
func (p *FmcV1FMC) ReadFQCD1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0104))
}

// WriteFQCD1 writes FQCD entry 1 (predefined: EX4B — exit 4-byte mode).
func (p *FmcV1FMC) WriteFQCD1(val uint32) {
    reg.Write(uint32(p.Base)+0x0104, uint32(val))
}

// ReadFQCD2 reads FQCD entry 2 (predefined: EQIO — enter QPI mode).
func (p *FmcV1FMC) ReadFQCD2() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0108))
}

// WriteFQCD2 writes FQCD entry 2 (predefined: EQIO — enter QPI mode).
func (p *FmcV1FMC) WriteFQCD2(val uint32) {
    reg.Write(uint32(p.Base)+0x0108, uint32(val))
}

// ReadFQCD3 reads FQCD entry 3 (predefined: RSTQIO — reset/exit QPI mode).
func (p *FmcV1FMC) ReadFQCD3() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x010c))
}

// WriteFQCD3 writes FQCD entry 3 (predefined: RSTQIO — reset/exit QPI mode).
func (p *FmcV1FMC) WriteFQCD3(val uint32) {
    reg.Write(uint32(p.Base)+0x010c, uint32(val))
}

// ReadFQCD4 reads FQCD entry 4 — general purpose.
func (p *FmcV1FMC) ReadFQCD4() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0110))
}

// WriteFQCD4 writes FQCD entry 4 — general purpose.
func (p *FmcV1FMC) WriteFQCD4(val uint32) {
    reg.Write(uint32(p.Base)+0x0110, uint32(val))
}

// ReadFQCD5 reads FQCD entry 5 — general purpose.
func (p *FmcV1FMC) ReadFQCD5() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0114))
}

// WriteFQCD5 writes FQCD entry 5 — general purpose.
func (p *FmcV1FMC) WriteFQCD5(val uint32) {
    reg.Write(uint32(p.Base)+0x0114, uint32(val))
}

// ReadFQCD6 reads FQCD entry 6 — general purpose.
func (p *FmcV1FMC) ReadFQCD6() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0118))
}

// WriteFQCD6 writes FQCD entry 6 — general purpose.
func (p *FmcV1FMC) WriteFQCD6(val uint32) {
    reg.Write(uint32(p.Base)+0x0118, uint32(val))
}

// ReadFQCD7 reads FQCD entry 7 — general purpose.
func (p *FmcV1FMC) ReadFQCD7() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x011c))
}

// WriteFQCD7 writes FQCD entry 7 — general purpose.
func (p *FmcV1FMC) WriteFQCD7(val uint32) {
    reg.Write(uint32(p.Base)+0x011c, uint32(val))
}

// ReadFQCD8 reads FQCD entry 8 — general purpose.
func (p *FmcV1FMC) ReadFQCD8() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0120))
}

// WriteFQCD8 writes FQCD entry 8 — general purpose.
func (p *FmcV1FMC) WriteFQCD8(val uint32) {
    reg.Write(uint32(p.Base)+0x0120, uint32(val))
}

// ReadFQCD9 reads FQCD entry 9 — general purpose.
func (p *FmcV1FMC) ReadFQCD9() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0124))
}

// WriteFQCD9 writes FQCD entry 9 — general purpose.
func (p *FmcV1FMC) WriteFQCD9(val uint32) {
    reg.Write(uint32(p.Base)+0x0124, uint32(val))
}

// ReadFQCD10 reads FQCD entry 10 — general purpose.
func (p *FmcV1FMC) ReadFQCD10() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0128))
}

// WriteFQCD10 writes FQCD entry 10 — general purpose.
func (p *FmcV1FMC) WriteFQCD10(val uint32) {
    reg.Write(uint32(p.Base)+0x0128, uint32(val))
}

// ReadFQCD11 reads FQCD entry 11 — general purpose.
func (p *FmcV1FMC) ReadFQCD11() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x012c))
}

// WriteFQCD11 writes FQCD entry 11 — general purpose.
func (p *FmcV1FMC) WriteFQCD11(val uint32) {
    reg.Write(uint32(p.Base)+0x012c, uint32(val))
}

// ReadFQCD12 reads FQCD entry 12 — general purpose.
func (p *FmcV1FMC) ReadFQCD12() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0130))
}

// WriteFQCD12 writes FQCD entry 12 — general purpose.
func (p *FmcV1FMC) WriteFQCD12(val uint32) {
    reg.Write(uint32(p.Base)+0x0130, uint32(val))
}

// ReadFQCD13 reads FQCD entry 13 — general purpose.
func (p *FmcV1FMC) ReadFQCD13() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0134))
}

// WriteFQCD13 writes FQCD entry 13 — general purpose.
func (p *FmcV1FMC) WriteFQCD13(val uint32) {
    reg.Write(uint32(p.Base)+0x0134, uint32(val))
}

// ReadFQCD14 reads FQCD entry 14 — general purpose.
func (p *FmcV1FMC) ReadFQCD14() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0138))
}

// WriteFQCD14 writes FQCD entry 14 — general purpose.
func (p *FmcV1FMC) WriteFQCD14(val uint32) {
    reg.Write(uint32(p.Base)+0x0138, uint32(val))
}

// ReadFQCD15 reads FQCD entry 15 — general purpose.
func (p *FmcV1FMC) ReadFQCD15() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x013c))
}

// WriteFQCD15 writes FQCD entry 15 — general purpose.
func (p *FmcV1FMC) WriteFQCD15(val uint32) {
    reg.Write(uint32(p.Base)+0x013c, uint32(val))
}

// ReadFQCD16 reads FQCD entry 16 — general purpose.
func (p *FmcV1FMC) ReadFQCD16() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0140))
}

// WriteFQCD16 writes FQCD entry 16 — general purpose.
func (p *FmcV1FMC) WriteFQCD16(val uint32) {
    reg.Write(uint32(p.Base)+0x0140, uint32(val))
}

// ReadFQCD17 reads FQCD entry 17 — general purpose.
func (p *FmcV1FMC) ReadFQCD17() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0144))
}

// WriteFQCD17 writes FQCD entry 17 — general purpose.
func (p *FmcV1FMC) WriteFQCD17(val uint32) {
    reg.Write(uint32(p.Base)+0x0144, uint32(val))
}

// ReadFQCD18 reads FQCD entry 18 — general purpose.
func (p *FmcV1FMC) ReadFQCD18() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0148))
}

// WriteFQCD18 writes FQCD entry 18 — general purpose.
func (p *FmcV1FMC) WriteFQCD18(val uint32) {
    reg.Write(uint32(p.Base)+0x0148, uint32(val))
}

// ReadFQCD19 reads FQCD entry 19 (predefined: WREAR — write extended address register).
func (p *FmcV1FMC) ReadFQCD19() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x014c))
}

// WriteFQCD19 writes FQCD entry 19 (predefined: WREAR — write extended address register).
func (p *FmcV1FMC) WriteFQCD19(val uint32) {
    reg.Write(uint32(p.Base)+0x014c, uint32(val))
}

// ReadAQCD0 reads Address Qualified Command entry 0 (predefined: page program 0x02, read 0xXX).
func (p *FmcV1FMC) ReadAQCD0() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0150))
}

// WriteAQCD0 writes Address Qualified Command entry 0 (predefined: page program 0x02, read 0xXX).
func (p *FmcV1FMC) WriteAQCD0(val uint32) {
    reg.Write(uint32(p.Base)+0x0150, uint32(val))
}

// ReadAQCD1 reads AQCD entry 1 (predefined: sector erase 0xD8).
func (p *FmcV1FMC) ReadAQCD1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0154))
}

// WriteAQCD1 writes AQCD entry 1 (predefined: sector erase 0xD8).
func (p *FmcV1FMC) WriteAQCD1(val uint32) {
    reg.Write(uint32(p.Base)+0x0154, uint32(val))
}

// ReadAQCD2 reads AQCD entry 2 — general purpose.
func (p *FmcV1FMC) ReadAQCD2() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0158))
}

// WriteAQCD2 writes AQCD entry 2 — general purpose.
func (p *FmcV1FMC) WriteAQCD2(val uint32) {
    reg.Write(uint32(p.Base)+0x0158, uint32(val))
}

// ReadAQCD3 reads AQCD entry 3 — general purpose.
func (p *FmcV1FMC) ReadAQCD3() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x015c))
}

// WriteAQCD3 writes AQCD entry 3 — general purpose.
func (p *FmcV1FMC) WriteAQCD3(val uint32) {
    reg.Write(uint32(p.Base)+0x015c, uint32(val))
}

// ReadAQCD4 reads AQCD entry 4 — general purpose.
func (p *FmcV1FMC) ReadAQCD4() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0160))
}

// WriteAQCD4 writes AQCD entry 4 — general purpose.
func (p *FmcV1FMC) WriteAQCD4(val uint32) {
    reg.Write(uint32(p.Base)+0x0160, uint32(val))
}

// ReadAQCD5 reads AQCD entry 5 — general purpose.
func (p *FmcV1FMC) ReadAQCD5() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0164))
}

// WriteAQCD5 writes AQCD entry 5 — general purpose.
func (p *FmcV1FMC) WriteAQCD5(val uint32) {
    reg.Write(uint32(p.Base)+0x0164, uint32(val))
}

// ReadAQCD6 reads AQCD entry 6 — general purpose.
func (p *FmcV1FMC) ReadAQCD6() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0168))
}

// WriteAQCD6 writes AQCD entry 6 — general purpose.
func (p *FmcV1FMC) WriteAQCD6(val uint32) {
    reg.Write(uint32(p.Base)+0x0168, uint32(val))
}

// ReadAQCD7 reads AQCD entry 7 — general purpose.
func (p *FmcV1FMC) ReadAQCD7() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x016c))
}

// WriteAQCD7 writes AQCD entry 7 — general purpose.
func (p *FmcV1FMC) WriteAQCD7(val uint32) {
    reg.Write(uint32(p.Base)+0x016c, uint32(val))
}

// ReadAQCD8 reads AQCD entry 8 — general purpose.
func (p *FmcV1FMC) ReadAQCD8() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0170))
}

// WriteAQCD8 writes AQCD entry 8 — general purpose.
func (p *FmcV1FMC) WriteAQCD8(val uint32) {
    reg.Write(uint32(p.Base)+0x0170, uint32(val))
}

// ReadAQCD9 reads AQCD entry 9 — general purpose.
func (p *FmcV1FMC) ReadAQCD9() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0174))
}

// WriteAQCD9 writes AQCD entry 9 — general purpose.
func (p *FmcV1FMC) WriteAQCD9(val uint32) {
    reg.Write(uint32(p.Base)+0x0174, uint32(val))
}

// ReadAQCD10 reads AQCD entry 10 — general purpose.
func (p *FmcV1FMC) ReadAQCD10() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0178))
}

// WriteAQCD10 writes AQCD entry 10 — general purpose.
func (p *FmcV1FMC) WriteAQCD10(val uint32) {
    reg.Write(uint32(p.Base)+0x0178, uint32(val))
}

// ReadAQCD11 reads AQCD entry 11 — general purpose.
func (p *FmcV1FMC) ReadAQCD11() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x017c))
}

// WriteAQCD11 writes AQCD entry 11 — general purpose.
func (p *FmcV1FMC) WriteAQCD11(val uint32) {
    reg.Write(uint32(p.Base)+0x017c, uint32(val))
}

