// Code generated by chiptool; DO NOT EDIT.

package pac

import "github.com/kyanitecomputer/aspeed-go/reg"

// HaceV1HACE ASPEED Hash and Crypto Engine (HACE). Base: 0x7E6D_0000. Two cascadeable engines: Hash (SHA/MD5/HMAC) and Crypto (AES/DES/3DES/RC4/AES-GCM).
type HaceV1HACE struct {
    Base uintptr
}

// ReadCRYPTOSRC reads Crypto data source base address (HACE00). Direct access mode: byte-aligned address [30:0]. Scatter-gather mode: 8-byte aligned SG list address [30:3]. In cascade (Hash→Crypto): must equal HASH_SRC.
func (p *HaceV1HACE) ReadCRYPTOSRC() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0000))
}

// WriteCRYPTOSRC writes Crypto data source base address (HACE00). Direct access mode: byte-aligned address [30:0]. Scatter-gather mode: 8-byte aligned SG list address [30:3]. In cascade (Hash→Crypto): must equal HASH_SRC.
func (p *HaceV1HACE) WriteCRYPTOSRC(val uint32) {
    reg.Write(uint32(p.Base)+0x0000, uint32(val))
}

// ReadCRYPTODST reads Crypto data destination base address (HACE04). Direct access: byte-aligned [30:0]. SG mode: [30:3]. In cascade (Crypto→Hash): must equal HASH_SRC.
func (p *HaceV1HACE) ReadCRYPTODST() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0004))
}

// WriteCRYPTODST writes Crypto data destination base address (HACE04). Direct access: byte-aligned [30:0]. SG mode: [30:3]. In cascade (Crypto→Hash): must equal HASH_SRC.
func (p *HaceV1HACE) WriteCRYPTODST(val uint32) {
    reg.Write(uint32(p.Base)+0x0004, uint32(val))
}

// ReadCRYPTOCTX reads Crypto context buffer base address (HACE08). 8-byte aligned [30:3]. Holds IV, keys, and intermediate state. Hardware loads before and saves after algorithm execution unless disabled.
func (p *HaceV1HACE) ReadCRYPTOCTX() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0008))
}

// WriteCRYPTOCTX writes Crypto context buffer base address (HACE08). 8-byte aligned [30:3]. Holds IV, keys, and intermediate state. Hardware loads before and saves after algorithm execution unless disabled.
func (p *HaceV1HACE) WriteCRYPTOCTX(val uint32) {
    reg.Write(uint32(p.Base)+0x0008, uint32(val))
}

// ReadCRYPTODATALEN reads Crypto data length in bytes (HACE0C). Bits[27:0], max 256 MB-1. In cascade mode must equal HASH_DATA_LEN. 0 is valid only for AES-GCM (zero-length confidential data).
func (p *HaceV1HACE) ReadCRYPTODATALEN() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x000c))
}

// WriteCRYPTODATALEN writes Crypto data length in bytes (HACE0C). Bits[27:0], max 256 MB-1. In cascade mode must equal HASH_DATA_LEN. 0 is valid only for AES-GCM (zero-length confidential data).
func (p *HaceV1HACE) WriteCRYPTODATALEN(val uint32) {
    reg.Write(uint32(p.Base)+0x000c, uint32(val))
}

// ReadCRYPTOCMD reads Crypto engine command register (HACE10). Select engine (AES/DES/RC4), algorithm, mode, direction, key source, cascade mode, DMA type (direct/SG), interrupt enable, and context I/O.
func (p *HaceV1HACE) ReadCRYPTOCMD() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0010))
}

// WriteCRYPTOCMD writes Crypto engine command register (HACE10). Select engine (AES/DES/RC4), algorithm, mode, direction, key source, cascade mode, DMA type (direct/SG), interrupt enable, and context I/O.
func (p *HaceV1HACE) WriteCRYPTOCMD(val uint32) {
    reg.Write(uint32(p.Base)+0x0010, uint32(val))
}

// ReadGCMAADLEN reads AES-GCM additional authenticated data (AAD) length in bytes (HACE14). Used when CRYPTO_CMD selects AES-GCM mode (OP_MODE=101).
func (p *HaceV1HACE) ReadGCMAADLEN() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0014))
}

// WriteGCMAADLEN writes AES-GCM additional authenticated data (AAD) length in bytes (HACE14). Used when CRYPTO_CMD selects AES-GCM mode (OP_MODE=101).
func (p *HaceV1HACE) WriteGCMAADLEN(val uint32) {
    reg.Write(uint32(p.Base)+0x0014, uint32(val))
}

// ReadGCMTAGBASE reads AES-GCM authentication tag write buffer base address (HACE18). Byte-aligned [30:0]. Tag is 16 bytes. Used when CRYPTO_CMD[21]=1.
func (p *HaceV1HACE) ReadGCMTAGBASE() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0018))
}

// WriteGCMTAGBASE writes AES-GCM authentication tag write buffer base address (HACE18). Byte-aligned [30:0]. Tag is 16 bytes. Used when CRYPTO_CMD[21]=1.
func (p *HaceV1HACE) WriteGCMTAGBASE(val uint32) {
    reg.Write(uint32(p.Base)+0x0018, uint32(val))
}

// ReadHACESTATUS reads HAC engine status and interrupt register (HACE1C). Interrupt flags for crypto, hash, and software tag events. Engine busy status bits.
func (p *HaceV1HACE) ReadHACESTATUS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x001c))
}

// WriteHACESTATUS writes HAC engine status and interrupt register (HACE1C). Interrupt flags for crypto, hash, and software tag events. Engine busy status bits.
func (p *HaceV1HACE) WriteHACESTATUS(val uint32) {
    reg.Write(uint32(p.Base)+0x001c, uint32(val))
}

// ReadHASHSRC reads Hash data source base address (HACE20). Direct access: byte-aligned [30:0]. SG mode: 8-byte aligned [30:3]. Cascade: Crypto→Hash: must equal CRYPTO_DST; Hash→Crypto: equal CRYPTO_SRC.
func (p *HaceV1HACE) ReadHASHSRC() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0020))
}

// WriteHASHSRC writes Hash data source base address (HACE20). Direct access: byte-aligned [30:0]. SG mode: 8-byte aligned [30:3]. Cascade: Crypto→Hash: must equal CRYPTO_DST; Hash→Crypto: equal CRYPTO_SRC.
func (p *HaceV1HACE) WriteHASHSRC(val uint32) {
    reg.Write(uint32(p.Base)+0x0020, uint32(val))
}

// ReadHASHDIGESTBASE reads Hash digest write buffer base address (HACE24). 8-byte aligned [30:3]. Buffer sizes: MD5=16 B, SHA-1=20 B, SHA-224/256=32 B, SHA-384/512/512-x=64 B.
func (p *HaceV1HACE) ReadHASHDIGESTBASE() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0024))
}

// WriteHASHDIGESTBASE writes Hash digest write buffer base address (HACE24). 8-byte aligned [30:3]. Buffer sizes: MD5=16 B, SHA-1=20 B, SHA-224/256=32 B, SHA-384/512/512-x=64 B.
func (p *HaceV1HACE) WriteHASHDIGESTBASE(val uint32) {
    reg.Write(uint32(p.Base)+0x0024, uint32(val))
}

// ReadHASHKEYBASE reads HMAC key buffer base address (HACE28). 8-byte aligned [30:3]. Stores result of HMAC key calculation command.
func (p *HaceV1HACE) ReadHASHKEYBASE() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0028))
}

// WriteHASHKEYBASE writes HMAC key buffer base address (HACE28). 8-byte aligned [30:3]. Stores result of HMAC key calculation command.
func (p *HaceV1HACE) WriteHASHKEYBASE(val uint32) {
    reg.Write(uint32(p.Base)+0x0028, uint32(val))
}

// ReadHASHDATALEN reads Hash data length in bytes (HACE2C). Bits[27:0], max 256 MB-1. Alignment requirements vary by algorithm and accumulative mode. In cascade mode must equal CRYPTO_DATA_LEN.
func (p *HaceV1HACE) ReadHASHDATALEN() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x002c))
}

// WriteHASHDATALEN writes Hash data length in bytes (HACE2C). Bits[27:0], max 256 MB-1. Alignment requirements vary by algorithm and accumulative mode. In cascade mode must equal CRYPTO_DATA_LEN.
func (p *HaceV1HACE) WriteHASHDATALEN(val uint32) {
    reg.Write(uint32(p.Base)+0x002c, uint32(val))
}

// ReadHASHCMD reads Hash engine command register (HACE30). Select algorithm, HMAC/accumulative mode, byte-swap, cascade mode, SG or direct access, interrupt enable, first/last block indicators.
func (p *HaceV1HACE) ReadHASHCMD() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0030))
}

// WriteHASHCMD writes Hash engine command register (HACE30). Select algorithm, HMAC/accumulative mode, byte-swap, cascade mode, SG or direct access, interrupt enable, first/last block indicators.
func (p *HaceV1HACE) WriteHASHCMD(val uint32) {
    reg.Write(uint32(p.Base)+0x0030, uint32(val))
}

// ReadHASHPADLEN reads Hash data padding length (HACE34). Used in the padding block when in accumulative mode with last block set.
func (p *HaceV1HACE) ReadHASHPADLEN() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0034))
}

// WriteHASHPADLEN writes Hash data padding length (HACE34). Used in the padding block when in accumulative mode with last block set.
func (p *HaceV1HACE) WriteHASHPADLEN(val uint32) {
    reg.Write(uint32(p.Base)+0x0034, uint32(val))
}

// ReadCQBASE reads Command Queue base address in DRAM (HACE50). 16-byte aligned [30:4]. Configure before enabling CQ in HACE60.
func (p *HaceV1HACE) ReadCQBASE() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0050))
}

// WriteCQBASE writes Command Queue base address in DRAM (HACE50). 16-byte aligned [30:4]. Configure before enabling CQ in HACE60.
func (p *HaceV1HACE) WriteCQBASE(val uint32) {
    reg.Write(uint32(p.Base)+0x0050, uint32(val))
}

// ReadCQENDPTR reads Command Queue end pointer offset (HACE54). 16-byte aligned [11:1]. Defines the end of the circular CQ buffer.
func (p *HaceV1HACE) ReadCQENDPTR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0054))
}

// WriteCQENDPTR writes Command Queue end pointer offset (HACE54). 16-byte aligned [11:1]. Defines the end of the circular CQ buffer.
func (p *HaceV1HACE) WriteCQENDPTR(val uint32) {
    reg.Write(uint32(p.Base)+0x0054, uint32(val))
}

// ReadCQWRITEPTR reads Command Queue write pointer (HACE58). 8-byte aligned [11:0]. Write before enabling CQ.
func (p *HaceV1HACE) ReadCQWRITEPTR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0058))
}

// WriteCQWRITEPTR writes Command Queue write pointer (HACE58). 8-byte aligned [11:0]. Write before enabling CQ.
func (p *HaceV1HACE) WriteCQWRITEPTR(val uint32) {
    reg.Write(uint32(p.Base)+0x0058, uint32(val))
}

// ReadCQREADPTR reads Command Queue read pointer (HACE5C). 8-byte aligned [11:0]. Read-only; hardware-managed.
func (p *HaceV1HACE) ReadCQREADPTR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x005c))
}

// WriteCQREADPTR writes Command Queue read pointer (HACE5C). 8-byte aligned [11:0]. Read-only; hardware-managed.
func (p *HaceV1HACE) WriteCQREADPTR(val uint32) {
    reg.Write(uint32(p.Base)+0x005c, uint32(val))
}

// ReadHACEFEATURE reads HACE feature control register (HACE60). Enable DRAM command queue, set CQ data format (single vs burst), select AES/DES CTR counter width, control register write source (AHB vs CQ).
func (p *HaceV1HACE) ReadHACEFEATURE() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0060))
}

// WriteHACEFEATURE writes HACE feature control register (HACE60). Enable DRAM command queue, set CQ data format (single vs burst), select AES/DES CTR counter width, control register write source (AHB vs CQ).
func (p *HaceV1HACE) WriteHACEFEATURE(val uint32) {
    reg.Write(uint32(p.Base)+0x0060, uint32(val))
}

// ReadSWTAG reads Software tag register (HACE64). Write a tag value to trigger a software interrupt (when HACE64[31]=1). The 28-bit SW_TAG value is stored; interrupt fires when value is written. Also controls whether to wait for crypto/hash idle before updating.
func (p *HaceV1HACE) ReadSWTAG() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0064))
}

// WriteSWTAG writes Software tag register (HACE64). Write a tag value to trigger a software interrupt (when HACE64[31]=1). The 28-bit SW_TAG value is stored; interrupt fires when value is written. Also controls whether to wait for crypto/hash idle before updating.
func (p *HaceV1HACE) WriteSWTAG(val uint32) {
    reg.Write(uint32(p.Base)+0x0064, uint32(val))
}

