// Code generated by chiptool; DO NOT EDIT.

package pac

import "github.com/kyanitecomputer/aspeed-go/reg"

// I2cV1I2C ASPEED I2C/SMBus per-channel registers (new register mode). Base: 0x7E7B_0000 + 0x80 + (N × 0x80) for channel N (0–13). Requires I2CG0C[2]=1 (new register mode) to be enabled globally.
type I2cV1I2C struct {
    Base uintptr
}

// ReadFUNCCTRL reads Master/slave function control register (I2CC00). Enables master and/or slave function, selects operating modes. Clearing both ENBL_MASTER_FN and ENBL_SLAVE_FN simultaneously resets all state machines and clears interrupt status registers.
func (p *I2cV1I2C) ReadFUNCCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0000))
}

// WriteFUNCCTRL writes Master/slave function control register (I2CC00). Enables master and/or slave function, selects operating modes. Clearing both ENBL_MASTER_FN and ENBL_SLAVE_FN simultaneously resets all state machines and clears interrupt status registers.
func (p *I2cV1I2C) WriteFUNCCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x0000, uint32(val))
}

// ReadCLKTIMING reads Master/slave clock and AC timing control register (I2CC04). Sets SCL frequency, data hold time, and timeout. SCL frequency = FreqBase / (tCKLow + tCKHigh).
func (p *I2cV1I2C) ReadCLKTIMING() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0004))
}

// WriteCLKTIMING writes Master/slave clock and AC timing control register (I2CC04). Sets SCL frequency, data hold time, and timeout. SCL frequency = FreqBase / (tCKLow + tCKHigh).
func (p *I2cV1I2C) WriteCLKTIMING(val uint32) {
    reg.Write(uint32(p.Base)+0x0004, uint32(val))
}

// ReadTXRXBUF reads Master/slave byte buffer and bus state register (I2CC08). Upper 16 bits: bus state (read-only). Lower 16 bits: TX byte buffer [15:8], RX byte buffer [7:0]. Valid only in byte mode (pool and DMA modes bypass this register).
func (p *I2cV1I2C) ReadTXRXBUF() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0008))
}

// WriteTXRXBUF writes Master/slave byte buffer and bus state register (I2CC08). Upper 16 bits: bus state (read-only). Lower 16 bits: TX byte buffer [15:8], RX byte buffer [7:0]. Valid only in byte mode (pool and DMA modes bypass this register).
func (p *I2cV1I2C) WriteTXRXBUF(val uint32) {
    reg.Write(uint32(p.Base)+0x0008, uint32(val))
}

// ReadPOOLCTRL reads Master/slave pool buffer control register (I2CC0C). Shared between master and slave — only one may use pool at a time. Pool and DMA modes are mutually exclusive.
func (p *I2cV1I2C) ReadPOOLCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x000c))
}

// WritePOOLCTRL writes Master/slave pool buffer control register (I2CC0C). Shared between master and slave — only one may use pool at a time. Pool and DMA modes are mutually exclusive.
func (p *I2cV1I2C) WritePOOLCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x000c, uint32(val))
}

// ReadMASTERIRQCTRL reads Master interrupt enable register (I2CM10). In packet operation mode, only ENBL_PKT_CMD_DONE_INT and/or ENBL_SMBUS_ALERT_INT need enabling; all other bits have no effect.
func (p *I2cV1I2C) ReadMASTERIRQCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0010))
}

// WriteMASTERIRQCTRL writes Master interrupt enable register (I2CM10). In packet operation mode, only ENBL_PKT_CMD_DONE_INT and/or ENBL_SMBUS_ALERT_INT need enabling; all other bits have no effect.
func (p *I2cV1I2C) WriteMASTERIRQCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x0010, uint32(val))
}

// ReadMASTERIRQSTATUS reads Master interrupt status register (I2CM14). Write-1-to-clear. In packet mode, clearing PKT_CMD_DONE_STS also clears bits[6:0,13:12,18:17].
func (p *I2cV1I2C) ReadMASTERIRQSTATUS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0014))
}

// WriteMASTERIRQSTATUS writes Master interrupt status register (I2CM14). Write-1-to-clear. In packet mode, clearing PKT_CMD_DONE_STS also clears bits[6:0,13:12,18:17].
func (p *I2cV1I2C) WriteMASTERIRQSTATUS(val uint32) {
    reg.Write(uint32(p.Base)+0x0014, uint32(val))
}

// ReadMASTERCMD reads Master command and control register (I2CM18). Step mode: set START_CMD first (highest priority), then TX_CMD or RX_CMD, then STOP_CMD. Hardware auto-clears each command bit when executed. Packet mode: set ENBL_MASTER_PKT_OP plus TARGET_ADDR. Bit[31] (W1T_CTRL) allows write-1-to-set without read-modify-write.
func (p *I2cV1I2C) ReadMASTERCMD() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0018))
}

// WriteMASTERCMD writes Master command and control register (I2CM18). Step mode: set START_CMD first (highest priority), then TX_CMD or RX_CMD, then STOP_CMD. Hardware auto-clears each command bit when executed. Packet mode: set ENBL_MASTER_PKT_OP plus TARGET_ADDR. Bit[31] (W1T_CTRL) allows write-1-to-set without read-modify-write.
func (p *I2cV1I2C) WriteMASTERCMD(val uint32) {
    reg.Write(uint32(p.Base)+0x0018, uint32(val))
}

// ReadMASTERDMALEN reads Master DMA transfer length register (I2CM1C). Configure before enabling DMA TX or RX. Bits[31] and [15] (W1T) allow updating TX and RX lengths independently.
func (p *I2cV1I2C) ReadMASTERDMALEN() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x001c))
}

// WriteMASTERDMALEN writes Master DMA transfer length register (I2CM1C). Configure before enabling DMA TX or RX. Bits[31] and [15] (W1T) allow updating TX and RX lengths independently.
func (p *I2cV1I2C) WriteMASTERDMALEN(val uint32) {
    reg.Write(uint32(p.Base)+0x001c, uint32(val))
}

// ReadSLAVEIRQCTRL reads Slave interrupt enable register (I2CS20). In packet mode, only ENBL_PKT_CMD_DONE_INT and/or ENBL_SLAVE_ADDR_NACKED_INT need enabling.
func (p *I2cV1I2C) ReadSLAVEIRQCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0020))
}

// WriteSLAVEIRQCTRL writes Slave interrupt enable register (I2CS20). In packet mode, only ENBL_PKT_CMD_DONE_INT and/or ENBL_SLAVE_ADDR_NACKED_INT need enabling.
func (p *I2cV1I2C) WriteSLAVEIRQCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x0020, uint32(val))
}

// ReadSLAVEIRQSTATUS reads Slave interrupt status register (I2CS24). Write-1-to-clear. In packet mode, clearing PKT_CMD_DONE_STS also clears bits[0,2,4:5,7,15,17]. Software must clear bits[2:0] after setting new commands.
func (p *I2cV1I2C) ReadSLAVEIRQSTATUS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0024))
}

// WriteSLAVEIRQSTATUS writes Slave interrupt status register (I2CS24). Write-1-to-clear. In packet mode, clearing PKT_CMD_DONE_STS also clears bits[0,2,4:5,7,15,17]. Software must clear bits[2:0] after setting new commands.
func (p *I2cV1I2C) WriteSLAVEIRQSTATUS(val uint32) {
    reg.Write(uint32(p.Base)+0x0024, uint32(val))
}

// ReadSLAVECMD reads Slave command and control register (I2CS28). Enables slave packet operation, sets active slave address, controls buffer selection, and issues transmit command. Bit[31] (W1T_CTRL) allows write-1-to-set without read-modify-write.
func (p *I2cV1I2C) ReadSLAVECMD() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0028))
}

// WriteSLAVECMD writes Slave command and control register (I2CS28). Enables slave packet operation, sets active slave address, controls buffer selection, and issues transmit command. Bit[31] (W1T_CTRL) allows write-1-to-set without read-modify-write.
func (p *I2cV1I2C) WriteSLAVECMD(val uint32) {
    reg.Write(uint32(p.Base)+0x0028, uint32(val))
}

// ReadSLAVEDMALEN reads Slave DMA transfer length register (I2CS2C). For slave RX, length may be set ≥ actual transfer (master may stop early).
func (p *I2cV1I2C) ReadSLAVEDMALEN() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x002c))
}

// WriteSLAVEDMALEN writes Slave DMA transfer length register (I2CS2C). For slave RX, length may be set ≥ actual transfer (master may stop early).
func (p *I2cV1I2C) WriteSLAVEDMALEN(val uint32) {
    reg.Write(uint32(p.Base)+0x002c, uint32(val))
}

// ReadMASTERDMATXBASE reads Master DMA transmit buffer base address in SDRAM (I2CM30). Configure before enabling master DMA TX. Hardware increments during transfer.
func (p *I2cV1I2C) ReadMASTERDMATXBASE() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0030))
}

// WriteMASTERDMATXBASE writes Master DMA transmit buffer base address in SDRAM (I2CM30). Configure before enabling master DMA TX. Hardware increments during transfer.
func (p *I2cV1I2C) WriteMASTERDMATXBASE(val uint32) {
    reg.Write(uint32(p.Base)+0x0030, uint32(val))
}

// ReadMASTERDMARXBASE reads Master DMA receive buffer base address in SDRAM (I2CM34).
func (p *I2cV1I2C) ReadMASTERDMARXBASE() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0034))
}

// WriteMASTERDMARXBASE writes Master DMA receive buffer base address in SDRAM (I2CM34).
func (p *I2cV1I2C) WriteMASTERDMARXBASE(val uint32) {
    reg.Write(uint32(p.Base)+0x0034, uint32(val))
}

// ReadSLAVEDMATXBASE reads Slave DMA transmit buffer base address in SDRAM (I2CS38).
func (p *I2cV1I2C) ReadSLAVEDMATXBASE() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0038))
}

// WriteSLAVEDMATXBASE writes Slave DMA transmit buffer base address in SDRAM (I2CS38).
func (p *I2cV1I2C) WriteSLAVEDMATXBASE(val uint32) {
    reg.Write(uint32(p.Base)+0x0038, uint32(val))
}

// ReadSLAVEDMARXBASE reads Slave DMA receive buffer base address in SDRAM (I2CS3C).
func (p *I2cV1I2C) ReadSLAVEDMARXBASE() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x003c))
}

// WriteSLAVEDMARXBASE writes Slave DMA receive buffer base address in SDRAM (I2CS3C).
func (p *I2cV1I2C) WriteSLAVEDMARXBASE(val uint32) {
    reg.Write(uint32(p.Base)+0x003c, uint32(val))
}

// ReadSLAVEADDR reads Slave device address register (I2CS40). Up to three 7-bit slave addresses. Address range mode (I2CC00[9]=1): SLAVE_ADDR1 ≤ incoming address ≤ SLAVE_ADDR2.
func (p *I2cV1I2C) ReadSLAVEADDR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0040))
}

// WriteSLAVEADDR writes Slave device address register (I2CS40). Up to three 7-bit slave addresses. Address range mode (I2CC00[9]=1): SLAVE_ADDR1 ≤ incoming address ≤ SLAVE_ADDR2.
func (p *I2cV1I2C) WriteSLAVEADDR(val uint32) {
    reg.Write(uint32(p.Base)+0x0040, uint32(val))
}

// ReadMASTERDMASTATUS reads Master DMA actual transfer length status (I2CM48). Read-only; write clears to 0. Also cleared by master packet operation start and by DMA start (TX and RX cleared independently).
func (p *I2cV1I2C) ReadMASTERDMASTATUS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0048))
}

// WriteMASTERDMASTATUS writes Master DMA actual transfer length status (I2CM48). Read-only; write clears to 0. Also cleared by master packet operation start and by DMA start (TX and RX cleared independently).
func (p *I2cV1I2C) WriteMASTERDMASTATUS(val uint32) {
    reg.Write(uint32(p.Base)+0x0048, uint32(val))
}

// ReadSLAVEDMASTATUS reads Slave DMA actual transfer length status (I2CS4C). Read-only; write clears to 0.
func (p *I2cV1I2C) ReadSLAVEDMASTATUS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x004c))
}

// WriteSLAVEDMASTATUS writes Slave DMA actual transfer length status (I2CS4C). Read-only; write clears to 0.
func (p *I2cV1I2C) WriteSLAVEDMASTATUS(val uint32) {
    reg.Write(uint32(p.Base)+0x004c, uint32(val))
}

// ReadCURDMAADDR reads Current DMA operating address (I2CC50). Read-only. Increments during DMA transfer.
func (p *I2cV1I2C) ReadCURDMAADDR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0050))
}

// WriteCURDMAADDR writes Current DMA operating address (I2CC50). Read-only. Increments during DMA transfer.
func (p *I2cV1I2C) WriteCURDMAADDR(val uint32) {
    reg.Write(uint32(p.Base)+0x0050, uint32(val))
}

// ReadCURDMALEN reads Current DMA remaining length (I2CC54). Read-only. Decrements during DMA transfer.
func (p *I2cV1I2C) ReadCURDMALEN() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0054))
}

// WriteCURDMALEN writes Current DMA remaining length (I2CC54). Read-only. Decrements during DMA transfer.
func (p *I2cV1I2C) WriteCURDMALEN(val uint32) {
    reg.Write(uint32(p.Base)+0x0054, uint32(val))
}

