// Code generated by chiptool; DO NOT EDIT.

package pac

import "github.com/kyanitecomputer/aspeed-go/reg"

// I2cbuffV1I2CBUFF ASPEED I2C/SMBus per-channel pool buffer SRAM (32 bytes = 8 × 32-bit words). Base: 0x7E7B_0C00 + (N × 0x20) for channel N (0–13). Organization: full 32-byte TX/RX, or split lower-16 TX / upper-16 RX via I2CC0C[0].
type I2cbuffV1I2CBUFF struct {
    Base uintptr
}

// ReadBUFF0 reads Pool buffer word 0 (bytes 0–3). TX data in all modes.
func (p *I2cbuffV1I2CBUFF) ReadBUFF0() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0000))
}

// WriteBUFF0 writes Pool buffer word 0 (bytes 0–3). TX data in all modes.
func (p *I2cbuffV1I2CBUFF) WriteBUFF0(val uint32) {
    reg.Write(uint32(p.Base)+0x0000, uint32(val))
}

// ReadBUFF1 reads Pool buffer word 1 (bytes 4–7).
func (p *I2cbuffV1I2CBUFF) ReadBUFF1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0004))
}

// WriteBUFF1 writes Pool buffer word 1 (bytes 4–7).
func (p *I2cbuffV1I2CBUFF) WriteBUFF1(val uint32) {
    reg.Write(uint32(p.Base)+0x0004, uint32(val))
}

// ReadBUFF2 reads Pool buffer word 2 (bytes 8–11).
func (p *I2cbuffV1I2CBUFF) ReadBUFF2() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0008))
}

// WriteBUFF2 writes Pool buffer word 2 (bytes 8–11).
func (p *I2cbuffV1I2CBUFF) WriteBUFF2(val uint32) {
    reg.Write(uint32(p.Base)+0x0008, uint32(val))
}

// ReadBUFF3 reads Pool buffer word 3 (bytes 12–15). Last TX word when I2CC0C[0]=1 (split mode); RX starts at BUFF4.
func (p *I2cbuffV1I2CBUFF) ReadBUFF3() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x000c))
}

// WriteBUFF3 writes Pool buffer word 3 (bytes 12–15). Last TX word when I2CC0C[0]=1 (split mode); RX starts at BUFF4.
func (p *I2cbuffV1I2CBUFF) WriteBUFF3(val uint32) {
    reg.Write(uint32(p.Base)+0x000c, uint32(val))
}

// ReadBUFF4 reads Pool buffer word 4 (bytes 16–19). First RX word when I2CC0C[0]=1 (split mode).
func (p *I2cbuffV1I2CBUFF) ReadBUFF4() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0010))
}

// WriteBUFF4 writes Pool buffer word 4 (bytes 16–19). First RX word when I2CC0C[0]=1 (split mode).
func (p *I2cbuffV1I2CBUFF) WriteBUFF4(val uint32) {
    reg.Write(uint32(p.Base)+0x0010, uint32(val))
}

// ReadBUFF5 reads Pool buffer word 5 (bytes 20–23).
func (p *I2cbuffV1I2CBUFF) ReadBUFF5() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0014))
}

// WriteBUFF5 writes Pool buffer word 5 (bytes 20–23).
func (p *I2cbuffV1I2CBUFF) WriteBUFF5(val uint32) {
    reg.Write(uint32(p.Base)+0x0014, uint32(val))
}

// ReadBUFF6 reads Pool buffer word 6 (bytes 24–27).
func (p *I2cbuffV1I2CBUFF) ReadBUFF6() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0018))
}

// WriteBUFF6 writes Pool buffer word 6 (bytes 24–27).
func (p *I2cbuffV1I2CBUFF) WriteBUFF6(val uint32) {
    reg.Write(uint32(p.Base)+0x0018, uint32(val))
}

// ReadBUFF7 reads Pool buffer word 7 (bytes 28–31). Last word in all modes.
func (p *I2cbuffV1I2CBUFF) ReadBUFF7() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x001c))
}

// WriteBUFF7 writes Pool buffer word 7 (bytes 28–31). Last word in all modes.
func (p *I2cbuffV1I2CBUFF) WriteBUFF7(val uint32) {
    reg.Write(uint32(p.Base)+0x001c, uint32(val))
}

