// Code generated by chiptool; DO NOT EDIT.

package pac

import "github.com/kyanitecomputer/aspeed-go/reg"

// I2cglobalV1I2CGLOBAL ASPEED I2C/SMBus global control registers. Base: 0x7E7B_0000.
type I2cglobalV1I2CGLOBAL struct {
    Base uintptr
}

// ReadIRQSTATUS reads Master (or merged master+slave) interrupt status (I2CG00). Read-only. Bit N-1 is set when device N has a pending interrupt. When I2CG0C[3]=0 (default), both master and slave interrupts aggregate here. When I2CG0C[3]=1, only master interrupts appear here. No write-clear needed; clear at the device channel interrupt register.
func (p *I2cglobalV1I2CGLOBAL) ReadIRQSTATUS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0000))
}

// WriteIRQSTATUS writes Master (or merged master+slave) interrupt status (I2CG00). Read-only. Bit N-1 is set when device N has a pending interrupt. When I2CG0C[3]=0 (default), both master and slave interrupts aggregate here. When I2CG0C[3]=1, only master interrupts appear here. No write-clear needed; clear at the device channel interrupt register.
func (p *I2cglobalV1I2CGLOBAL) WriteIRQSTATUS(val uint32) {
    reg.Write(uint32(p.Base)+0x0000, uint32(val))
}

// ReadSLAVEIRQSTATUS reads Slave interrupt status (I2CG04). Read-only. Valid only when I2CG0C[3]=1 (separate master/slave mode). Bit N-1 is set when device N has a pending slave interrupt.
func (p *I2cglobalV1I2CGLOBAL) ReadSLAVEIRQSTATUS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0004))
}

// WriteSLAVEIRQSTATUS writes Slave interrupt status (I2CG04). Read-only. Valid only when I2CG0C[3]=1 (separate master/slave mode). Bit N-1 is set when device N has a pending slave interrupt.
func (p *I2cglobalV1I2CGLOBAL) WriteSLAVEIRQSTATUS(val uint32) {
    reg.Write(uint32(p.Base)+0x0004, uint32(val))
}

// ReadGLOBALCTRL reads Global control register (I2CG0C). Controls register mode, clock divider mode, interrupt routing, and bus-recovery turnaround delay.
func (p *I2cglobalV1I2CGLOBAL) ReadGLOBALCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x000c))
}

// WriteGLOBALCTRL writes Global control register (I2CG0C). Controls register mode, clock divider mode, interrupt routing, and bus-recovery turnaround delay.
func (p *I2cglobalV1I2CGLOBAL) WriteGLOBALCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x000c, uint32(val))
}

// ReadCLKDIV reads New-mode clock divider control register (I2CG10). Valid when I2CG0C[1]=1 (new clock divider mode). Defines four base clock divisors used by per-channel I2CC04[3:0] selection. Divisor value N: effective divisor = N/2 + 0.5 (0x00=÷1, 0x01=÷1.5, ..., 0xFF=÷128.5).
func (p *I2cglobalV1I2CGLOBAL) ReadCLKDIV() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0010))
}

// WriteCLKDIV writes New-mode clock divider control register (I2CG10). Valid when I2CG0C[1]=1 (new clock divider mode). Defines four base clock divisors used by per-channel I2CC04[3:0] selection. Divisor value N: effective divisor = N/2 + 0.5 (0x00=÷1, 0x01=÷1.5, ..., 0xFF=÷128.5).
func (p *I2cglobalV1I2CGLOBAL) WriteCLKDIV(val uint32) {
    reg.Write(uint32(p.Base)+0x0010, uint32(val))
}

