// Code generated by chiptool; DO NOT EDIT.

package pac

import "github.com/kyanitecomputer/aspeed-go/reg"

// I3cV1I3C DWC I3C per-channel registers (AST1060, 4 instances). Base: 0x7E7A_2000 + N*0x1000 for instance N (0-3).
type I3cV1I3C struct {
    Base uintptr
}

// ReadDEVICECTRL reads Device control register. Enable/disable master and slave functions, abort transfers, configure DMA, IBI, and addressing policies.
func (p *I3cV1I3C) ReadDEVICECTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0000))
}

// WriteDEVICECTRL writes Device control register. Enable/disable master and slave functions, abort transfers, configure DMA, IBI, and addressing policies.
func (p *I3cV1I3C) WriteDEVICECTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x0000, uint32(val))
}

// ReadDEVICEADDR reads Device address register. Holds dynamic address (assigned by master or self-assigned for main master) and static address (slave mode).
func (p *I3cV1I3C) ReadDEVICEADDR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0004))
}

// WriteDEVICEADDR writes Device address register. Holds dynamic address (assigned by master or self-assigned for main master) and static address (slave mode).
func (p *I3cV1I3C) WriteDEVICEADDR(val uint32) {
    reg.Write(uint32(p.Base)+0x0004, uint32(val))
}

// ReadHWCAPABILITY reads Hardware capability register (read-only). Reflects IP configuration: supported roles, HDR modes, DMA presence, clock parameters.
func (p *I3cV1I3C) ReadHWCAPABILITY() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0008))
}

// WriteHWCAPABILITY writes Hardware capability register (read-only). Reflects IP configuration: supported roles, HDR modes, DMA presence, clock parameters.
func (p *I3cV1I3C) WriteHWCAPABILITY(val uint32) {
    reg.Write(uint32(p.Base)+0x0008, uint32(val))
}

// ReadCMDQUEUEPORT reads Command queue port (write-only). Push 32-bit command descriptors. Four formats: TC (Transfer Command, attr=0), TARG (Transfer Argument, attr=1), SDA (Short Data Argument, attr=2), AAC (Address Assignment, attr=3). CMD_ATTR in bits[2:0] selects format.
func (p *I3cV1I3C) ReadCMDQUEUEPORT() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x000c))
}

// WriteCMDQUEUEPORT writes Command queue port (write-only). Push 32-bit command descriptors. Four formats: TC (Transfer Command, attr=0), TARG (Transfer Argument, attr=1), SDA (Short Data Argument, attr=2), AAC (Address Assignment, attr=3). CMD_ATTR in bits[2:0] selects format.
func (p *I3cV1I3C) WriteCMDQUEUEPORT(val uint32) {
    reg.Write(uint32(p.Base)+0x000c, uint32(val))
}

// ReadRESPQUEUEPORT reads Response queue port (read-only). Pop response entries after transfer. Contains error status, TID, CCC type, and data length.
func (p *I3cV1I3C) ReadRESPQUEUEPORT() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0010))
}

// WriteRESPQUEUEPORT writes Response queue port (read-only). Pop response entries after transfer. Contains error status, TID, CCC type, and data length.
func (p *I3cV1I3C) WriteRESPQUEUEPORT(val uint32) {
    reg.Write(uint32(p.Base)+0x0010, uint32(val))
}

// ReadTXRXDATAPORT reads TX/RX data port. Write = push TX FIFO; read = pop RX FIFO. Data must be 4-byte aligned; extra bytes at end of non-aligned transfers are padding (TX) or ignored (RX).
func (p *I3cV1I3C) ReadTXRXDATAPORT() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0014))
}

// WriteTXRXDATAPORT writes TX/RX data port. Write = push TX FIFO; read = pop RX FIFO. Data must be 4-byte aligned; extra bytes at end of non-aligned transfers are padding (TX) or ignored (RX).
func (p *I3cV1I3C) WriteTXRXDATAPORT(val uint32) {
    reg.Write(uint32(p.Base)+0x0014, uint32(val))
}

// ReadIBIQUEUESTATUS reads IBI queue (read-only). On read, returns either IBI status word (IBI_ID, DATA_LEN, ACK/NACK, LAST_STATUS) or IBI payload data. Context determined by bit[24] (LAST_STATUS) of the status entry.
func (p *I3cV1I3C) ReadIBIQUEUESTATUS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0018))
}

// WriteIBIQUEUESTATUS writes IBI queue (read-only). On read, returns either IBI status word (IBI_ID, DATA_LEN, ACK/NACK, LAST_STATUS) or IBI payload data. Context determined by bit[24] (LAST_STATUS) of the status entry.
func (p *I3cV1I3C) WriteIBIQUEUESTATUS(val uint32) {
    reg.Write(uint32(p.Base)+0x0018, uint32(val))
}

// ReadQUEUETHLDCTRL reads Queue threshold control. Sets watermarks for command queue empty, response queue ready, IBI status, and IBI data segment thresholds.
func (p *I3cV1I3C) ReadQUEUETHLDCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x001c))
}

// WriteQUEUETHLDCTRL writes Queue threshold control. Sets watermarks for command queue empty, response queue ready, IBI status, and IBI data segment thresholds.
func (p *I3cV1I3C) WriteQUEUETHLDCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x001c, uint32(val))
}

// ReadDATABUFTHLDCTRL reads Data buffer threshold control. Sets TX/RX FIFO watermarks that trigger TX_THLD_STAT and RX_THLD_STAT interrupts, and minimum fill levels before starting transfers.
func (p *I3cV1I3C) ReadDATABUFTHLDCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0020))
}

// WriteDATABUFTHLDCTRL writes Data buffer threshold control. Sets TX/RX FIFO watermarks that trigger TX_THLD_STAT and RX_THLD_STAT interrupts, and minimum fill levels before starting transfers.
func (p *I3cV1I3C) WriteDATABUFTHLDCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x0020, uint32(val))
}

// ReadIBIQUEUECTRL reads IBI queue notification control. When NOTIFY_*_REJECTED=1, NACKed Hot-Join/MR/SIR events are forwarded to the IBI FIFO with error flag.
func (p *I3cV1I3C) ReadIBIQUEUECTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0024))
}

// WriteIBIQUEUECTRL writes IBI queue notification control. When NOTIFY_*_REJECTED=1, NACKed Hot-Join/MR/SIR events are forwarded to the IBI FIFO with error flag.
func (p *I3cV1I3C) WriteIBIQUEUECTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x0024, uint32(val))
}

// ReadIBIMRREQREJECT reads Per-device Master Request rejection bitmap (master only). Bit N=1: NACK MR from device N and send directed DISEC CCC.
func (p *I3cV1I3C) ReadIBIMRREQREJECT() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x002c))
}

// WriteIBIMRREQREJECT writes Per-device Master Request rejection bitmap (master only). Bit N=1: NACK MR from device N and send directed DISEC CCC.
func (p *I3cV1I3C) WriteIBIMRREQREJECT(val uint32) {
    reg.Write(uint32(p.Base)+0x002c, uint32(val))
}

// ReadIBISIRREQREJECT reads Per-device Slave Interrupt Request rejection bitmap (master only). Bit N=1: NACK SIR from device N and send directed auto-disable DISEC.
func (p *I3cV1I3C) ReadIBISIRREQREJECT() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0030))
}

// WriteIBISIRREQREJECT writes Per-device Slave Interrupt Request rejection bitmap (master only). Bit N=1: NACK SIR from device N and send directed auto-disable DISEC.
func (p *I3cV1I3C) WriteIBISIRREQREJECT(val uint32) {
    reg.Write(uint32(p.Base)+0x0030, uint32(val))
}

// ReadRESETCTRL reads Software reset control. Write 1 to each bit to reset the named resource; bits auto-clear after reset completes (volatile).
func (p *I3cV1I3C) ReadRESETCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0034))
}

// WriteRESETCTRL writes Software reset control. Write 1 to each bit to reset the named resource; bits auto-clear after reset completes (volatile).
func (p *I3cV1I3C) WriteRESETCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x0034, uint32(val))
}

// ReadSLVEVENTCTRL reads Slave event control and status. Reports MWL/MRL updates from master CCC, current activity state, and enabled IBI event types.
func (p *I3cV1I3C) ReadSLVEVENTCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0038))
}

// WriteSLVEVENTCTRL writes Slave event control and status. Reports MWL/MRL updates from master CCC, current activity state, and enabled IBI event types.
func (p *I3cV1I3C) WriteSLVEVENTCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x0038, uint32(val))
}

// ReadINTRSTATUS reads Interrupt status. Sticky (RW1C) bits for error/event interrupts; level bits auto-clear when the condition clears (FIFO thresholds).
func (p *I3cV1I3C) ReadINTRSTATUS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x003c))
}

// WriteINTRSTATUS writes Interrupt status. Sticky (RW1C) bits for error/event interrupts; level bits auto-clear when the condition clears (FIFO thresholds).
func (p *I3cV1I3C) WriteINTRSTATUS(val uint32) {
    reg.Write(uint32(p.Base)+0x003c, uint32(val))
}

// ReadINTRSTATUSEN reads Interrupt status enable mask (same bit layout as INTR_STATUS).
func (p *I3cV1I3C) ReadINTRSTATUSEN() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0040))
}

// WriteINTRSTATUSEN writes Interrupt status enable mask (same bit layout as INTR_STATUS).
func (p *I3cV1I3C) WriteINTRSTATUSEN(val uint32) {
    reg.Write(uint32(p.Base)+0x0040, uint32(val))
}

// ReadINTRSIGNALEN reads Interrupt signal (IRQ pin) enable mask (same bit layout as INTR_STATUS). Each bit gates whether the corresponding status bit drives the IRQ pin.
func (p *I3cV1I3C) ReadINTRSIGNALEN() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0044))
}

// WriteINTRSIGNALEN writes Interrupt signal (IRQ pin) enable mask (same bit layout as INTR_STATUS). Each bit gates whether the corresponding status bit drives the IRQ pin.
func (p *I3cV1I3C) WriteINTRSIGNALEN(val uint32) {
    reg.Write(uint32(p.Base)+0x0044, uint32(val))
}

// ReadINTRFORCE reads Interrupt force register (write-only). Write 1 to force-set the corresponding INTR_STATUS bit (for testing).
func (p *I3cV1I3C) ReadINTRFORCE() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0048))
}

// WriteINTRFORCE writes Interrupt force register (write-only). Write 1 to force-set the corresponding INTR_STATUS bit (for testing).
func (p *I3cV1I3C) WriteINTRFORCE(val uint32) {
    reg.Write(uint32(p.Base)+0x0048, uint32(val))
}

// ReadQUEUESTATUSLEVEL reads Current queue occupancy (read-only).
func (p *I3cV1I3C) ReadQUEUESTATUSLEVEL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x004c))
}

// WriteQUEUESTATUSLEVEL writes Current queue occupancy (read-only).
func (p *I3cV1I3C) WriteQUEUESTATUSLEVEL(val uint32) {
    reg.Write(uint32(p.Base)+0x004c, uint32(val))
}

// ReadDATABUFSTATUSLEVEL reads Current FIFO occupancy (read-only).
func (p *I3cV1I3C) ReadDATABUFSTATUSLEVEL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0050))
}

// WriteDATABUFSTATUSLEVEL writes Current FIFO occupancy (read-only).
func (p *I3cV1I3C) WriteDATABUFSTATUSLEVEL(val uint32) {
    reg.Write(uint32(p.Base)+0x0050, uint32(val))
}

// ReadPRESENTSTATE reads Current controller state (read-only). Shows whether this controller is the current bus master, SCL/SDA line levels, transfer FSM state, current TID, and master idle status.
func (p *I3cV1I3C) ReadPRESENTSTATE() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0054))
}

// WritePRESENTSTATE writes Current controller state (read-only). Shows whether this controller is the current bus master, SCL/SDA line levels, transfer FSM state, current TID, and master idle status.
func (p *I3cV1I3C) WritePRESENTSTATE(val uint32) {
    reg.Write(uint32(p.Base)+0x0054, uint32(val))
}

// ReadDEVOPERATINGSTATUS reads Device operating status (slave mode, read-only). Reports error conditions (frame error, buffer not available, data not ready, overflow) and current activity mode.
func (p *I3cV1I3C) ReadDEVOPERATINGSTATUS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0058))
}

// WriteDEVOPERATINGSTATUS writes Device operating status (slave mode, read-only). Reports error conditions (frame error, buffer not available, data not ready, overflow) and current activity mode.
func (p *I3cV1I3C) WriteDEVOPERATINGSTATUS(val uint32) {
    reg.Write(uint32(p.Base)+0x0058, uint32(val))
}

// ReadDEVADDRTABLEPTR reads Device Address Table (DAT) pointer (read-only).
func (p *I3cV1I3C) ReadDEVADDRTABLEPTR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x005c))
}

// WriteDEVADDRTABLEPTR writes Device Address Table (DAT) pointer (read-only).
func (p *I3cV1I3C) WriteDEVADDRTABLEPTR(val uint32) {
    reg.Write(uint32(p.Base)+0x005c, uint32(val))
}

// ReadDEVCHARTABLEPTR reads Device Characteristic Table (DCT) pointer and write index.
func (p *I3cV1I3C) ReadDEVCHARTABLEPTR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0060))
}

// WriteDEVCHARTABLEPTR writes Device Characteristic Table (DCT) pointer and write index.
func (p *I3cV1I3C) WriteDEVCHARTABLEPTR(val uint32) {
    reg.Write(uint32(p.Base)+0x0060, uint32(val))
}

// ReadSLVMIPIPIDHI reads Slave Provisional ID high word: MFG ID [47:33] + type selector [32].
func (p *I3cV1I3C) ReadSLVMIPIPIDHI() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0070))
}

// WriteSLVMIPIPIDHI writes Slave Provisional ID high word: MFG ID [47:33] + type selector [32].
func (p *I3cV1I3C) WriteSLVMIPIPIDHI(val uint32) {
    reg.Write(uint32(p.Base)+0x0070, uint32(val))
}

// ReadSLVPIDLO reads Slave Provisional ID low word: part ID [31:16], instance ID [15:12], extra [11:0].
func (p *I3cV1I3C) ReadSLVPIDLO() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0074))
}

// WriteSLVPIDLO writes Slave Provisional ID low word: part ID [31:16], instance ID [15:12], extra [11:0].
func (p *I3cV1I3C) WriteSLVPIDLO(val uint32) {
    reg.Write(uint32(p.Base)+0x0074, uint32(val))
}

// ReadSLVCHARCTRL reads Slave characteristic control (read-only). BCR, DCR, HDR capability.
func (p *I3cV1I3C) ReadSLVCHARCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0078))
}

// WriteSLVCHARCTRL writes Slave characteristic control (read-only). BCR, DCR, HDR capability.
func (p *I3cV1I3C) WriteSLVCHARCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x0078, uint32(val))
}

// ReadSLVMAXLEN reads Slave max read/write length (set by master via SETMRL/SETMWL CCC).
func (p *I3cV1I3C) ReadSLVMAXLEN() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x007c))
}

// WriteSLVMAXLEN writes Slave max read/write length (set by master via SETMRL/SETMWL CCC).
func (p *I3cV1I3C) WriteSLVMAXLEN(val uint32) {
    reg.Write(uint32(p.Base)+0x007c, uint32(val))
}

// ReadMAXREADTURNAROUND reads MXDS max read turnaround time in microseconds (read-only, reflects input port).
func (p *I3cV1I3C) ReadMAXREADTURNAROUND() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0080))
}

// WriteMAXREADTURNAROUND writes MXDS max read turnaround time in microseconds (read-only, reflects input port).
func (p *I3cV1I3C) WriteMAXREADTURNAROUND(val uint32) {
    reg.Write(uint32(p.Base)+0x0080, uint32(val))
}

// ReadMAXDATASPEED reads MXDS maximum data speed — Tsco, max read/write speeds.
func (p *I3cV1I3C) ReadMAXDATASPEED() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0084))
}

// WriteMAXDATASPEED writes MXDS maximum data speed — Tsco, max read/write speeds.
func (p *I3cV1I3C) WriteMAXDATASPEED(val uint32) {
    reg.Write(uint32(p.Base)+0x0084, uint32(val))
}

// ReadSLVINTRREQ reads Slave interrupt request (slave mode only). Write SIR=1 to initiate Slave Interrupt Request IBI. MIR=1 for secondary master request. IBI_STS reads completion status.
func (p *I3cV1I3C) ReadSLVINTRREQ() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x008c))
}

// WriteSLVINTRREQ writes Slave interrupt request (slave mode only). Write SIR=1 to initiate Slave Interrupt Request IBI. MIR=1 for secondary master request. IBI_STS reads completion status.
func (p *I3cV1I3C) WriteSLVINTRREQ(val uint32) {
    reg.Write(uint32(p.Base)+0x008c, uint32(val))
}

// ReadSLVTSXSYMBLTIMING reads TSP/TSL symbol timing. Symbol duration = count × hdr_tx_clk_period.
func (p *I3cV1I3C) ReadSLVTSXSYMBLTIMING() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0090))
}

// WriteSLVTSXSYMBLTIMING writes TSP/TSL symbol timing. Symbol duration = count × hdr_tx_clk_period.
func (p *I3cV1I3C) WriteSLVTSXSYMBLTIMING(val uint32) {
    reg.Write(uint32(p.Base)+0x0090, uint32(val))
}

// ReadDEVICECTRLEXT reads Extended device control. Sets operation mode (master/slave) and REQMST ACK policy.
func (p *I3cV1I3C) ReadDEVICECTRLEXT() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00b0))
}

// WriteDEVICECTRLEXT writes Extended device control. Sets operation mode (master/slave) and REQMST ACK policy.
func (p *I3cV1I3C) WriteDEVICECTRLEXT(val uint32) {
    reg.Write(uint32(p.Base)+0x00b0, uint32(val))
}

// ReadSCLI3CODTIMING reads SCL open-drain timing for I3C transfers. Sets high/low period counts.
func (p *I3cV1I3C) ReadSCLI3CODTIMING() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00b4))
}

// WriteSCLI3CODTIMING writes SCL open-drain timing for I3C transfers. Sets high/low period counts.
func (p *I3cV1I3C) WriteSCLI3CODTIMING(val uint32) {
    reg.Write(uint32(p.Base)+0x00b4, uint32(val))
}

// ReadSCLI3CPPTIMING reads SCL push-pull timing for I3C transfers.
func (p *I3cV1I3C) ReadSCLI3CPPTIMING() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00b8))
}

// WriteSCLI3CPPTIMING writes SCL push-pull timing for I3C transfers.
func (p *I3cV1I3C) WriteSCLI3CPPTIMING(val uint32) {
    reg.Write(uint32(p.Base)+0x00b8, uint32(val))
}

// ReadSCLI2CFMTIMING reads SCL timing for I2C Fast Mode (400 kHz) transfers.
func (p *I3cV1I3C) ReadSCLI2CFMTIMING() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00bc))
}

// WriteSCLI2CFMTIMING writes SCL timing for I2C Fast Mode (400 kHz) transfers.
func (p *I3cV1I3C) WriteSCLI2CFMTIMING(val uint32) {
    reg.Write(uint32(p.Base)+0x00bc, uint32(val))
}

// ReadSCLI2CFMPTIMING reads SCL timing for I2C Fast Mode Plus (1 MHz) transfers.
func (p *I3cV1I3C) ReadSCLI2CFMPTIMING() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00c0))
}

// WriteSCLI2CFMPTIMING writes SCL timing for I2C Fast Mode Plus (1 MHz) transfers.
func (p *I3cV1I3C) WriteSCLI2CFMPTIMING(val uint32) {
    reg.Write(uint32(p.Base)+0x00c0, uint32(val))
}

// ReadSCLEXTLCNTTIMING reads Extended SCL low count for SDR1-SDR4 speeds (one 8-bit field per speed).
func (p *I3cV1I3C) ReadSCLEXTLCNTTIMING() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00c8))
}

// WriteSCLEXTLCNTTIMING writes Extended SCL low count for SDR1-SDR4 speeds (one 8-bit field per speed).
func (p *I3cV1I3C) WriteSCLEXTLCNTTIMING(val uint32) {
    reg.Write(uint32(p.Base)+0x00c8, uint32(val))
}

// ReadSCLEXTTERMNLCNT reads HDR-TS skew count and read termination bit low count.
func (p *I3cV1I3C) ReadSCLEXTTERMNLCNT() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00cc))
}

// WriteSCLEXTTERMNLCNT writes HDR-TS skew count and read termination bit low count.
func (p *I3cV1I3C) WriteSCLEXTTERMNLCNT(val uint32) {
    reg.Write(uint32(p.Base)+0x00cc, uint32(val))
}

// ReadSDAHOLDSWDLY reads SDA transmit hold time and PP↔OD switching delays.
func (p *I3cV1I3C) ReadSDAHOLDSWDLY() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00d0))
}

// WriteSDAHOLDSWDLY writes SDA transmit hold time and PP↔OD switching delays.
func (p *I3cV1I3C) WriteSDAHOLDSWDLY(val uint32) {
    reg.Write(uint32(p.Base)+0x00d0, uint32(val))
}

// ReadBUSFREETIMING reads Bus free timing for IBI initiation (slave) and inter-transfer gap (master).
func (p *I3cV1I3C) ReadBUSFREETIMING() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00d4))
}

// WriteBUSFREETIMING writes Bus free timing for IBI initiation (slave) and inter-transfer gap (master).
func (p *I3cV1I3C) WriteBUSFREETIMING(val uint32) {
    reg.Write(uint32(p.Base)+0x00d4, uint32(val))
}

// ReadBUSIDLETIMING reads Bus idle count before Hot-Join initiation (slave/non-current-master).
func (p *I3cV1I3C) ReadBUSIDLETIMING() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00d8))
}

// WriteBUSIDLETIMING writes Bus idle count before Hot-Join initiation (slave/non-current-master).
func (p *I3cV1I3C) WriteBUSIDLETIMING(val uint32) {
    reg.Write(uint32(p.Base)+0x00d8, uint32(val))
}

// ReadSCLLOWMSTEXTTIMEOUT reads Core clock count for SCL Low Bus Reset pattern generation (master).
func (p *I3cV1I3C) ReadSCLLOWMSTEXTTIMEOUT() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00dc))
}

// WriteSCLLOWMSTEXTTIMEOUT writes Core clock count for SCL Low Bus Reset pattern generation (master).
func (p *I3cV1I3C) WriteSCLLOWMSTEXTTIMEOUT(val uint32) {
    reg.Write(uint32(p.Base)+0x00dc, uint32(val))
}

// ReadVERID reads DWC I3C version ID in ASCII (read-only).
func (p *I3cV1I3C) ReadVERID() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00e0))
}

// WriteVERID writes DWC I3C version ID in ASCII (read-only).
func (p *I3cV1I3C) WriteVERID(val uint32) {
    reg.Write(uint32(p.Base)+0x00e0, uint32(val))
}

// ReadVERTYPE reads DWC I3C version type in ASCII (read-only).
func (p *I3cV1I3C) ReadVERTYPE() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00e4))
}

// WriteVERTYPE writes DWC I3C version type in ASCII (read-only).
func (p *I3cV1I3C) WriteVERTYPE(val uint32) {
    reg.Write(uint32(p.Base)+0x00e4, uint32(val))
}

// ReadQUEUESIZECAP reads Queue and FIFO depth capability (read-only, reflects IP configuration).
func (p *I3cV1I3C) ReadQUEUESIZECAP() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00e8))
}

// WriteQUEUESIZECAP writes Queue and FIFO depth capability (read-only, reflects IP configuration).
func (p *I3cV1I3C) WriteQUEUESIZECAP(val uint32) {
    reg.Write(uint32(p.Base)+0x00e8, uint32(val))
}

// ReadIBIPAYLOADLEN reads IBI payload length — slave configurable size + hardware max size.
func (p *I3cV1I3C) ReadIBIPAYLOADLEN() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00ec))
}

// WriteIBIPAYLOADLEN writes IBI payload length — slave configurable size + hardware max size.
func (p *I3cV1I3C) WriteIBIPAYLOADLEN(val uint32) {
    reg.Write(uint32(p.Base)+0x00ec, uint32(val))
}

// ReadDCTDEV1LOC1 reads DCT device 1 location 1 — Provisional ID bits [31:0].
func (p *I3cV1I3C) ReadDCTDEV1LOC1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0200))
}

// WriteDCTDEV1LOC1 writes DCT device 1 location 1 — Provisional ID bits [31:0].
func (p *I3cV1I3C) WriteDCTDEV1LOC1(val uint32) {
    reg.Write(uint32(p.Base)+0x0200, uint32(val))
}

// ReadDCTDEV1LOC2 reads DCT device 1 location 2 — Provisional ID bits [47:32].
func (p *I3cV1I3C) ReadDCTDEV1LOC2() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0204))
}

// WriteDCTDEV1LOC2 writes DCT device 1 location 2 — Provisional ID bits [47:32].
func (p *I3cV1I3C) WriteDCTDEV1LOC2(val uint32) {
    reg.Write(uint32(p.Base)+0x0204, uint32(val))
}

// ReadDCTDEV1LOC3 reads DCT device 1 location 3 — BCR and DCR.
func (p *I3cV1I3C) ReadDCTDEV1LOC3() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0208))
}

// WriteDCTDEV1LOC3 writes DCT device 1 location 3 — BCR and DCR.
func (p *I3cV1I3C) WriteDCTDEV1LOC3(val uint32) {
    reg.Write(uint32(p.Base)+0x0208, uint32(val))
}

// ReadDCTDEV1LOC4 reads DCT device 1 location 4 — assigned dynamic address.
func (p *I3cV1I3C) ReadDCTDEV1LOC4() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x020c))
}

// WriteDCTDEV1LOC4 writes DCT device 1 location 4 — assigned dynamic address.
func (p *I3cV1I3C) WriteDCTDEV1LOC4(val uint32) {
    reg.Write(uint32(p.Base)+0x020c, uint32(val))
}

// ReadDCTDEV2LOC1 reads DCT device 2 PID[31:0].
func (p *I3cV1I3C) ReadDCTDEV2LOC1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0210))
}

// WriteDCTDEV2LOC1 writes DCT device 2 PID[31:0].
func (p *I3cV1I3C) WriteDCTDEV2LOC1(val uint32) {
    reg.Write(uint32(p.Base)+0x0210, uint32(val))
}

// ReadDCTDEV2LOC2 reads DCT device 2 PID[47:32].
func (p *I3cV1I3C) ReadDCTDEV2LOC2() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0214))
}

// WriteDCTDEV2LOC2 writes DCT device 2 PID[47:32].
func (p *I3cV1I3C) WriteDCTDEV2LOC2(val uint32) {
    reg.Write(uint32(p.Base)+0x0214, uint32(val))
}

// ReadDCTDEV2LOC3 reads DCT device 2 BCR+DCR.
func (p *I3cV1I3C) ReadDCTDEV2LOC3() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0218))
}

// WriteDCTDEV2LOC3 writes DCT device 2 BCR+DCR.
func (p *I3cV1I3C) WriteDCTDEV2LOC3(val uint32) {
    reg.Write(uint32(p.Base)+0x0218, uint32(val))
}

// ReadDCTDEV2LOC4 reads DCT device 2 dynamic address.
func (p *I3cV1I3C) ReadDCTDEV2LOC4() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x021c))
}

// WriteDCTDEV2LOC4 writes DCT device 2 dynamic address.
func (p *I3cV1I3C) WriteDCTDEV2LOC4(val uint32) {
    reg.Write(uint32(p.Base)+0x021c, uint32(val))
}

// ReadDCTDEV3LOC1 reads DCT device 3 PID[31:0].
func (p *I3cV1I3C) ReadDCTDEV3LOC1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0220))
}

// WriteDCTDEV3LOC1 writes DCT device 3 PID[31:0].
func (p *I3cV1I3C) WriteDCTDEV3LOC1(val uint32) {
    reg.Write(uint32(p.Base)+0x0220, uint32(val))
}

// ReadDCTDEV3LOC2 reads DCT device 3 PID[47:32].
func (p *I3cV1I3C) ReadDCTDEV3LOC2() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0224))
}

// WriteDCTDEV3LOC2 writes DCT device 3 PID[47:32].
func (p *I3cV1I3C) WriteDCTDEV3LOC2(val uint32) {
    reg.Write(uint32(p.Base)+0x0224, uint32(val))
}

// ReadDCTDEV3LOC3 reads DCT device 3 BCR+DCR.
func (p *I3cV1I3C) ReadDCTDEV3LOC3() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0228))
}

// WriteDCTDEV3LOC3 writes DCT device 3 BCR+DCR.
func (p *I3cV1I3C) WriteDCTDEV3LOC3(val uint32) {
    reg.Write(uint32(p.Base)+0x0228, uint32(val))
}

// ReadDCTDEV3LOC4 reads DCT device 3 dynamic address.
func (p *I3cV1I3C) ReadDCTDEV3LOC4() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x022c))
}

// WriteDCTDEV3LOC4 writes DCT device 3 dynamic address.
func (p *I3cV1I3C) WriteDCTDEV3LOC4(val uint32) {
    reg.Write(uint32(p.Base)+0x022c, uint32(val))
}

// ReadDCTDEV4LOC1 reads DCT device 4 PID[31:0].
func (p *I3cV1I3C) ReadDCTDEV4LOC1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0230))
}

// WriteDCTDEV4LOC1 writes DCT device 4 PID[31:0].
func (p *I3cV1I3C) WriteDCTDEV4LOC1(val uint32) {
    reg.Write(uint32(p.Base)+0x0230, uint32(val))
}

// ReadDCTDEV4LOC2 reads DCT device 4 PID[47:32].
func (p *I3cV1I3C) ReadDCTDEV4LOC2() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0234))
}

// WriteDCTDEV4LOC2 writes DCT device 4 PID[47:32].
func (p *I3cV1I3C) WriteDCTDEV4LOC2(val uint32) {
    reg.Write(uint32(p.Base)+0x0234, uint32(val))
}

// ReadDCTDEV4LOC3 reads DCT device 4 BCR+DCR.
func (p *I3cV1I3C) ReadDCTDEV4LOC3() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0238))
}

// WriteDCTDEV4LOC3 writes DCT device 4 BCR+DCR.
func (p *I3cV1I3C) WriteDCTDEV4LOC3(val uint32) {
    reg.Write(uint32(p.Base)+0x0238, uint32(val))
}

// ReadDCTDEV4LOC4 reads DCT device 4 dynamic address.
func (p *I3cV1I3C) ReadDCTDEV4LOC4() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x023c))
}

// WriteDCTDEV4LOC4 writes DCT device 4 dynamic address.
func (p *I3cV1I3C) WriteDCTDEV4LOC4(val uint32) {
    reg.Write(uint32(p.Base)+0x023c, uint32(val))
}

// ReadDCTDEV5LOC1 reads DCT device 5 PID[31:0].
func (p *I3cV1I3C) ReadDCTDEV5LOC1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0240))
}

// WriteDCTDEV5LOC1 writes DCT device 5 PID[31:0].
func (p *I3cV1I3C) WriteDCTDEV5LOC1(val uint32) {
    reg.Write(uint32(p.Base)+0x0240, uint32(val))
}

// ReadDCTDEV5LOC2 reads DCT device 5 PID[47:32].
func (p *I3cV1I3C) ReadDCTDEV5LOC2() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0244))
}

// WriteDCTDEV5LOC2 writes DCT device 5 PID[47:32].
func (p *I3cV1I3C) WriteDCTDEV5LOC2(val uint32) {
    reg.Write(uint32(p.Base)+0x0244, uint32(val))
}

// ReadDCTDEV5LOC3 reads DCT device 5 BCR+DCR.
func (p *I3cV1I3C) ReadDCTDEV5LOC3() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0248))
}

// WriteDCTDEV5LOC3 writes DCT device 5 BCR+DCR.
func (p *I3cV1I3C) WriteDCTDEV5LOC3(val uint32) {
    reg.Write(uint32(p.Base)+0x0248, uint32(val))
}

// ReadDCTDEV5LOC4 reads DCT device 5 dynamic address.
func (p *I3cV1I3C) ReadDCTDEV5LOC4() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x024c))
}

// WriteDCTDEV5LOC4 writes DCT device 5 dynamic address.
func (p *I3cV1I3C) WriteDCTDEV5LOC4(val uint32) {
    reg.Write(uint32(p.Base)+0x024c, uint32(val))
}

// ReadDCTDEV6LOC1 reads DCT device 6 PID[31:0].
func (p *I3cV1I3C) ReadDCTDEV6LOC1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0250))
}

// WriteDCTDEV6LOC1 writes DCT device 6 PID[31:0].
func (p *I3cV1I3C) WriteDCTDEV6LOC1(val uint32) {
    reg.Write(uint32(p.Base)+0x0250, uint32(val))
}

// ReadDCTDEV6LOC2 reads DCT device 6 PID[47:32].
func (p *I3cV1I3C) ReadDCTDEV6LOC2() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0254))
}

// WriteDCTDEV6LOC2 writes DCT device 6 PID[47:32].
func (p *I3cV1I3C) WriteDCTDEV6LOC2(val uint32) {
    reg.Write(uint32(p.Base)+0x0254, uint32(val))
}

// ReadDCTDEV6LOC3 reads DCT device 6 BCR+DCR.
func (p *I3cV1I3C) ReadDCTDEV6LOC3() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0258))
}

// WriteDCTDEV6LOC3 writes DCT device 6 BCR+DCR.
func (p *I3cV1I3C) WriteDCTDEV6LOC3(val uint32) {
    reg.Write(uint32(p.Base)+0x0258, uint32(val))
}

// ReadDCTDEV6LOC4 reads DCT device 6 dynamic address.
func (p *I3cV1I3C) ReadDCTDEV6LOC4() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x025c))
}

// WriteDCTDEV6LOC4 writes DCT device 6 dynamic address.
func (p *I3cV1I3C) WriteDCTDEV6LOC4(val uint32) {
    reg.Write(uint32(p.Base)+0x025c, uint32(val))
}

// ReadDCTDEV7LOC1 reads DCT device 7 PID[31:0].
func (p *I3cV1I3C) ReadDCTDEV7LOC1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0260))
}

// WriteDCTDEV7LOC1 writes DCT device 7 PID[31:0].
func (p *I3cV1I3C) WriteDCTDEV7LOC1(val uint32) {
    reg.Write(uint32(p.Base)+0x0260, uint32(val))
}

// ReadDCTDEV7LOC2 reads DCT device 7 PID[47:32].
func (p *I3cV1I3C) ReadDCTDEV7LOC2() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0264))
}

// WriteDCTDEV7LOC2 writes DCT device 7 PID[47:32].
func (p *I3cV1I3C) WriteDCTDEV7LOC2(val uint32) {
    reg.Write(uint32(p.Base)+0x0264, uint32(val))
}

// ReadDCTDEV7LOC3 reads DCT device 7 BCR+DCR.
func (p *I3cV1I3C) ReadDCTDEV7LOC3() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0268))
}

// WriteDCTDEV7LOC3 writes DCT device 7 BCR+DCR.
func (p *I3cV1I3C) WriteDCTDEV7LOC3(val uint32) {
    reg.Write(uint32(p.Base)+0x0268, uint32(val))
}

// ReadDCTDEV7LOC4 reads DCT device 7 dynamic address.
func (p *I3cV1I3C) ReadDCTDEV7LOC4() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x026c))
}

// WriteDCTDEV7LOC4 writes DCT device 7 dynamic address.
func (p *I3cV1I3C) WriteDCTDEV7LOC4(val uint32) {
    reg.Write(uint32(p.Base)+0x026c, uint32(val))
}

// ReadDCTDEV8LOC1 reads DCT device 8 PID[31:0].
func (p *I3cV1I3C) ReadDCTDEV8LOC1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0270))
}

// WriteDCTDEV8LOC1 writes DCT device 8 PID[31:0].
func (p *I3cV1I3C) WriteDCTDEV8LOC1(val uint32) {
    reg.Write(uint32(p.Base)+0x0270, uint32(val))
}

// ReadDCTDEV8LOC2 reads DCT device 8 PID[47:32].
func (p *I3cV1I3C) ReadDCTDEV8LOC2() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0274))
}

// WriteDCTDEV8LOC2 writes DCT device 8 PID[47:32].
func (p *I3cV1I3C) WriteDCTDEV8LOC2(val uint32) {
    reg.Write(uint32(p.Base)+0x0274, uint32(val))
}

// ReadDCTDEV8LOC3 reads DCT device 8 BCR+DCR.
func (p *I3cV1I3C) ReadDCTDEV8LOC3() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0278))
}

// WriteDCTDEV8LOC3 writes DCT device 8 BCR+DCR.
func (p *I3cV1I3C) WriteDCTDEV8LOC3(val uint32) {
    reg.Write(uint32(p.Base)+0x0278, uint32(val))
}

// ReadDCTDEV8LOC4 reads DCT device 8 dynamic address.
func (p *I3cV1I3C) ReadDCTDEV8LOC4() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x027c))
}

// WriteDCTDEV8LOC4 writes DCT device 8 dynamic address.
func (p *I3cV1I3C) WriteDCTDEV8LOC4(val uint32) {
    reg.Write(uint32(p.Base)+0x027c, uint32(val))
}

// ReadDATDEV1 reads DAT entry for device 1. Address, IBI policy, retry count.
func (p *I3cV1I3C) ReadDATDEV1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0280))
}

// WriteDATDEV1 writes DAT entry for device 1. Address, IBI policy, retry count.
func (p *I3cV1I3C) WriteDATDEV1(val uint32) {
    reg.Write(uint32(p.Base)+0x0280, uint32(val))
}

// ReadDATDEV2 reads DAT entry for device 2.
func (p *I3cV1I3C) ReadDATDEV2() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0284))
}

// WriteDATDEV2 writes DAT entry for device 2.
func (p *I3cV1I3C) WriteDATDEV2(val uint32) {
    reg.Write(uint32(p.Base)+0x0284, uint32(val))
}

// ReadDATDEV3 reads DAT entry for device 3.
func (p *I3cV1I3C) ReadDATDEV3() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0288))
}

// WriteDATDEV3 writes DAT entry for device 3.
func (p *I3cV1I3C) WriteDATDEV3(val uint32) {
    reg.Write(uint32(p.Base)+0x0288, uint32(val))
}

// ReadDATDEV4 reads DAT entry for device 4.
func (p *I3cV1I3C) ReadDATDEV4() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x028c))
}

// WriteDATDEV4 writes DAT entry for device 4.
func (p *I3cV1I3C) WriteDATDEV4(val uint32) {
    reg.Write(uint32(p.Base)+0x028c, uint32(val))
}

// ReadDATDEV5 reads DAT entry for device 5.
func (p *I3cV1I3C) ReadDATDEV5() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0290))
}

// WriteDATDEV5 writes DAT entry for device 5.
func (p *I3cV1I3C) WriteDATDEV5(val uint32) {
    reg.Write(uint32(p.Base)+0x0290, uint32(val))
}

// ReadDATDEV6 reads DAT entry for device 6.
func (p *I3cV1I3C) ReadDATDEV6() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0294))
}

// WriteDATDEV6 writes DAT entry for device 6.
func (p *I3cV1I3C) WriteDATDEV6(val uint32) {
    reg.Write(uint32(p.Base)+0x0294, uint32(val))
}

// ReadDATDEV7 reads DAT entry for device 7.
func (p *I3cV1I3C) ReadDATDEV7() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0298))
}

// WriteDATDEV7 writes DAT entry for device 7.
func (p *I3cV1I3C) WriteDATDEV7(val uint32) {
    reg.Write(uint32(p.Base)+0x0298, uint32(val))
}

// ReadDATDEV8 reads DAT entry for device 8.
func (p *I3cV1I3C) ReadDATDEV8() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x029c))
}

// WriteDATDEV8 writes DAT entry for device 8.
func (p *I3cV1I3C) WriteDATDEV8(val uint32) {
    reg.Write(uint32(p.Base)+0x029c, uint32(val))
}

