// Code generated by chiptool; DO NOT EDIT.

package pac

import "github.com/kyanitecomputer/aspeed-go/reg"

// I3cglobalV1I3CGLOBAL ASPEED I3C global wrapper registers. Base: 0x7E7A_0000. Six channels, 4 registers each starting at offset 0x010.
type I3cglobalV1I3CGLOBAL struct {
    Base uintptr
}

// ReadCH1PHY reads I3C Channel 1 PHY control (SDA pull-ups, CDR, de-glitch).
func (p *I3cglobalV1I3CGLOBAL) ReadCH1PHY() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0010))
}

// WriteCH1PHY writes I3C Channel 1 PHY control (SDA pull-ups, CDR, de-glitch).
func (p *I3cglobalV1I3CGLOBAL) WriteCH1PHY(val uint32) {
    reg.Write(uint32(p.Base)+0x0010, uint32(val))
}

// ReadCH1SLV reads I3C Channel 1 slave identity (static addr, instance ID, mode).
func (p *I3cglobalV1I3CGLOBAL) ReadCH1SLV() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0014))
}

// WriteCH1SLV writes I3C Channel 1 slave identity (static addr, instance ID, mode).
func (p *I3cglobalV1I3CGLOBAL) WriteCH1SLV(val uint32) {
    reg.Write(uint32(p.Base)+0x0014, uint32(val))
}

// ReadCH1DBG1 reads I3C Channel 1 debug signals (read-only).
func (p *I3cglobalV1I3CGLOBAL) ReadCH1DBG1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0018))
}

// WriteCH1DBG1 writes I3C Channel 1 debug signals (read-only).
func (p *I3cglobalV1I3CGLOBAL) WriteCH1DBG1(val uint32) {
    reg.Write(uint32(p.Base)+0x0018, uint32(val))
}

// ReadCH1DBG2 reads I3C Channel 1 debug IO and FSM (read-only).
func (p *I3cglobalV1I3CGLOBAL) ReadCH1DBG2() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x001c))
}

// WriteCH1DBG2 writes I3C Channel 1 debug IO and FSM (read-only).
func (p *I3cglobalV1I3CGLOBAL) WriteCH1DBG2(val uint32) {
    reg.Write(uint32(p.Base)+0x001c, uint32(val))
}

// ReadCH2PHY reads I3C Channel 2 PHY control.
func (p *I3cglobalV1I3CGLOBAL) ReadCH2PHY() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0020))
}

// WriteCH2PHY writes I3C Channel 2 PHY control.
func (p *I3cglobalV1I3CGLOBAL) WriteCH2PHY(val uint32) {
    reg.Write(uint32(p.Base)+0x0020, uint32(val))
}

// ReadCH2SLV reads I3C Channel 2 slave identity.
func (p *I3cglobalV1I3CGLOBAL) ReadCH2SLV() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0024))
}

// WriteCH2SLV writes I3C Channel 2 slave identity.
func (p *I3cglobalV1I3CGLOBAL) WriteCH2SLV(val uint32) {
    reg.Write(uint32(p.Base)+0x0024, uint32(val))
}

// ReadCH2DBG1 reads I3C Channel 2 debug signals.
func (p *I3cglobalV1I3CGLOBAL) ReadCH2DBG1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0028))
}

// WriteCH2DBG1 writes I3C Channel 2 debug signals.
func (p *I3cglobalV1I3CGLOBAL) WriteCH2DBG1(val uint32) {
    reg.Write(uint32(p.Base)+0x0028, uint32(val))
}

// ReadCH2DBG2 reads I3C Channel 2 debug IO and FSM.
func (p *I3cglobalV1I3CGLOBAL) ReadCH2DBG2() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x002c))
}

// WriteCH2DBG2 writes I3C Channel 2 debug IO and FSM.
func (p *I3cglobalV1I3CGLOBAL) WriteCH2DBG2(val uint32) {
    reg.Write(uint32(p.Base)+0x002c, uint32(val))
}

// ReadCH3PHY reads I3C Channel 3 PHY control.
func (p *I3cglobalV1I3CGLOBAL) ReadCH3PHY() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0030))
}

// WriteCH3PHY writes I3C Channel 3 PHY control.
func (p *I3cglobalV1I3CGLOBAL) WriteCH3PHY(val uint32) {
    reg.Write(uint32(p.Base)+0x0030, uint32(val))
}

// ReadCH3SLV reads I3C Channel 3 slave identity.
func (p *I3cglobalV1I3CGLOBAL) ReadCH3SLV() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0034))
}

// WriteCH3SLV writes I3C Channel 3 slave identity.
func (p *I3cglobalV1I3CGLOBAL) WriteCH3SLV(val uint32) {
    reg.Write(uint32(p.Base)+0x0034, uint32(val))
}

// ReadCH3DBG1 reads I3C Channel 3 debug signals.
func (p *I3cglobalV1I3CGLOBAL) ReadCH3DBG1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0038))
}

// WriteCH3DBG1 writes I3C Channel 3 debug signals.
func (p *I3cglobalV1I3CGLOBAL) WriteCH3DBG1(val uint32) {
    reg.Write(uint32(p.Base)+0x0038, uint32(val))
}

// ReadCH3DBG2 reads I3C Channel 3 debug IO and FSM.
func (p *I3cglobalV1I3CGLOBAL) ReadCH3DBG2() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x003c))
}

// WriteCH3DBG2 writes I3C Channel 3 debug IO and FSM.
func (p *I3cglobalV1I3CGLOBAL) WriteCH3DBG2(val uint32) {
    reg.Write(uint32(p.Base)+0x003c, uint32(val))
}

// ReadCH4PHY reads I3C Channel 4 PHY control.
func (p *I3cglobalV1I3CGLOBAL) ReadCH4PHY() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0040))
}

// WriteCH4PHY writes I3C Channel 4 PHY control.
func (p *I3cglobalV1I3CGLOBAL) WriteCH4PHY(val uint32) {
    reg.Write(uint32(p.Base)+0x0040, uint32(val))
}

// ReadCH4SLV reads I3C Channel 4 slave identity.
func (p *I3cglobalV1I3CGLOBAL) ReadCH4SLV() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0044))
}

// WriteCH4SLV writes I3C Channel 4 slave identity.
func (p *I3cglobalV1I3CGLOBAL) WriteCH4SLV(val uint32) {
    reg.Write(uint32(p.Base)+0x0044, uint32(val))
}

// ReadCH4DBG1 reads I3C Channel 4 debug signals.
func (p *I3cglobalV1I3CGLOBAL) ReadCH4DBG1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0048))
}

// WriteCH4DBG1 writes I3C Channel 4 debug signals.
func (p *I3cglobalV1I3CGLOBAL) WriteCH4DBG1(val uint32) {
    reg.Write(uint32(p.Base)+0x0048, uint32(val))
}

// ReadCH4DBG2 reads I3C Channel 4 debug IO and FSM.
func (p *I3cglobalV1I3CGLOBAL) ReadCH4DBG2() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x004c))
}

// WriteCH4DBG2 writes I3C Channel 4 debug IO and FSM.
func (p *I3cglobalV1I3CGLOBAL) WriteCH4DBG2(val uint32) {
    reg.Write(uint32(p.Base)+0x004c, uint32(val))
}

// ReadCH5PHY reads I3C Channel 5 PHY control (no SDA pull-up bits).
func (p *I3cglobalV1I3CGLOBAL) ReadCH5PHY() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0050))
}

// WriteCH5PHY writes I3C Channel 5 PHY control (no SDA pull-up bits).
func (p *I3cglobalV1I3CGLOBAL) WriteCH5PHY(val uint32) {
    reg.Write(uint32(p.Base)+0x0050, uint32(val))
}

// ReadCH5SLV reads I3C Channel 5 slave identity.
func (p *I3cglobalV1I3CGLOBAL) ReadCH5SLV() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0054))
}

// WriteCH5SLV writes I3C Channel 5 slave identity.
func (p *I3cglobalV1I3CGLOBAL) WriteCH5SLV(val uint32) {
    reg.Write(uint32(p.Base)+0x0054, uint32(val))
}

// ReadCH5DBG1 reads I3C Channel 5 debug signals.
func (p *I3cglobalV1I3CGLOBAL) ReadCH5DBG1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0058))
}

// WriteCH5DBG1 writes I3C Channel 5 debug signals.
func (p *I3cglobalV1I3CGLOBAL) WriteCH5DBG1(val uint32) {
    reg.Write(uint32(p.Base)+0x0058, uint32(val))
}

// ReadCH5DBG2 reads I3C Channel 5 debug IO and FSM.
func (p *I3cglobalV1I3CGLOBAL) ReadCH5DBG2() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x005c))
}

// WriteCH5DBG2 writes I3C Channel 5 debug IO and FSM.
func (p *I3cglobalV1I3CGLOBAL) WriteCH5DBG2(val uint32) {
    reg.Write(uint32(p.Base)+0x005c, uint32(val))
}

// ReadCH6PHY reads I3C Channel 6 PHY control (no SDA pull-up bits).
func (p *I3cglobalV1I3CGLOBAL) ReadCH6PHY() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0060))
}

// WriteCH6PHY writes I3C Channel 6 PHY control (no SDA pull-up bits).
func (p *I3cglobalV1I3CGLOBAL) WriteCH6PHY(val uint32) {
    reg.Write(uint32(p.Base)+0x0060, uint32(val))
}

// ReadCH6SLV reads I3C Channel 6 slave identity.
func (p *I3cglobalV1I3CGLOBAL) ReadCH6SLV() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0064))
}

// WriteCH6SLV writes I3C Channel 6 slave identity.
func (p *I3cglobalV1I3CGLOBAL) WriteCH6SLV(val uint32) {
    reg.Write(uint32(p.Base)+0x0064, uint32(val))
}

// ReadCH6DBG1 reads I3C Channel 6 debug signals.
func (p *I3cglobalV1I3CGLOBAL) ReadCH6DBG1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0068))
}

// WriteCH6DBG1 writes I3C Channel 6 debug signals.
func (p *I3cglobalV1I3CGLOBAL) WriteCH6DBG1(val uint32) {
    reg.Write(uint32(p.Base)+0x0068, uint32(val))
}

// ReadCH6DBG2 reads I3C Channel 6 debug IO and FSM.
func (p *I3cglobalV1I3CGLOBAL) ReadCH6DBG2() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x006c))
}

// WriteCH6DBG2 writes I3C Channel 6 debug IO and FSM.
func (p *I3cglobalV1I3CGLOBAL) WriteCH6DBG2(val uint32) {
    reg.Write(uint32(p.Base)+0x006c, uint32(val))
}

