// Code generated by chiptool; DO NOT EDIT.

package pac

import "github.com/kyanitecomputer/aspeed-go/reg"

// SecureV1SECURE ASPEED Secure Boot Controller (SB) and OTP engine. Base: 0x7E6F_2000. Covers OTP access, secure boot status, RSA/ECC engine, SBMCU DMA, vault key staging, and image digest readback.
type SecureV1SECURE struct {
    Base uintptr
}

// ReadPROTKEY reads Protection key (SEC00). Write 0x349f138a to unlock SB registers. Write any other value to lock. Readback: 1=unlocked, 0=locked.
func (p *SecureV1SECURE) ReadPROTKEY() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0000))
}

// WritePROTKEY writes Protection key (SEC00). Write 0x349f138a to unlock SB registers. Write any other value to lock. Readback: 1=unlocked, 0=locked.
func (p *SecureV1SECURE) WritePROTKEY(val uint32) {
    reg.Write(uint32(p.Base)+0x0000, uint32(val))
}

// ReadOTPCMDTRIG reads OTP command trigger (SEC04). Write command code to execute OTP operation: 0x23b1e361=dual-DW read, 0x23b1e362=mode-register write, 0x23b1e363=quad-DW compare, 0x23b1e364=program, 0x23b1e365=precharge.
func (p *SecureV1SECURE) ReadOTPCMDTRIG() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0004))
}

// WriteOTPCMDTRIG writes OTP command trigger (SEC04). Write command code to execute OTP operation: 0x23b1e361=dual-DW read, 0x23b1e362=mode-register write, 0x23b1e363=quad-DW compare, 0x23b1e364=program, 0x23b1e365=precharge.
func (p *SecureV1SECURE) WriteOTPCMDTRIG(val uint32) {
    reg.Write(uint32(p.Base)+0x0004, uint32(val))
}

// ReadOTPTIMING reads OTP access timing (SEC08). Read/write cycle times in 40 ns units.
func (p *SecureV1SECURE) ReadOTPTIMING() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0008))
}

// WriteOTPTIMING writes OTP access timing (SEC08). Read/write cycle times in 40 ns units.
func (p *SecureV1SECURE) WriteOTPTIMING(val uint32) {
    reg.Write(uint32(p.Base)+0x0008, uint32(val))
}

// ReadOTPADDR reads OTP memory address for read/write/compare (SEC10).
func (p *SecureV1SECURE) ReadOTPADDR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0010))
}

// WriteOTPADDR writes OTP memory address for read/write/compare (SEC10).
func (p *SecureV1SECURE) WriteOTPADDR(val uint32) {
    reg.Write(uint32(p.Base)+0x0010, uint32(val))
}

// ReadENGINESTATUS reads Secure engine status register (SEC14). Read-only. OTP controller idle, RSA/ECC ready, secure boot status flags.
func (p *SecureV1SECURE) ReadENGINESTATUS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0014))
}

// WriteENGINESTATUS writes Secure engine status register (SEC14). Read-only. OTP controller idle, RSA/ECC ready, secure boot status flags.
func (p *SecureV1SECURE) WriteENGINESTATUS(val uint32) {
    reg.Write(uint32(p.Base)+0x0014, uint32(val))
}

// ReadOTPPGMSTATUS reads OTP programming status (SEC18). Read-only. Write protection state.
func (p *SecureV1SECURE) ReadOTPPGMSTATUS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0018))
}

// WriteOTPPGMSTATUS writes OTP programming status (SEC18). Read-only. Write protection state.
func (p *SecureV1SECURE) WriteOTPPGMSTATUS(val uint32) {
    reg.Write(uint32(p.Base)+0x0018, uint32(val))
}

// ReadOTPCMPDATA1 reads OTP compare data word 1 / read result [31:0] (SEC20).
func (p *SecureV1SECURE) ReadOTPCMPDATA1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0020))
}

// WriteOTPCMPDATA1 writes OTP compare data word 1 / read result [31:0] (SEC20).
func (p *SecureV1SECURE) WriteOTPCMPDATA1(val uint32) {
    reg.Write(uint32(p.Base)+0x0020, uint32(val))
}

// ReadOTPCMPDATA2 reads OTP compare data word 2 [63:32] (SEC24).
func (p *SecureV1SECURE) ReadOTPCMPDATA2() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0024))
}

// WriteOTPCMPDATA2 writes OTP compare data word 2 [63:32] (SEC24).
func (p *SecureV1SECURE) WriteOTPCMPDATA2(val uint32) {
    reg.Write(uint32(p.Base)+0x0024, uint32(val))
}

// ReadOTPCMPDATA3 reads OTP compare data word 3 [95:64] (SEC28).
func (p *SecureV1SECURE) ReadOTPCMPDATA3() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0028))
}

// WriteOTPCMPDATA3 writes OTP compare data word 3 [95:64] (SEC28).
func (p *SecureV1SECURE) WriteOTPCMPDATA3(val uint32) {
    reg.Write(uint32(p.Base)+0x0028, uint32(val))
}

// ReadOTPCMPDATA4 reads OTP compare data word 4 [127:96] (SEC2C, read-only).
func (p *SecureV1SECURE) ReadOTPCMPDATA4() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x002c))
}

// WriteOTPCMPDATA4 writes OTP compare data word 4 [127:96] (SEC2C, read-only).
func (p *SecureV1SECURE) WriteOTPCMPDATA4(val uint32) {
    reg.Write(uint32(p.Base)+0x002c, uint32(val))
}

// ReadOTPTRAPLO reads OTP strap bits [31:0] readback (SEC30, read-only).
func (p *SecureV1SECURE) ReadOTPTRAPLO() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0030))
}

// WriteOTPTRAPLO writes OTP strap bits [31:0] readback (SEC30, read-only).
func (p *SecureV1SECURE) WriteOTPTRAPLO(val uint32) {
    reg.Write(uint32(p.Base)+0x0030, uint32(val))
}

// ReadOTPTRAPHI reads OTP strap bits [63:32] readback (SEC34, read-only).
func (p *SecureV1SECURE) ReadOTPTRAPHI() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0034))
}

// WriteOTPTRAPHI writes OTP strap bits [63:32] readback (SEC34, read-only).
func (p *SecureV1SECURE) WriteOTPTRAPHI(val uint32) {
    reg.Write(uint32(p.Base)+0x0034, uint32(val))
}

// ReadOTPQRR reads OTP Quality Repair Register readback (SEC38, read-only).
func (p *SecureV1SECURE) ReadOTPQRR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0038))
}

// WriteOTPQRR writes OTP Quality Repair Register readback (SEC38, read-only).
func (p *SecureV1SECURE) WriteOTPQRR(val uint32) {
    reg.Write(uint32(p.Base)+0x0038, uint32(val))
}

// ReadOTPQSR reads OTP Quality Status Register readback (SEC40, read-only).
func (p *SecureV1SECURE) ReadOTPQSR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0040))
}

// WriteOTPQSR writes OTP Quality Status Register readback (SEC40, read-only).
func (p *SecureV1SECURE) WriteOTPQSR(val uint32) {
    reg.Write(uint32(p.Base)+0x0040, uint32(val))
}

// ReadOTPQMR reads OTP Quality Mask Register readback (SEC44, read-only).
func (p *SecureV1SECURE) ReadOTPQMR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0044))
}

// WriteOTPQMR writes OTP Quality Mask Register readback (SEC44, read-only).
func (p *SecureV1SECURE) WriteOTPQMR(val uint32) {
    reg.Write(uint32(p.Base)+0x0044, uint32(val))
}

// ReadOTPQMRAB reads OTP QMRA [15:0] and QMRB [31:16] readback (SEC48, read-only).
func (p *SecureV1SECURE) ReadOTPQMRAB() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0048))
}

// WriteOTPQMRAB writes OTP QMRA [15:0] and QMRB [31:16] readback (SEC48, read-only).
func (p *SecureV1SECURE) WriteOTPQMRAB(val uint32) {
    reg.Write(uint32(p.Base)+0x0048, uint32(val))
}

// ReadEXTRAPGMPROT reads Extra OTP programming protection range (SEC50). Increasing only.
func (p *SecureV1SECURE) ReadEXTRAPGMPROT() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0050))
}

// WriteEXTRAPGMPROT writes Extra OTP programming protection range (SEC50). Increasing only.
func (p *SecureV1SECURE) WriteEXTRAPGMPROT(val uint32) {
    reg.Write(uint32(p.Base)+0x0050, uint32(val))
}

// ReadEXTRARDPROT reads Extra OTP read protection range (SEC54). Increasing only.
func (p *SecureV1SECURE) ReadEXTRARDPROT() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0054))
}

// WriteEXTRARDPROT writes Extra OTP read protection range (SEC54). Increasing only.
func (p *SecureV1SECURE) WriteEXTRARDPROT(val uint32) {
    reg.Write(uint32(p.Base)+0x0054, uint32(val))
}

// ReadHWREV1 reads HW Revision Register 1 / OTPCFG10 (SEC60). Loaded by SB engine; write-protected after load.
func (p *SecureV1SECURE) ReadHWREV1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0060))
}

// WriteHWREV1 writes HW Revision Register 1 / OTPCFG10 (SEC60). Loaded by SB engine; write-protected after load.
func (p *SecureV1SECURE) WriteHWREV1(val uint32) {
    reg.Write(uint32(p.Base)+0x0060, uint32(val))
}

// ReadHWREV2 reads HW Revision Register 2 / OTPCFG11 (SEC64).
func (p *SecureV1SECURE) ReadHWREV2() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0064))
}

// WriteHWREV2 writes HW Revision Register 2 / OTPCFG11 (SEC64).
func (p *SecureV1SECURE) WriteHWREV2(val uint32) {
    reg.Write(uint32(p.Base)+0x0064, uint32(val))
}

// ReadSWREV1 reads SW Revision Register 1 / SBH10 (SEC68). From secure boot header offset 0x10.
func (p *SecureV1SECURE) ReadSWREV1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0068))
}

// WriteSWREV1 writes SW Revision Register 1 / SBH10 (SEC68). From secure boot header offset 0x10.
func (p *SecureV1SECURE) WriteSWREV1(val uint32) {
    reg.Write(uint32(p.Base)+0x0068, uint32(val))
}

// ReadSWREV2 reads SW Revision Register 2 / SBH14 (SEC6C). From secure boot header offset 0x14.
func (p *SecureV1SECURE) ReadSWREV2() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x006c))
}

// WriteSWREV2 writes SW Revision Register 2 / SBH14 (SEC6C). From secure boot header offset 0x14.
func (p *SecureV1SECURE) WriteSWREV2(val uint32) {
    reg.Write(uint32(p.Base)+0x006c, uint32(val))
}

// ReadSPIBOOTSTATUS reads Secure boot SPI check status (SEC70).
func (p *SecureV1SECURE) ReadSPIBOOTSTATUS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0070))
}

// WriteSPIBOOTSTATUS writes Secure boot SPI check status (SEC70).
func (p *SecureV1SECURE) WriteSPIBOOTSTATUS(val uint32) {
    reg.Write(uint32(p.Base)+0x0070, uint32(val))
}

// ReadSBKEYNUM reads Secure boot key number used and image encryption status (SEC78).
func (p *SecureV1SECURE) ReadSBKEYNUM() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0078))
}

// WriteSBKEYNUM writes Secure boot key number used and image encryption status (SEC78).
func (p *SecureV1SECURE) WriteSBKEYNUM(val uint32) {
    reg.Write(uint32(p.Base)+0x0078, uint32(val))
}

// ReadSWECCCTRL reads Software ECC disable control (SEC88). For failure analysis only.
func (p *SecureV1SECURE) ReadSWECCCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0088))
}

// WriteSWECCCTRL writes Software ECC disable control (SEC88). For failure analysis only.
func (p *SecureV1SECURE) WriteSWECCCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x0088, uint32(val))
}

// ReadRSACTRL reads RSA engine controller (SECB0). Set modulus and exponent bit widths before firing.
func (p *SecureV1SECURE) ReadRSACTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00b0))
}

// WriteRSACTRL writes RSA engine controller (SECB0). Set modulus and exponent bit widths before firing.
func (p *SecureV1SECURE) WriteRSACTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x00b0, uint32(val))
}

// ReadECCCTRL reads ECC engine controller (SECB4). Enable ECC and ECDSA-384.
func (p *SecureV1SECURE) ReadECCCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00b4))
}

// WriteECCCTRL writes ECC engine controller (SECB4). Enable ECC and ECDSA-384.
func (p *SecureV1SECURE) WriteECCCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x00b4, uint32(val))
}

// ReadENGINETRIG reads RSA/ECC engine trigger (SECBC). Write 1 to fire respective engine.
func (p *SecureV1SECURE) ReadENGINETRIG() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00bc))
}

// WriteENGINETRIG writes RSA/ECC engine trigger (SECBC). Write 1 to fire respective engine.
func (p *SecureV1SECURE) WriteENGINETRIG(val uint32) {
    reg.Write(uint32(p.Base)+0x00bc, uint32(val))
}

// ReadENGINEIRQCTRL reads RSA/ECC engine interrupt enable (SECC0).
func (p *SecureV1SECURE) ReadENGINEIRQCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00c0))
}

// WriteENGINEIRQCTRL writes RSA/ECC engine interrupt enable (SECC0).
func (p *SecureV1SECURE) WriteENGINEIRQCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x00c0, uint32(val))
}

// ReadENGINEIRQSTATUS reads RSA/ECC engine interrupt status (SECC4). Write 1 to clear.
func (p *SecureV1SECURE) ReadENGINEIRQSTATUS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00c4))
}

// WriteENGINEIRQSTATUS writes RSA/ECC engine interrupt status (SECC4). Write 1 to clear.
func (p *SecureV1SECURE) WriteENGINEIRQSTATUS(val uint32) {
    reg.Write(uint32(p.Base)+0x00c4, uint32(val))
}

// ReadDMAENABLE reads Secure boot DMA enable (SEC800). Write 1 to trigger DMA (SBMCU use only).
func (p *SecureV1SECURE) ReadDMAENABLE() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0800))
}

// WriteDMAENABLE writes Secure boot DMA enable (SEC800). Write 1 to trigger DMA (SBMCU use only).
func (p *SecureV1SECURE) WriteDMAENABLE(val uint32) {
    reg.Write(uint32(p.Base)+0x0800, uint32(val))
}

// ReadVAULTKEYCTRL reads Vault key control (SEC80C). Select which of two vault keys HACE uses. Lock vault key write access and selection.
func (p *SecureV1SECURE) ReadVAULTKEYCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x080c))
}

// WriteVAULTKEYCTRL writes Vault key control (SEC80C). Select which of two vault keys HACE uses. Lock vault key write access and selection.
func (p *SecureV1SECURE) WriteVAULTKEYCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x080c, uint32(val))
}

// ReadDIGESTRESULT reads Secure boot digest check pass/fail result (SEC810).
func (p *SecureV1SECURE) ReadDIGESTRESULT() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0810))
}

// WriteDIGESTRESULT writes Secure boot digest check pass/fail result (SEC810).
func (p *SecureV1SECURE) WriteDIGESTRESULT(val uint32) {
    reg.Write(uint32(p.Base)+0x0810, uint32(val))
}

// ReadDIGESTSTATUS reads Secure boot digest check busy status (SEC814).
func (p *SecureV1SECURE) ReadDIGESTSTATUS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0814))
}

// WriteDIGESTSTATUS writes Secure boot digest check busy status (SEC814).
func (p *SecureV1SECURE) WriteDIGESTSTATUS(val uint32) {
    reg.Write(uint32(p.Base)+0x0814, uint32(val))
}

// ReadSCEENABLE reads Secure crypto engine enable (SEC820). When enabled, the open HACE engine is disabled. Write 1 to enable (SBMCU use only).
func (p *SecureV1SECURE) ReadSCEENABLE() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0820))
}

// WriteSCEENABLE writes Secure crypto engine enable (SEC820). When enabled, the open HACE engine is disabled. Write 1 to enable (SBMCU use only).
func (p *SecureV1SECURE) WriteSCEENABLE(val uint32) {
    reg.Write(uint32(p.Base)+0x0820, uint32(val))
}

// ReadDMASRCADDR reads Secure boot DMA source address (SEC840, 4-byte aligned).
func (p *SecureV1SECURE) ReadDMASRCADDR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0840))
}

// WriteDMASRCADDR writes Secure boot DMA source address (SEC840, 4-byte aligned).
func (p *SecureV1SECURE) WriteDMASRCADDR(val uint32) {
    reg.Write(uint32(p.Base)+0x0840, uint32(val))
}

// ReadDMADSTADDR reads Secure boot DMA destination address (SEC844, 4-byte aligned).
func (p *SecureV1SECURE) ReadDMADSTADDR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0844))
}

// WriteDMADSTADDR writes Secure boot DMA destination address (SEC844, 4-byte aligned).
func (p *SecureV1SECURE) WriteDMADSTADDR(val uint32) {
    reg.Write(uint32(p.Base)+0x0844, uint32(val))
}

// ReadDMASIZE reads Secure boot DMA transfer size in bytes (SEC848, max 128 KB-1).
func (p *SecureV1SECURE) ReadDMASIZE() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0848))
}

// WriteDMASIZE writes Secure boot DMA transfer size in bytes (SEC848, max 128 KB-1).
func (p *SecureV1SECURE) WriteDMASIZE(val uint32) {
    reg.Write(uint32(p.Base)+0x0848, uint32(val))
}

// ReadHASHFIRE reads Secure boot hash engine fire trigger (SEC85C). Write any value to start.
func (p *SecureV1SECURE) ReadHASHFIRE() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x085c))
}

// WriteHASHFIRE writes Secure boot hash engine fire trigger (SEC85C). Write any value to start.
func (p *SecureV1SECURE) WriteHASHFIRE(val uint32) {
    reg.Write(uint32(p.Base)+0x085c, uint32(val))
}

// ReadCRYPTOFIRE reads Secure boot crypto engine fire trigger (SEC87C). Write any value to start.
func (p *SecureV1SECURE) ReadCRYPTOFIRE() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x087c))
}

// WriteCRYPTOFIRE writes Secure boot crypto engine fire trigger (SEC87C). Write any value to start.
func (p *SecureV1SECURE) WriteCRYPTOFIRE(val uint32) {
    reg.Write(uint32(p.Base)+0x087c, uint32(val))
}

// ReadCRYPTODATA0 reads Secure crypto input data bits [31:0] (SEC880, write-only).
func (p *SecureV1SECURE) ReadCRYPTODATA0() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0880))
}

// WriteCRYPTODATA0 writes Secure crypto input data bits [31:0] (SEC880, write-only).
func (p *SecureV1SECURE) WriteCRYPTODATA0(val uint32) {
    reg.Write(uint32(p.Base)+0x0880, uint32(val))
}

// ReadCRYPTODATA1 reads Secure crypto input data bits [63:32] (SEC884, write-only).
func (p *SecureV1SECURE) ReadCRYPTODATA1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0884))
}

// WriteCRYPTODATA1 writes Secure crypto input data bits [63:32] (SEC884, write-only).
func (p *SecureV1SECURE) WriteCRYPTODATA1(val uint32) {
    reg.Write(uint32(p.Base)+0x0884, uint32(val))
}

// ReadCRYPTODATA2 reads Secure crypto input data bits [95:64] (SEC888, write-only).
func (p *SecureV1SECURE) ReadCRYPTODATA2() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0888))
}

// WriteCRYPTODATA2 writes Secure crypto input data bits [95:64] (SEC888, write-only).
func (p *SecureV1SECURE) WriteCRYPTODATA2(val uint32) {
    reg.Write(uint32(p.Base)+0x0888, uint32(val))
}

// ReadCRYPTODATA3 reads Secure crypto input data bits [127:96] (SEC88C, write-only).
func (p *SecureV1SECURE) ReadCRYPTODATA3() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x088c))
}

// WriteCRYPTODATA3 writes Secure crypto input data bits [127:96] (SEC88C, write-only).
func (p *SecureV1SECURE) WriteCRYPTODATA3(val uint32) {
    reg.Write(uint32(p.Base)+0x088c, uint32(val))
}

// ReadCRYPTOKEY0 reads Secure crypto key / IV bits [31:0] (SEC8A0, write-only).
func (p *SecureV1SECURE) ReadCRYPTOKEY0() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x08a0))
}

// WriteCRYPTOKEY0 writes Secure crypto key / IV bits [31:0] (SEC8A0, write-only).
func (p *SecureV1SECURE) WriteCRYPTOKEY0(val uint32) {
    reg.Write(uint32(p.Base)+0x08a0, uint32(val))
}

// ReadCRYPTOKEY1 reads Secure crypto key / IV bits [63:32] (SEC8A4, write-only).
func (p *SecureV1SECURE) ReadCRYPTOKEY1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x08a4))
}

// WriteCRYPTOKEY1 writes Secure crypto key / IV bits [63:32] (SEC8A4, write-only).
func (p *SecureV1SECURE) WriteCRYPTOKEY1(val uint32) {
    reg.Write(uint32(p.Base)+0x08a4, uint32(val))
}

// ReadCRYPTOKEY2 reads Secure crypto key / IV bits [95:64] (SEC8A8, write-only).
func (p *SecureV1SECURE) ReadCRYPTOKEY2() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x08a8))
}

// WriteCRYPTOKEY2 writes Secure crypto key / IV bits [95:64] (SEC8A8, write-only).
func (p *SecureV1SECURE) WriteCRYPTOKEY2(val uint32) {
    reg.Write(uint32(p.Base)+0x08a8, uint32(val))
}

// ReadCRYPTOKEY3 reads Secure crypto key / IV bits [127:96] (SEC8AC, write-only).
func (p *SecureV1SECURE) ReadCRYPTOKEY3() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x08ac))
}

// WriteCRYPTOKEY3 writes Secure crypto key / IV bits [127:96] (SEC8AC, write-only).
func (p *SecureV1SECURE) WriteCRYPTOKEY3(val uint32) {
    reg.Write(uint32(p.Base)+0x08ac, uint32(val))
}

// ReadCRYPTOKEY4 reads Secure crypto key bits [159:128] (SEC8B0, write-only).
func (p *SecureV1SECURE) ReadCRYPTOKEY4() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x08b0))
}

// WriteCRYPTOKEY4 writes Secure crypto key bits [159:128] (SEC8B0, write-only).
func (p *SecureV1SECURE) WriteCRYPTOKEY4(val uint32) {
    reg.Write(uint32(p.Base)+0x08b0, uint32(val))
}

// ReadCRYPTOKEY5 reads Secure crypto key bits [191:160] (SEC8B4, write-only).
func (p *SecureV1SECURE) ReadCRYPTOKEY5() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x08b4))
}

// WriteCRYPTOKEY5 writes Secure crypto key bits [191:160] (SEC8B4, write-only).
func (p *SecureV1SECURE) WriteCRYPTOKEY5(val uint32) {
    reg.Write(uint32(p.Base)+0x08b4, uint32(val))
}

// ReadCRYPTOKEY6 reads Secure crypto key bits [223:192] (SEC8B8, write-only).
func (p *SecureV1SECURE) ReadCRYPTOKEY6() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x08b8))
}

// WriteCRYPTOKEY6 writes Secure crypto key bits [223:192] (SEC8B8, write-only).
func (p *SecureV1SECURE) WriteCRYPTOKEY6(val uint32) {
    reg.Write(uint32(p.Base)+0x08b8, uint32(val))
}

// ReadCRYPTOKEY7 reads Secure crypto key bits [255:224] (SEC8BC, write-only).
func (p *SecureV1SECURE) ReadCRYPTOKEY7() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x08bc))
}

// WriteCRYPTOKEY7 writes Secure crypto key bits [255:224] (SEC8BC, write-only).
func (p *SecureV1SECURE) WriteCRYPTOKEY7(val uint32) {
    reg.Write(uint32(p.Base)+0x08bc, uint32(val))
}

// ReadVAULTKEY1W0 reads First vault key bits [31:0] (SEC900, write-only).
func (p *SecureV1SECURE) ReadVAULTKEY1W0() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0900))
}

// WriteVAULTKEY1W0 writes First vault key bits [31:0] (SEC900, write-only).
func (p *SecureV1SECURE) WriteVAULTKEY1W0(val uint32) {
    reg.Write(uint32(p.Base)+0x0900, uint32(val))
}

// ReadVAULTKEY1W1 reads First vault key bits [63:32] (SEC904, write-only).
func (p *SecureV1SECURE) ReadVAULTKEY1W1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0904))
}

// WriteVAULTKEY1W1 writes First vault key bits [63:32] (SEC904, write-only).
func (p *SecureV1SECURE) WriteVAULTKEY1W1(val uint32) {
    reg.Write(uint32(p.Base)+0x0904, uint32(val))
}

// ReadVAULTKEY1W2 reads First vault key bits [95:64] (SEC908, write-only).
func (p *SecureV1SECURE) ReadVAULTKEY1W2() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0908))
}

// WriteVAULTKEY1W2 writes First vault key bits [95:64] (SEC908, write-only).
func (p *SecureV1SECURE) WriteVAULTKEY1W2(val uint32) {
    reg.Write(uint32(p.Base)+0x0908, uint32(val))
}

// ReadVAULTKEY1W3 reads First vault key bits [127:96] (SEC90C, write-only).
func (p *SecureV1SECURE) ReadVAULTKEY1W3() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x090c))
}

// WriteVAULTKEY1W3 writes First vault key bits [127:96] (SEC90C, write-only).
func (p *SecureV1SECURE) WriteVAULTKEY1W3(val uint32) {
    reg.Write(uint32(p.Base)+0x090c, uint32(val))
}

// ReadVAULTKEY1W4 reads First vault key bits [159:128] (SEC910, write-only).
func (p *SecureV1SECURE) ReadVAULTKEY1W4() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0910))
}

// WriteVAULTKEY1W4 writes First vault key bits [159:128] (SEC910, write-only).
func (p *SecureV1SECURE) WriteVAULTKEY1W4(val uint32) {
    reg.Write(uint32(p.Base)+0x0910, uint32(val))
}

// ReadVAULTKEY1W5 reads First vault key bits [191:160] (SEC914, write-only).
func (p *SecureV1SECURE) ReadVAULTKEY1W5() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0914))
}

// WriteVAULTKEY1W5 writes First vault key bits [191:160] (SEC914, write-only).
func (p *SecureV1SECURE) WriteVAULTKEY1W5(val uint32) {
    reg.Write(uint32(p.Base)+0x0914, uint32(val))
}

// ReadVAULTKEY1W6 reads First vault key bits [223:192] (SEC918, write-only).
func (p *SecureV1SECURE) ReadVAULTKEY1W6() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0918))
}

// WriteVAULTKEY1W6 writes First vault key bits [223:192] (SEC918, write-only).
func (p *SecureV1SECURE) WriteVAULTKEY1W6(val uint32) {
    reg.Write(uint32(p.Base)+0x0918, uint32(val))
}

// ReadVAULTKEY1W7 reads First vault key bits [255:224] (SEC91C, write-only).
func (p *SecureV1SECURE) ReadVAULTKEY1W7() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x091c))
}

// WriteVAULTKEY1W7 writes First vault key bits [255:224] (SEC91C, write-only).
func (p *SecureV1SECURE) WriteVAULTKEY1W7(val uint32) {
    reg.Write(uint32(p.Base)+0x091c, uint32(val))
}

// ReadVAULTKEY2W0 reads Second vault key bits [31:0] (SEC920, write-only).
func (p *SecureV1SECURE) ReadVAULTKEY2W0() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0920))
}

// WriteVAULTKEY2W0 writes Second vault key bits [31:0] (SEC920, write-only).
func (p *SecureV1SECURE) WriteVAULTKEY2W0(val uint32) {
    reg.Write(uint32(p.Base)+0x0920, uint32(val))
}

// ReadVAULTKEY2W1 reads Second vault key bits [63:32] (SEC924, write-only).
func (p *SecureV1SECURE) ReadVAULTKEY2W1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0924))
}

// WriteVAULTKEY2W1 writes Second vault key bits [63:32] (SEC924, write-only).
func (p *SecureV1SECURE) WriteVAULTKEY2W1(val uint32) {
    reg.Write(uint32(p.Base)+0x0924, uint32(val))
}

// ReadVAULTKEY2W2 reads Second vault key bits [95:64] (SEC928, write-only).
func (p *SecureV1SECURE) ReadVAULTKEY2W2() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0928))
}

// WriteVAULTKEY2W2 writes Second vault key bits [95:64] (SEC928, write-only).
func (p *SecureV1SECURE) WriteVAULTKEY2W2(val uint32) {
    reg.Write(uint32(p.Base)+0x0928, uint32(val))
}

// ReadVAULTKEY2W3 reads Second vault key bits [127:96] (SEC92C, write-only).
func (p *SecureV1SECURE) ReadVAULTKEY2W3() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x092c))
}

// WriteVAULTKEY2W3 writes Second vault key bits [127:96] (SEC92C, write-only).
func (p *SecureV1SECURE) WriteVAULTKEY2W3(val uint32) {
    reg.Write(uint32(p.Base)+0x092c, uint32(val))
}

// ReadVAULTKEY2W4 reads Second vault key bits [159:128] (SEC930, write-only).
func (p *SecureV1SECURE) ReadVAULTKEY2W4() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0930))
}

// WriteVAULTKEY2W4 writes Second vault key bits [159:128] (SEC930, write-only).
func (p *SecureV1SECURE) WriteVAULTKEY2W4(val uint32) {
    reg.Write(uint32(p.Base)+0x0930, uint32(val))
}

// ReadVAULTKEY2W5 reads Second vault key bits [191:160] (SEC934, write-only).
func (p *SecureV1SECURE) ReadVAULTKEY2W5() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0934))
}

// WriteVAULTKEY2W5 writes Second vault key bits [191:160] (SEC934, write-only).
func (p *SecureV1SECURE) WriteVAULTKEY2W5(val uint32) {
    reg.Write(uint32(p.Base)+0x0934, uint32(val))
}

// ReadVAULTKEY2W6 reads Second vault key bits [223:192] (SEC938, write-only).
func (p *SecureV1SECURE) ReadVAULTKEY2W6() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0938))
}

// WriteVAULTKEY2W6 writes Second vault key bits [223:192] (SEC938, write-only).
func (p *SecureV1SECURE) WriteVAULTKEY2W6(val uint32) {
    reg.Write(uint32(p.Base)+0x0938, uint32(val))
}

// ReadVAULTKEY2W7 reads Second vault key bits [255:224] (SEC93C, write-only).
func (p *SecureV1SECURE) ReadVAULTKEY2W7() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x093c))
}

// WriteVAULTKEY2W7 writes Second vault key bits [255:224] (SEC93C, write-only).
func (p *SecureV1SECURE) WriteVAULTKEY2W7(val uint32) {
    reg.Write(uint32(p.Base)+0x093c, uint32(val))
}

// ReadIMGDIGEST0 reads Image digest readback word 0 (SEC980).
func (p *SecureV1SECURE) ReadIMGDIGEST0() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0980))
}

// WriteIMGDIGEST0 writes Image digest readback word 0 (SEC980).
func (p *SecureV1SECURE) WriteIMGDIGEST0(val uint32) {
    reg.Write(uint32(p.Base)+0x0980, uint32(val))
}

// ReadIMGDIGEST1 reads Image digest readback word 1 (SEC984).
func (p *SecureV1SECURE) ReadIMGDIGEST1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0984))
}

// WriteIMGDIGEST1 writes Image digest readback word 1 (SEC984).
func (p *SecureV1SECURE) WriteIMGDIGEST1(val uint32) {
    reg.Write(uint32(p.Base)+0x0984, uint32(val))
}

// ReadIMGDIGEST2 reads Image digest readback word 2 (SEC988).
func (p *SecureV1SECURE) ReadIMGDIGEST2() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0988))
}

// WriteIMGDIGEST2 writes Image digest readback word 2 (SEC988).
func (p *SecureV1SECURE) WriteIMGDIGEST2(val uint32) {
    reg.Write(uint32(p.Base)+0x0988, uint32(val))
}

// ReadIMGDIGEST3 reads Image digest readback word 3 (SEC98C).
func (p *SecureV1SECURE) ReadIMGDIGEST3() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x098c))
}

// WriteIMGDIGEST3 writes Image digest readback word 3 (SEC98C).
func (p *SecureV1SECURE) WriteIMGDIGEST3(val uint32) {
    reg.Write(uint32(p.Base)+0x098c, uint32(val))
}

// ReadIMGDIGEST4 reads Image digest readback word 4 (SEC990).
func (p *SecureV1SECURE) ReadIMGDIGEST4() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0990))
}

// WriteIMGDIGEST4 writes Image digest readback word 4 (SEC990).
func (p *SecureV1SECURE) WriteIMGDIGEST4(val uint32) {
    reg.Write(uint32(p.Base)+0x0990, uint32(val))
}

// ReadIMGDIGEST5 reads Image digest readback word 5 (SEC994).
func (p *SecureV1SECURE) ReadIMGDIGEST5() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0994))
}

// WriteIMGDIGEST5 writes Image digest readback word 5 (SEC994).
func (p *SecureV1SECURE) WriteIMGDIGEST5(val uint32) {
    reg.Write(uint32(p.Base)+0x0994, uint32(val))
}

// ReadIMGDIGEST6 reads Image digest readback word 6 (SEC998).
func (p *SecureV1SECURE) ReadIMGDIGEST6() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0998))
}

// WriteIMGDIGEST6 writes Image digest readback word 6 (SEC998).
func (p *SecureV1SECURE) WriteIMGDIGEST6(val uint32) {
    reg.Write(uint32(p.Base)+0x0998, uint32(val))
}

// ReadIMGDIGEST7 reads Image digest readback word 7 (SEC99C).
func (p *SecureV1SECURE) ReadIMGDIGEST7() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x099c))
}

// WriteIMGDIGEST7 writes Image digest readback word 7 (SEC99C).
func (p *SecureV1SECURE) WriteIMGDIGEST7(val uint32) {
    reg.Write(uint32(p.Base)+0x099c, uint32(val))
}

// ReadIMGDIGEST8 reads Image digest readback word 8 (SEC9A0).
func (p *SecureV1SECURE) ReadIMGDIGEST8() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x09a0))
}

// WriteIMGDIGEST8 writes Image digest readback word 8 (SEC9A0).
func (p *SecureV1SECURE) WriteIMGDIGEST8(val uint32) {
    reg.Write(uint32(p.Base)+0x09a0, uint32(val))
}

// ReadIMGDIGEST9 reads Image digest readback word 9 (SEC9A4).
func (p *SecureV1SECURE) ReadIMGDIGEST9() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x09a4))
}

// WriteIMGDIGEST9 writes Image digest readback word 9 (SEC9A4).
func (p *SecureV1SECURE) WriteIMGDIGEST9(val uint32) {
    reg.Write(uint32(p.Base)+0x09a4, uint32(val))
}

// ReadIMGDIGEST10 reads Image digest readback word 10 (SEC9A8).
func (p *SecureV1SECURE) ReadIMGDIGEST10() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x09a8))
}

// WriteIMGDIGEST10 writes Image digest readback word 10 (SEC9A8).
func (p *SecureV1SECURE) WriteIMGDIGEST10(val uint32) {
    reg.Write(uint32(p.Base)+0x09a8, uint32(val))
}

// ReadIMGDIGEST11 reads Image digest readback word 11 (SEC9AC).
func (p *SecureV1SECURE) ReadIMGDIGEST11() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x09ac))
}

// WriteIMGDIGEST11 writes Image digest readback word 11 (SEC9AC).
func (p *SecureV1SECURE) WriteIMGDIGEST11(val uint32) {
    reg.Write(uint32(p.Base)+0x09ac, uint32(val))
}

// ReadIMGDIGEST12 reads Image digest readback word 12 (SEC9B0).
func (p *SecureV1SECURE) ReadIMGDIGEST12() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x09b0))
}

// WriteIMGDIGEST12 writes Image digest readback word 12 (SEC9B0).
func (p *SecureV1SECURE) WriteIMGDIGEST12(val uint32) {
    reg.Write(uint32(p.Base)+0x09b0, uint32(val))
}

// ReadIMGDIGEST13 reads Image digest readback word 13 (SEC9B4).
func (p *SecureV1SECURE) ReadIMGDIGEST13() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x09b4))
}

// WriteIMGDIGEST13 writes Image digest readback word 13 (SEC9B4).
func (p *SecureV1SECURE) WriteIMGDIGEST13(val uint32) {
    reg.Write(uint32(p.Base)+0x09b4, uint32(val))
}

// ReadIMGDIGEST14 reads Image digest readback word 14 (SEC9B8).
func (p *SecureV1SECURE) ReadIMGDIGEST14() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x09b8))
}

// WriteIMGDIGEST14 writes Image digest readback word 14 (SEC9B8).
func (p *SecureV1SECURE) WriteIMGDIGEST14(val uint32) {
    reg.Write(uint32(p.Base)+0x09b8, uint32(val))
}

// ReadIMGDIGEST15 reads Image digest readback word 15 (SEC9BC).
func (p *SecureV1SECURE) ReadIMGDIGEST15() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x09bc))
}

// WriteIMGDIGEST15 writes Image digest readback word 15 (SEC9BC).
func (p *SecureV1SECURE) WriteIMGDIGEST15(val uint32) {
    reg.Write(uint32(p.Base)+0x09bc, uint32(val))
}

