// Code generated by chiptool; DO NOT EDIT.

package pac

import "github.com/kyanitecomputer/aspeed-go/reg"

// SgpioV1SGPIO ASPEED Serial GPIO Master (SGPIO). Embedded in the GPIO controller at base offset 0x500 (AST1060 GPIO base: 0x7E780000). Instance base for this block: 0x7E780500. Up to 128 output + 128 input bits via 4 serial pins.
type SgpioV1SGPIO struct {
    Base uintptr
}

// ReadABCDDATA reads Serial GPIO ABCD data value register (GPIO500). Output data: bits[7:0]=A, bits[15:8]=B, bits[23:16]=C, bits[31:24]=D. Also receives captured input data from SGPMI on each shift cycle.
func (p *SgpioV1SGPIO) ReadABCDDATA() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0000))
}

// WriteABCDDATA writes Serial GPIO ABCD data value register (GPIO500). Output data: bits[7:0]=A, bits[15:8]=B, bits[23:16]=C, bits[31:24]=D. Also receives captured input data from SGPMI on each shift cycle.
func (p *SgpioV1SGPIO) WriteABCDDATA(val uint32) {
    reg.Write(uint32(p.Base)+0x0000, uint32(val))
}

// ReadABCDIRQEN reads Serial GPIO ABCD interrupt enable (GPIO504). Per-bit: 1=enable interrupt for that pin.
func (p *SgpioV1SGPIO) ReadABCDIRQEN() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0004))
}

// WriteABCDIRQEN writes Serial GPIO ABCD interrupt enable (GPIO504). Per-bit: 1=enable interrupt for that pin.
func (p *SgpioV1SGPIO) WriteABCDIRQEN(val uint32) {
    reg.Write(uint32(p.Base)+0x0004, uint32(val))
}

// ReadABCDIRQSENS0 reads Serial GPIO ABCD interrupt sensitivity type 0 (GPIO508). Per-bit: 0=falling-edge or level-low, 1=rising-edge or level-high.
func (p *SgpioV1SGPIO) ReadABCDIRQSENS0() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0008))
}

// WriteABCDIRQSENS0 writes Serial GPIO ABCD interrupt sensitivity type 0 (GPIO508). Per-bit: 0=falling-edge or level-low, 1=rising-edge or level-high.
func (p *SgpioV1SGPIO) WriteABCDIRQSENS0(val uint32) {
    reg.Write(uint32(p.Base)+0x0008, uint32(val))
}

// ReadABCDIRQSENS1 reads Serial GPIO ABCD interrupt sensitivity type 1 (GPIO50C). Per-bit: 0=edge trigger, 1=level trigger.
func (p *SgpioV1SGPIO) ReadABCDIRQSENS1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x000c))
}

// WriteABCDIRQSENS1 writes Serial GPIO ABCD interrupt sensitivity type 1 (GPIO50C). Per-bit: 0=edge trigger, 1=level trigger.
func (p *SgpioV1SGPIO) WriteABCDIRQSENS1(val uint32) {
    reg.Write(uint32(p.Base)+0x000c, uint32(val))
}

// ReadABCDIRQSENS2 reads Serial GPIO ABCD interrupt sensitivity type 2 (GPIO510). Per-bit: 0=single-edge or level, 1=dual-edge trigger.
func (p *SgpioV1SGPIO) ReadABCDIRQSENS2() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0010))
}

// WriteABCDIRQSENS2 writes Serial GPIO ABCD interrupt sensitivity type 2 (GPIO510). Per-bit: 0=single-edge or level, 1=dual-edge trigger.
func (p *SgpioV1SGPIO) WriteABCDIRQSENS2(val uint32) {
    reg.Write(uint32(p.Base)+0x0010, uint32(val))
}

// ReadABCDIRQSTATUS reads Serial GPIO ABCD interrupt status (GPIO514). Write-1-to-clear per bit. 1=interrupt pending for that pin.
func (p *SgpioV1SGPIO) ReadABCDIRQSTATUS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0014))
}

// WriteABCDIRQSTATUS writes Serial GPIO ABCD interrupt status (GPIO514). Write-1-to-clear per bit. 1=interrupt pending for that pin.
func (p *SgpioV1SGPIO) WriteABCDIRQSTATUS(val uint32) {
    reg.Write(uint32(p.Base)+0x0014, uint32(val))
}

// ReadABCDWDTTOL reads Serial GPIO ABCD WDT reset tolerant (GPIO518). Per-bit: 1=preserve output data through WDT reset, 0=cleared by WDT.
func (p *SgpioV1SGPIO) ReadABCDWDTTOL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0018))
}

// WriteABCDWDTTOL writes Serial GPIO ABCD WDT reset tolerant (GPIO518). Per-bit: 1=preserve output data through WDT reset, 0=cleared by WDT.
func (p *SgpioV1SGPIO) WriteABCDWDTTOL(val uint32) {
    reg.Write(uint32(p.Base)+0x0018, uint32(val))
}

// ReadEFGHDATA reads Serial GPIO EFGH data (GPIO51C). E=bits[7:0], F=[15:8], G=[23:16], H=[31:24].
func (p *SgpioV1SGPIO) ReadEFGHDATA() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x001c))
}

// WriteEFGHDATA writes Serial GPIO EFGH data (GPIO51C). E=bits[7:0], F=[15:8], G=[23:16], H=[31:24].
func (p *SgpioV1SGPIO) WriteEFGHDATA(val uint32) {
    reg.Write(uint32(p.Base)+0x001c, uint32(val))
}

// ReadEFGHIRQEN reads Serial GPIO EFGH interrupt enable (GPIO520).
func (p *SgpioV1SGPIO) ReadEFGHIRQEN() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0020))
}

// WriteEFGHIRQEN writes Serial GPIO EFGH interrupt enable (GPIO520).
func (p *SgpioV1SGPIO) WriteEFGHIRQEN(val uint32) {
    reg.Write(uint32(p.Base)+0x0020, uint32(val))
}

// ReadEFGHIRQSENS0 reads Serial GPIO EFGH interrupt sensitivity type 0 (GPIO524).
func (p *SgpioV1SGPIO) ReadEFGHIRQSENS0() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0024))
}

// WriteEFGHIRQSENS0 writes Serial GPIO EFGH interrupt sensitivity type 0 (GPIO524).
func (p *SgpioV1SGPIO) WriteEFGHIRQSENS0(val uint32) {
    reg.Write(uint32(p.Base)+0x0024, uint32(val))
}

// ReadEFGHIRQSENS1 reads Serial GPIO EFGH interrupt sensitivity type 1 (GPIO528).
func (p *SgpioV1SGPIO) ReadEFGHIRQSENS1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0028))
}

// WriteEFGHIRQSENS1 writes Serial GPIO EFGH interrupt sensitivity type 1 (GPIO528).
func (p *SgpioV1SGPIO) WriteEFGHIRQSENS1(val uint32) {
    reg.Write(uint32(p.Base)+0x0028, uint32(val))
}

// ReadEFGHIRQSENS2 reads Serial GPIO EFGH interrupt sensitivity type 2 (GPIO52C).
func (p *SgpioV1SGPIO) ReadEFGHIRQSENS2() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x002c))
}

// WriteEFGHIRQSENS2 writes Serial GPIO EFGH interrupt sensitivity type 2 (GPIO52C).
func (p *SgpioV1SGPIO) WriteEFGHIRQSENS2(val uint32) {
    reg.Write(uint32(p.Base)+0x002c, uint32(val))
}

// ReadEFGHIRQSTATUS reads Serial GPIO EFGH interrupt status (GPIO530). Write-1-to-clear.
func (p *SgpioV1SGPIO) ReadEFGHIRQSTATUS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0030))
}

// WriteEFGHIRQSTATUS writes Serial GPIO EFGH interrupt status (GPIO530). Write-1-to-clear.
func (p *SgpioV1SGPIO) WriteEFGHIRQSTATUS(val uint32) {
    reg.Write(uint32(p.Base)+0x0030, uint32(val))
}

// ReadEFGHWDTTOL reads Serial GPIO EFGH WDT reset tolerant (GPIO534).
func (p *SgpioV1SGPIO) ReadEFGHWDTTOL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0034))
}

// WriteEFGHWDTTOL writes Serial GPIO EFGH WDT reset tolerant (GPIO534).
func (p *SgpioV1SGPIO) WriteEFGHWDTTOL(val uint32) {
    reg.Write(uint32(p.Base)+0x0034, uint32(val))
}

// ReadIJKLDATA reads Serial GPIO IJKL data (GPIO538). I=bits[7:0], J=[15:8], K=[23:16], L=[31:24].
func (p *SgpioV1SGPIO) ReadIJKLDATA() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0038))
}

// WriteIJKLDATA writes Serial GPIO IJKL data (GPIO538). I=bits[7:0], J=[15:8], K=[23:16], L=[31:24].
func (p *SgpioV1SGPIO) WriteIJKLDATA(val uint32) {
    reg.Write(uint32(p.Base)+0x0038, uint32(val))
}

// ReadIJKLIRQEN reads Serial GPIO IJKL interrupt enable (GPIO53C).
func (p *SgpioV1SGPIO) ReadIJKLIRQEN() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x003c))
}

// WriteIJKLIRQEN writes Serial GPIO IJKL interrupt enable (GPIO53C).
func (p *SgpioV1SGPIO) WriteIJKLIRQEN(val uint32) {
    reg.Write(uint32(p.Base)+0x003c, uint32(val))
}

// ReadIJKLIRQSENS0 reads Serial GPIO IJKL interrupt sensitivity type 0 (GPIO540).
func (p *SgpioV1SGPIO) ReadIJKLIRQSENS0() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0040))
}

// WriteIJKLIRQSENS0 writes Serial GPIO IJKL interrupt sensitivity type 0 (GPIO540).
func (p *SgpioV1SGPIO) WriteIJKLIRQSENS0(val uint32) {
    reg.Write(uint32(p.Base)+0x0040, uint32(val))
}

// ReadIJKLIRQSENS1 reads Serial GPIO IJKL interrupt sensitivity type 1 (GPIO544).
func (p *SgpioV1SGPIO) ReadIJKLIRQSENS1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0044))
}

// WriteIJKLIRQSENS1 writes Serial GPIO IJKL interrupt sensitivity type 1 (GPIO544).
func (p *SgpioV1SGPIO) WriteIJKLIRQSENS1(val uint32) {
    reg.Write(uint32(p.Base)+0x0044, uint32(val))
}

// ReadIJKLIRQSENS2 reads Serial GPIO IJKL interrupt sensitivity type 2 (GPIO548).
func (p *SgpioV1SGPIO) ReadIJKLIRQSENS2() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0048))
}

// WriteIJKLIRQSENS2 writes Serial GPIO IJKL interrupt sensitivity type 2 (GPIO548).
func (p *SgpioV1SGPIO) WriteIJKLIRQSENS2(val uint32) {
    reg.Write(uint32(p.Base)+0x0048, uint32(val))
}

// ReadIJKLIRQSTATUS reads Serial GPIO IJKL interrupt status (GPIO54C). Write-1-to-clear.
func (p *SgpioV1SGPIO) ReadIJKLIRQSTATUS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x004c))
}

// WriteIJKLIRQSTATUS writes Serial GPIO IJKL interrupt status (GPIO54C). Write-1-to-clear.
func (p *SgpioV1SGPIO) WriteIJKLIRQSTATUS(val uint32) {
    reg.Write(uint32(p.Base)+0x004c, uint32(val))
}

// ReadIJKLWDTTOL reads Serial GPIO IJKL WDT reset tolerant (GPIO550).
func (p *SgpioV1SGPIO) ReadIJKLWDTTOL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0050))
}

// WriteIJKLWDTTOL writes Serial GPIO IJKL WDT reset tolerant (GPIO550).
func (p *SgpioV1SGPIO) WriteIJKLWDTTOL(val uint32) {
    reg.Write(uint32(p.Base)+0x0050, uint32(val))
}

// ReadSGPIOCTRL reads Serial GPIO master configuration register (GPIO554). Controls enable, PIN_COUNT (bytes to shift per cycle: 1–16 = 8–128 bits), and CLK_DIV (clock divider for SGPMCLK = PCLK / (2 × (CLK_DIV + 1))).
func (p *SgpioV1SGPIO) ReadSGPIOCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0054))
}

// WriteSGPIOCTRL writes Serial GPIO master configuration register (GPIO554). Controls enable, PIN_COUNT (bytes to shift per cycle: 1–16 = 8–128 bits), and CLK_DIV (clock divider for SGPMCLK = PCLK / (2 × (CLK_DIV + 1))).
func (p *SgpioV1SGPIO) WriteSGPIOCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x0054, uint32(val))
}

// ReadABCDINPUTMASK reads Serial GPIO ABCD input mask (GPIO558). Per-bit: 1=freeze that bit's captured input (do not update from shift register).
func (p *SgpioV1SGPIO) ReadABCDINPUTMASK() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0058))
}

// WriteABCDINPUTMASK writes Serial GPIO ABCD input mask (GPIO558). Per-bit: 1=freeze that bit's captured input (do not update from shift register).
func (p *SgpioV1SGPIO) WriteABCDINPUTMASK(val uint32) {
    reg.Write(uint32(p.Base)+0x0058, uint32(val))
}

// ReadEFGHINPUTMASK reads Serial GPIO EFGH input mask (GPIO55C).
func (p *SgpioV1SGPIO) ReadEFGHINPUTMASK() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x005c))
}

// WriteEFGHINPUTMASK writes Serial GPIO EFGH input mask (GPIO55C).
func (p *SgpioV1SGPIO) WriteEFGHINPUTMASK(val uint32) {
    reg.Write(uint32(p.Base)+0x005c, uint32(val))
}

// ReadIJKLINPUTMASK reads Serial GPIO IJKL input mask (GPIO560).
func (p *SgpioV1SGPIO) ReadIJKLINPUTMASK() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0060))
}

// WriteIJKLINPUTMASK writes Serial GPIO IJKL input mask (GPIO560).
func (p *SgpioV1SGPIO) WriteIJKLINPUTMASK(val uint32) {
    reg.Write(uint32(p.Base)+0x0060, uint32(val))
}

// ReadMNOPINPUTMASK reads Serial GPIO MNOP input mask (GPIO564).
func (p *SgpioV1SGPIO) ReadMNOPINPUTMASK() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0064))
}

// WriteMNOPINPUTMASK writes Serial GPIO MNOP input mask (GPIO564).
func (p *SgpioV1SGPIO) WriteMNOPINPUTMASK(val uint32) {
    reg.Write(uint32(p.Base)+0x0064, uint32(val))
}

// ReadABCDDATAREAD reads Serial GPIO ABCD data read (GPIO570). Read-only mirror of last ABCD_DATA driven.
func (p *SgpioV1SGPIO) ReadABCDDATAREAD() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0070))
}

// WriteABCDDATAREAD writes Serial GPIO ABCD data read (GPIO570). Read-only mirror of last ABCD_DATA driven.
func (p *SgpioV1SGPIO) WriteABCDDATAREAD(val uint32) {
    reg.Write(uint32(p.Base)+0x0070, uint32(val))
}

// ReadEFGHDATAREAD reads Serial GPIO EFGH data read (GPIO574). Read-only mirror of EFGH_DATA.
func (p *SgpioV1SGPIO) ReadEFGHDATAREAD() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0074))
}

// WriteEFGHDATAREAD writes Serial GPIO EFGH data read (GPIO574). Read-only mirror of EFGH_DATA.
func (p *SgpioV1SGPIO) WriteEFGHDATAREAD(val uint32) {
    reg.Write(uint32(p.Base)+0x0074, uint32(val))
}

// ReadIJKLDATAREAD reads Serial GPIO IJKL data read (GPIO578). Read-only mirror of IJKL_DATA.
func (p *SgpioV1SGPIO) ReadIJKLDATAREAD() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0078))
}

// WriteIJKLDATAREAD writes Serial GPIO IJKL data read (GPIO578). Read-only mirror of IJKL_DATA.
func (p *SgpioV1SGPIO) WriteIJKLDATAREAD(val uint32) {
    reg.Write(uint32(p.Base)+0x0078, uint32(val))
}

// ReadMNOPDATAREAD reads Serial GPIO MNOP data read (GPIO57C). Read-only mirror of MNOP_DATA.
func (p *SgpioV1SGPIO) ReadMNOPDATAREAD() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x007c))
}

// WriteMNOPDATAREAD writes Serial GPIO MNOP data read (GPIO57C). Read-only mirror of MNOP_DATA.
func (p *SgpioV1SGPIO) WriteMNOPDATAREAD(val uint32) {
    reg.Write(uint32(p.Base)+0x007c, uint32(val))
}

// ReadMNOPDATA reads Serial GPIO MNOP data (GPIO590). M=bits[7:0], N=[15:8], O=[23:16], P=[31:24].
func (p *SgpioV1SGPIO) ReadMNOPDATA() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0090))
}

// WriteMNOPDATA writes Serial GPIO MNOP data (GPIO590). M=bits[7:0], N=[15:8], O=[23:16], P=[31:24].
func (p *SgpioV1SGPIO) WriteMNOPDATA(val uint32) {
    reg.Write(uint32(p.Base)+0x0090, uint32(val))
}

// ReadMNOPIRQEN reads Serial GPIO MNOP interrupt enable (GPIO594).
func (p *SgpioV1SGPIO) ReadMNOPIRQEN() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0094))
}

// WriteMNOPIRQEN writes Serial GPIO MNOP interrupt enable (GPIO594).
func (p *SgpioV1SGPIO) WriteMNOPIRQEN(val uint32) {
    reg.Write(uint32(p.Base)+0x0094, uint32(val))
}

// ReadMNOPIRQSENS0 reads Serial GPIO MNOP interrupt sensitivity type 0 (GPIO598).
func (p *SgpioV1SGPIO) ReadMNOPIRQSENS0() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0098))
}

// WriteMNOPIRQSENS0 writes Serial GPIO MNOP interrupt sensitivity type 0 (GPIO598).
func (p *SgpioV1SGPIO) WriteMNOPIRQSENS0(val uint32) {
    reg.Write(uint32(p.Base)+0x0098, uint32(val))
}

// ReadMNOPIRQSENS1 reads Serial GPIO MNOP interrupt sensitivity type 1 (GPIO59C).
func (p *SgpioV1SGPIO) ReadMNOPIRQSENS1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x009c))
}

// WriteMNOPIRQSENS1 writes Serial GPIO MNOP interrupt sensitivity type 1 (GPIO59C).
func (p *SgpioV1SGPIO) WriteMNOPIRQSENS1(val uint32) {
    reg.Write(uint32(p.Base)+0x009c, uint32(val))
}

// ReadMNOPIRQSENS2 reads Serial GPIO MNOP interrupt sensitivity type 2 (GPIO5A0).
func (p *SgpioV1SGPIO) ReadMNOPIRQSENS2() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00a0))
}

// WriteMNOPIRQSENS2 writes Serial GPIO MNOP interrupt sensitivity type 2 (GPIO5A0).
func (p *SgpioV1SGPIO) WriteMNOPIRQSENS2(val uint32) {
    reg.Write(uint32(p.Base)+0x00a0, uint32(val))
}

// ReadMNOPIRQSTATUS reads Serial GPIO MNOP interrupt status (GPIO5A4). Write-1-to-clear.
func (p *SgpioV1SGPIO) ReadMNOPIRQSTATUS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00a4))
}

// WriteMNOPIRQSTATUS writes Serial GPIO MNOP interrupt status (GPIO5A4). Write-1-to-clear.
func (p *SgpioV1SGPIO) WriteMNOPIRQSTATUS(val uint32) {
    reg.Write(uint32(p.Base)+0x00a4, uint32(val))
}

// ReadMNOPWDTTOL reads Serial GPIO MNOP WDT reset tolerant (GPIO5A8).
func (p *SgpioV1SGPIO) ReadMNOPWDTTOL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00a8))
}

// WriteMNOPWDTTOL writes Serial GPIO MNOP WDT reset tolerant (GPIO5A8).
func (p *SgpioV1SGPIO) WriteMNOPWDTTOL(val uint32) {
    reg.Write(uint32(p.Base)+0x00a8, uint32(val))
}

