// Code generated by chiptool; DO NOT EDIT.

package pac

import "github.com/kyanitecomputer/aspeed-go/reg"

// SpipfV1SPIPF ASPEED SPI Passthrough Filter / QSPI Monitor (SPIPF). 4 instances, base = 0x7E791000, stride = 0x1000. Monitors SPI bus traffic and filters commands/addresses.
type SpipfV1SPIPF struct {
    Base uintptr
}

// ReadENGINECTRL reads Engine control register (SPIPF000). Enable/disable filter and passthrough, select SPI mode, configure block behavior, FIFO management, debounce, and address table selection (write 0x57/'W' or 0x52/'R' to bits[31:24]).
func (p *SpipfV1SPIPF) ReadENGINECTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0000))
}

// WriteENGINECTRL writes Engine control register (SPIPF000). Enable/disable filter and passthrough, select SPI mode, configure block behavior, FIFO management, debounce, and address table selection (write 0x57/'W' or 0x52/'R' to bits[31:24]).
func (p *SpipfV1SPIPF) WriteENGINECTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x0000, uint32(val))
}

// ReadIRQCTRL reads Interrupt enable and status register (SPIPF004). Enable interrupts for read-block, write-block, and command-block events. Write 1 to clear status bits.
func (p *SpipfV1SPIPF) ReadIRQCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0004))
}

// WriteIRQCTRL writes Interrupt enable and status register (SPIPF004). Enable interrupts for read-block, write-block, and command-block events. Write 1 to clear status bits.
func (p *SpipfV1SPIPF) WriteIRQCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x0004, uint32(val))
}

// ReadEAR reads Extended Address Register readback (SPIPF008, read-only). Current EAR value as received from SPI master. Used for 4-byte address decoding when EAR-based addressing is active.
func (p *SpipfV1SPIPF) ReadEAR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0008))
}

// WriteEAR writes Extended Address Register readback (SPIPF008, read-only). Current EAR value as received from SPI master. Used for 4-byte address decoding when EAR-based addressing is active.
func (p *SpipfV1SPIPF) WriteEAR(val uint32) {
    reg.Write(uint32(p.Base)+0x0008, uint32(val))
}

// ReadBLOCKFIFODATA reads Blocked transaction FIFO read port (SPIPF00C, read-only). Each read pops one 32-bit entry from the FIFO. BLOCK_FIFO_LEN in ENGINE_CTRL shows current occupancy.
func (p *SpipfV1SPIPF) ReadBLOCKFIFODATA() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x000c))
}

// WriteBLOCKFIFODATA writes Blocked transaction FIFO read port (SPIPF00C, read-only). Each read pops one 32-bit entry from the FIFO. BLOCK_FIFO_LEN in ENGINE_CTRL shows current occupancy.
func (p *SpipfV1SPIPF) WriteBLOCKFIFODATA(val uint32) {
    reg.Write(uint32(p.Base)+0x000c, uint32(val))
}

// ReadDMABASE reads Block-log DMA buffer base address (SPIPF010, 4-byte aligned).
func (p *SpipfV1SPIPF) ReadDMABASE() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0010))
}

// WriteDMABASE writes Block-log DMA buffer base address (SPIPF010, 4-byte aligned).
func (p *SpipfV1SPIPF) WriteDMABASE(val uint32) {
    reg.Write(uint32(p.Base)+0x0010, uint32(val))
}

// ReadDMASIZE reads Block-log DMA buffer size and enable (SPIPF014).
func (p *SpipfV1SPIPF) ReadDMASIZE() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0014))
}

// WriteDMASIZE writes Block-log DMA buffer size and enable (SPIPF014).
func (p *SpipfV1SPIPF) WriteDMASIZE(val uint32) {
    reg.Write(uint32(p.Base)+0x0014, uint32(val))
}

// ReadDMAWRPTR reads Block-log DMA write pointer (SPIPF018, hardware-managed, read-only).
func (p *SpipfV1SPIPF) ReadDMAWRPTR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0018))
}

// WriteDMAWRPTR writes Block-log DMA write pointer (SPIPF018, hardware-managed, read-only).
func (p *SpipfV1SPIPF) WriteDMAWRPTR(val uint32) {
    reg.Write(uint32(p.Base)+0x0018, uint32(val))
}

// ReadWRITEDISABLE reads Write disable register (SPIPF07C). All fields are write-1-only (sticky lock). Once set, the corresponding register is permanently write-locked until reset.
func (p *SpipfV1SPIPF) ReadWRITEDISABLE() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x007c))
}

// WriteWRITEDISABLE writes Write disable register (SPIPF07C). All fields are write-1-only (sticky lock). Once set, the corresponding register is permanently write-locked until reset.
func (p *SpipfV1SPIPF) WriteWRITEDISABLE(val uint32) {
    reg.Write(uint32(p.Base)+0x007c, uint32(val))
}

// ReadCMDTABLE0 reads Command table entry 0 (predefined: EN4B — enter 4-byte address mode).
func (p *SpipfV1SPIPF) ReadCMDTABLE0() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0080))
}

// WriteCMDTABLE0 writes Command table entry 0 (predefined: EN4B — enter 4-byte address mode).
func (p *SpipfV1SPIPF) WriteCMDTABLE0(val uint32) {
    reg.Write(uint32(p.Base)+0x0080, uint32(val))
}

// ReadCMDTABLE1 reads Command table entry 1 (predefined: EX4B — exit 4-byte mode).
func (p *SpipfV1SPIPF) ReadCMDTABLE1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0084))
}

// WriteCMDTABLE1 writes Command table entry 1 (predefined: EX4B — exit 4-byte mode).
func (p *SpipfV1SPIPF) WriteCMDTABLE1(val uint32) {
    reg.Write(uint32(p.Base)+0x0084, uint32(val))
}

// ReadCMDTABLE2 reads Command table entry 2 (predefined: EQIO — enter QPI mode).
func (p *SpipfV1SPIPF) ReadCMDTABLE2() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0088))
}

// WriteCMDTABLE2 writes Command table entry 2 (predefined: EQIO — enter QPI mode).
func (p *SpipfV1SPIPF) WriteCMDTABLE2(val uint32) {
    reg.Write(uint32(p.Base)+0x0088, uint32(val))
}

// ReadCMDTABLE3 reads Command table entry 3 (predefined: RSTQIO — exit QPI mode).
func (p *SpipfV1SPIPF) ReadCMDTABLE3() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x008c))
}

// WriteCMDTABLE3 writes Command table entry 3 (predefined: RSTQIO — exit QPI mode).
func (p *SpipfV1SPIPF) WriteCMDTABLE3(val uint32) {
    reg.Write(uint32(p.Base)+0x008c, uint32(val))
}

// ReadCMDTABLE4 reads Command table entry 4 — general purpose.
func (p *SpipfV1SPIPF) ReadCMDTABLE4() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0090))
}

// WriteCMDTABLE4 writes Command table entry 4 — general purpose.
func (p *SpipfV1SPIPF) WriteCMDTABLE4(val uint32) {
    reg.Write(uint32(p.Base)+0x0090, uint32(val))
}

// ReadCMDTABLE5 reads Command table entry 5 — general purpose.
func (p *SpipfV1SPIPF) ReadCMDTABLE5() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0094))
}

// WriteCMDTABLE5 writes Command table entry 5 — general purpose.
func (p *SpipfV1SPIPF) WriteCMDTABLE5(val uint32) {
    reg.Write(uint32(p.Base)+0x0094, uint32(val))
}

// ReadCMDTABLE6 reads Command table entry 6 — general purpose.
func (p *SpipfV1SPIPF) ReadCMDTABLE6() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0098))
}

// WriteCMDTABLE6 writes Command table entry 6 — general purpose.
func (p *SpipfV1SPIPF) WriteCMDTABLE6(val uint32) {
    reg.Write(uint32(p.Base)+0x0098, uint32(val))
}

// ReadCMDTABLE7 reads Command table entry 7 — general purpose.
func (p *SpipfV1SPIPF) ReadCMDTABLE7() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x009c))
}

// WriteCMDTABLE7 writes Command table entry 7 — general purpose.
func (p *SpipfV1SPIPF) WriteCMDTABLE7(val uint32) {
    reg.Write(uint32(p.Base)+0x009c, uint32(val))
}

// ReadCMDTABLE8 reads Command table entry 8 — general purpose.
func (p *SpipfV1SPIPF) ReadCMDTABLE8() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00a0))
}

// WriteCMDTABLE8 writes Command table entry 8 — general purpose.
func (p *SpipfV1SPIPF) WriteCMDTABLE8(val uint32) {
    reg.Write(uint32(p.Base)+0x00a0, uint32(val))
}

// ReadCMDTABLE9 reads Command table entry 9 — general purpose.
func (p *SpipfV1SPIPF) ReadCMDTABLE9() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00a4))
}

// WriteCMDTABLE9 writes Command table entry 9 — general purpose.
func (p *SpipfV1SPIPF) WriteCMDTABLE9(val uint32) {
    reg.Write(uint32(p.Base)+0x00a4, uint32(val))
}

// ReadCMDTABLE10 reads Command table entry 10 — general purpose.
func (p *SpipfV1SPIPF) ReadCMDTABLE10() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00a8))
}

// WriteCMDTABLE10 writes Command table entry 10 — general purpose.
func (p *SpipfV1SPIPF) WriteCMDTABLE10(val uint32) {
    reg.Write(uint32(p.Base)+0x00a8, uint32(val))
}

// ReadCMDTABLE11 reads Command table entry 11 — general purpose.
func (p *SpipfV1SPIPF) ReadCMDTABLE11() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00ac))
}

// WriteCMDTABLE11 writes Command table entry 11 — general purpose.
func (p *SpipfV1SPIPF) WriteCMDTABLE11(val uint32) {
    reg.Write(uint32(p.Base)+0x00ac, uint32(val))
}

// ReadCMDTABLE12 reads Command table entry 12 — general purpose.
func (p *SpipfV1SPIPF) ReadCMDTABLE12() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00b0))
}

// WriteCMDTABLE12 writes Command table entry 12 — general purpose.
func (p *SpipfV1SPIPF) WriteCMDTABLE12(val uint32) {
    reg.Write(uint32(p.Base)+0x00b0, uint32(val))
}

// ReadCMDTABLE13 reads Command table entry 13 — general purpose.
func (p *SpipfV1SPIPF) ReadCMDTABLE13() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00b4))
}

// WriteCMDTABLE13 writes Command table entry 13 — general purpose.
func (p *SpipfV1SPIPF) WriteCMDTABLE13(val uint32) {
    reg.Write(uint32(p.Base)+0x00b4, uint32(val))
}

// ReadCMDTABLE14 reads Command table entry 14 — general purpose.
func (p *SpipfV1SPIPF) ReadCMDTABLE14() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00b8))
}

// WriteCMDTABLE14 writes Command table entry 14 — general purpose.
func (p *SpipfV1SPIPF) WriteCMDTABLE14(val uint32) {
    reg.Write(uint32(p.Base)+0x00b8, uint32(val))
}

// ReadCMDTABLE15 reads Command table entry 15 — general purpose.
func (p *SpipfV1SPIPF) ReadCMDTABLE15() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00bc))
}

// WriteCMDTABLE15 writes Command table entry 15 — general purpose.
func (p *SpipfV1SPIPF) WriteCMDTABLE15(val uint32) {
    reg.Write(uint32(p.Base)+0x00bc, uint32(val))
}

// ReadCMDTABLE16 reads Command table entry 16 — general purpose.
func (p *SpipfV1SPIPF) ReadCMDTABLE16() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00c0))
}

// WriteCMDTABLE16 writes Command table entry 16 — general purpose.
func (p *SpipfV1SPIPF) WriteCMDTABLE16(val uint32) {
    reg.Write(uint32(p.Base)+0x00c0, uint32(val))
}

// ReadCMDTABLE17 reads Command table entry 17 — general purpose.
func (p *SpipfV1SPIPF) ReadCMDTABLE17() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00c4))
}

// WriteCMDTABLE17 writes Command table entry 17 — general purpose.
func (p *SpipfV1SPIPF) WriteCMDTABLE17(val uint32) {
    reg.Write(uint32(p.Base)+0x00c4, uint32(val))
}

// ReadCMDTABLE18 reads Command table entry 18 — general purpose.
func (p *SpipfV1SPIPF) ReadCMDTABLE18() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00c8))
}

// WriteCMDTABLE18 writes Command table entry 18 — general purpose.
func (p *SpipfV1SPIPF) WriteCMDTABLE18(val uint32) {
    reg.Write(uint32(p.Base)+0x00c8, uint32(val))
}

// ReadCMDTABLE19 reads Command table entry 19 (predefined: WREAR — write extended address register).
func (p *SpipfV1SPIPF) ReadCMDTABLE19() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00cc))
}

// WriteCMDTABLE19 writes Command table entry 19 (predefined: WREAR — write extended address register).
func (p *SpipfV1SPIPF) WriteCMDTABLE19(val uint32) {
    reg.Write(uint32(p.Base)+0x00cc, uint32(val))
}

// ReadCMDTABLE20 reads Command table entry 20 — general purpose.
func (p *SpipfV1SPIPF) ReadCMDTABLE20() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00d0))
}

// WriteCMDTABLE20 writes Command table entry 20 — general purpose.
func (p *SpipfV1SPIPF) WriteCMDTABLE20(val uint32) {
    reg.Write(uint32(p.Base)+0x00d0, uint32(val))
}

// ReadCMDTABLE21 reads Command table entry 21 — general purpose.
func (p *SpipfV1SPIPF) ReadCMDTABLE21() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00d4))
}

// WriteCMDTABLE21 writes Command table entry 21 — general purpose.
func (p *SpipfV1SPIPF) WriteCMDTABLE21(val uint32) {
    reg.Write(uint32(p.Base)+0x00d4, uint32(val))
}

// ReadCMDTABLE22 reads Command table entry 22 — general purpose.
func (p *SpipfV1SPIPF) ReadCMDTABLE22() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00d8))
}

// WriteCMDTABLE22 writes Command table entry 22 — general purpose.
func (p *SpipfV1SPIPF) WriteCMDTABLE22(val uint32) {
    reg.Write(uint32(p.Base)+0x00d8, uint32(val))
}

// ReadCMDTABLE23 reads Command table entry 23 — general purpose.
func (p *SpipfV1SPIPF) ReadCMDTABLE23() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00dc))
}

// WriteCMDTABLE23 writes Command table entry 23 — general purpose.
func (p *SpipfV1SPIPF) WriteCMDTABLE23(val uint32) {
    reg.Write(uint32(p.Base)+0x00dc, uint32(val))
}

// ReadCMDTABLE24 reads Command table entry 24 — general purpose.
func (p *SpipfV1SPIPF) ReadCMDTABLE24() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00e0))
}

// WriteCMDTABLE24 writes Command table entry 24 — general purpose.
func (p *SpipfV1SPIPF) WriteCMDTABLE24(val uint32) {
    reg.Write(uint32(p.Base)+0x00e0, uint32(val))
}

// ReadCMDTABLE25 reads Command table entry 25 — general purpose.
func (p *SpipfV1SPIPF) ReadCMDTABLE25() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00e4))
}

// WriteCMDTABLE25 writes Command table entry 25 — general purpose.
func (p *SpipfV1SPIPF) WriteCMDTABLE25(val uint32) {
    reg.Write(uint32(p.Base)+0x00e4, uint32(val))
}

// ReadCMDTABLE26 reads Command table entry 26 — general purpose.
func (p *SpipfV1SPIPF) ReadCMDTABLE26() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00e8))
}

// WriteCMDTABLE26 writes Command table entry 26 — general purpose.
func (p *SpipfV1SPIPF) WriteCMDTABLE26(val uint32) {
    reg.Write(uint32(p.Base)+0x00e8, uint32(val))
}

// ReadCMDTABLE27 reads Command table entry 27 — general purpose.
func (p *SpipfV1SPIPF) ReadCMDTABLE27() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00ec))
}

// WriteCMDTABLE27 writes Command table entry 27 — general purpose.
func (p *SpipfV1SPIPF) WriteCMDTABLE27(val uint32) {
    reg.Write(uint32(p.Base)+0x00ec, uint32(val))
}

// ReadCMDTABLE28 reads Command table entry 28 — general purpose.
func (p *SpipfV1SPIPF) ReadCMDTABLE28() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00f0))
}

// WriteCMDTABLE28 writes Command table entry 28 — general purpose.
func (p *SpipfV1SPIPF) WriteCMDTABLE28(val uint32) {
    reg.Write(uint32(p.Base)+0x00f0, uint32(val))
}

// ReadCMDTABLE29 reads Command table entry 29 — general purpose.
func (p *SpipfV1SPIPF) ReadCMDTABLE29() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00f4))
}

// WriteCMDTABLE29 writes Command table entry 29 — general purpose.
func (p *SpipfV1SPIPF) WriteCMDTABLE29(val uint32) {
    reg.Write(uint32(p.Base)+0x00f4, uint32(val))
}

// ReadCMDTABLE30 reads Command table entry 30 — general purpose.
func (p *SpipfV1SPIPF) ReadCMDTABLE30() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00f8))
}

// WriteCMDTABLE30 writes Command table entry 30 — general purpose.
func (p *SpipfV1SPIPF) WriteCMDTABLE30(val uint32) {
    reg.Write(uint32(p.Base)+0x00f8, uint32(val))
}

// ReadCMDTABLE31 reads Command table entry 31 — general purpose.
func (p *SpipfV1SPIPF) ReadCMDTABLE31() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00fc))
}

// WriteCMDTABLE31 writes Command table entry 31 — general purpose.
func (p *SpipfV1SPIPF) WriteCMDTABLE31(val uint32) {
    reg.Write(uint32(p.Base)+0x00fc, uint32(val))
}

// ReadADDRTABLE0 reads Address table entry 0 — controls flash regions 0x0000_0000 to 0x0007_FFFF (512 KB, 1 bit per 16 KB).
func (p *SpipfV1SPIPF) ReadADDRTABLE0() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0100))
}

// WriteADDRTABLE0 writes Address table entry 0 — controls flash regions 0x0000_0000 to 0x0007_FFFF (512 KB, 1 bit per 16 KB).
func (p *SpipfV1SPIPF) WriteADDRTABLE0(val uint32) {
    reg.Write(uint32(p.Base)+0x0100, uint32(val))
}

// ReadADDRTABLE1 reads Address table entry 1 — regions 0x0008_0000 to 0x000F_FFFF.
func (p *SpipfV1SPIPF) ReadADDRTABLE1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0104))
}

// WriteADDRTABLE1 writes Address table entry 1 — regions 0x0008_0000 to 0x000F_FFFF.
func (p *SpipfV1SPIPF) WriteADDRTABLE1(val uint32) {
    reg.Write(uint32(p.Base)+0x0104, uint32(val))
}

// ReadADDRTABLE2 reads Address table entry 2 — regions 0x0010_0000 to 0x0017_FFFF.
func (p *SpipfV1SPIPF) ReadADDRTABLE2() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0108))
}

// WriteADDRTABLE2 writes Address table entry 2 — regions 0x0010_0000 to 0x0017_FFFF.
func (p *SpipfV1SPIPF) WriteADDRTABLE2(val uint32) {
    reg.Write(uint32(p.Base)+0x0108, uint32(val))
}

// ReadADDRTABLE3 reads Address table entry 3 — regions 0x0018_0000 to 0x001F_FFFF.
func (p *SpipfV1SPIPF) ReadADDRTABLE3() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x010c))
}

// WriteADDRTABLE3 writes Address table entry 3 — regions 0x0018_0000 to 0x001F_FFFF.
func (p *SpipfV1SPIPF) WriteADDRTABLE3(val uint32) {
    reg.Write(uint32(p.Base)+0x010c, uint32(val))
}

// ReadADDRTABLE4 reads Address table entry 4 — regions 0x0020_0000 to 0x0027_FFFF.
func (p *SpipfV1SPIPF) ReadADDRTABLE4() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0110))
}

// WriteADDRTABLE4 writes Address table entry 4 — regions 0x0020_0000 to 0x0027_FFFF.
func (p *SpipfV1SPIPF) WriteADDRTABLE4(val uint32) {
    reg.Write(uint32(p.Base)+0x0110, uint32(val))
}

// ReadADDRTABLE5 reads Address table entry 5 — regions 0x0028_0000 to 0x002F_FFFF.
func (p *SpipfV1SPIPF) ReadADDRTABLE5() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0114))
}

// WriteADDRTABLE5 writes Address table entry 5 — regions 0x0028_0000 to 0x002F_FFFF.
func (p *SpipfV1SPIPF) WriteADDRTABLE5(val uint32) {
    reg.Write(uint32(p.Base)+0x0114, uint32(val))
}

// ReadADDRTABLE6 reads Address table entry 6 — regions 0x0030_0000 to 0x0037_FFFF.
func (p *SpipfV1SPIPF) ReadADDRTABLE6() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0118))
}

// WriteADDRTABLE6 writes Address table entry 6 — regions 0x0030_0000 to 0x0037_FFFF.
func (p *SpipfV1SPIPF) WriteADDRTABLE6(val uint32) {
    reg.Write(uint32(p.Base)+0x0118, uint32(val))
}

// ReadADDRTABLE7 reads Address table entry 7 — regions 0x0038_0000 to 0x003F_FFFF.
func (p *SpipfV1SPIPF) ReadADDRTABLE7() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x011c))
}

// WriteADDRTABLE7 writes Address table entry 7 — regions 0x0038_0000 to 0x003F_FFFF.
func (p *SpipfV1SPIPF) WriteADDRTABLE7(val uint32) {
    reg.Write(uint32(p.Base)+0x011c, uint32(val))
}

// ReadADDRTABLE8 reads Address table entry 8 — regions 0x0040_0000 to 0x0047_FFFF.
func (p *SpipfV1SPIPF) ReadADDRTABLE8() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0120))
}

// WriteADDRTABLE8 writes Address table entry 8 — regions 0x0040_0000 to 0x0047_FFFF.
func (p *SpipfV1SPIPF) WriteADDRTABLE8(val uint32) {
    reg.Write(uint32(p.Base)+0x0120, uint32(val))
}

// ReadADDRTABLE9 reads Address table entry 9 — regions 0x0048_0000 to 0x004F_FFFF.
func (p *SpipfV1SPIPF) ReadADDRTABLE9() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0124))
}

// WriteADDRTABLE9 writes Address table entry 9 — regions 0x0048_0000 to 0x004F_FFFF.
func (p *SpipfV1SPIPF) WriteADDRTABLE9(val uint32) {
    reg.Write(uint32(p.Base)+0x0124, uint32(val))
}

// ReadADDRTABLE10 reads Address table entry 10 — regions 0x0050_0000 to 0x0057_FFFF.
func (p *SpipfV1SPIPF) ReadADDRTABLE10() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0128))
}

// WriteADDRTABLE10 writes Address table entry 10 — regions 0x0050_0000 to 0x0057_FFFF.
func (p *SpipfV1SPIPF) WriteADDRTABLE10(val uint32) {
    reg.Write(uint32(p.Base)+0x0128, uint32(val))
}

// ReadADDRTABLE11 reads Address table entry 11 — regions 0x0058_0000 to 0x005F_FFFF.
func (p *SpipfV1SPIPF) ReadADDRTABLE11() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x012c))
}

// WriteADDRTABLE11 writes Address table entry 11 — regions 0x0058_0000 to 0x005F_FFFF.
func (p *SpipfV1SPIPF) WriteADDRTABLE11(val uint32) {
    reg.Write(uint32(p.Base)+0x012c, uint32(val))
}

// ReadADDRTABLE12 reads Address table entry 12 — regions 0x0060_0000 to 0x0067_FFFF.
func (p *SpipfV1SPIPF) ReadADDRTABLE12() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0130))
}

// WriteADDRTABLE12 writes Address table entry 12 — regions 0x0060_0000 to 0x0067_FFFF.
func (p *SpipfV1SPIPF) WriteADDRTABLE12(val uint32) {
    reg.Write(uint32(p.Base)+0x0130, uint32(val))
}

// ReadADDRTABLE13 reads Address table entry 13 — regions 0x0068_0000 to 0x006F_FFFF.
func (p *SpipfV1SPIPF) ReadADDRTABLE13() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0134))
}

// WriteADDRTABLE13 writes Address table entry 13 — regions 0x0068_0000 to 0x006F_FFFF.
func (p *SpipfV1SPIPF) WriteADDRTABLE13(val uint32) {
    reg.Write(uint32(p.Base)+0x0134, uint32(val))
}

// ReadADDRTABLE14 reads Address table entry 14 — regions 0x0070_0000 to 0x0077_FFFF.
func (p *SpipfV1SPIPF) ReadADDRTABLE14() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0138))
}

// WriteADDRTABLE14 writes Address table entry 14 — regions 0x0070_0000 to 0x0077_FFFF.
func (p *SpipfV1SPIPF) WriteADDRTABLE14(val uint32) {
    reg.Write(uint32(p.Base)+0x0138, uint32(val))
}

// ReadADDRTABLE15 reads Address table entry 15 — regions 0x0078_0000 to 0x007F_FFFF.
func (p *SpipfV1SPIPF) ReadADDRTABLE15() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x013c))
}

// WriteADDRTABLE15 writes Address table entry 15 — regions 0x0078_0000 to 0x007F_FFFF.
func (p *SpipfV1SPIPF) WriteADDRTABLE15(val uint32) {
    reg.Write(uint32(p.Base)+0x013c, uint32(val))
}

