// Code generated by chiptool; DO NOT EDIT.

package pac

import "github.com/kyanitecomputer/aspeed-go/reg"

// TimerV1TIMER AST2600 hardware timer block. Base: 0x7E78_2000 (CM3 view).  8 × 32-bit countdown timers.
type TimerV1TIMER struct {
    Base uintptr
}

// ReadT1STATUS reads Timer 1 Counter Status (TMC00). Read-only current count.
func (p *TimerV1TIMER) ReadT1STATUS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0000))
}

// WriteT1STATUS writes Timer 1 Counter Status (TMC00). Read-only current count.
func (p *TimerV1TIMER) WriteT1STATUS(val uint32) {
    reg.Write(uint32(p.Base)+0x0000, uint32(val))
}

// ReadT1RELOAD reads Timer 1 Reload Value (TMC04). Loaded on enable or overflow.
func (p *TimerV1TIMER) ReadT1RELOAD() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0004))
}

// WriteT1RELOAD writes Timer 1 Reload Value (TMC04). Loaded on enable or overflow.
func (p *TimerV1TIMER) WriteT1RELOAD(val uint32) {
    reg.Write(uint32(p.Base)+0x0004, uint32(val))
}

// ReadT1MATCH1 reads Timer 1 First Match Register (TMC08).
func (p *TimerV1TIMER) ReadT1MATCH1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0008))
}

// WriteT1MATCH1 writes Timer 1 First Match Register (TMC08).
func (p *TimerV1TIMER) WriteT1MATCH1(val uint32) {
    reg.Write(uint32(p.Base)+0x0008, uint32(val))
}

// ReadT2STATUS reads Timer 2 Counter Status (TMC10).
func (p *TimerV1TIMER) ReadT2STATUS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0010))
}

// WriteT2STATUS writes Timer 2 Counter Status (TMC10).
func (p *TimerV1TIMER) WriteT2STATUS(val uint32) {
    reg.Write(uint32(p.Base)+0x0010, uint32(val))
}

// ReadT2RELOAD reads Timer 2 Reload Value (TMC14).
func (p *TimerV1TIMER) ReadT2RELOAD() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0014))
}

// WriteT2RELOAD writes Timer 2 Reload Value (TMC14).
func (p *TimerV1TIMER) WriteT2RELOAD(val uint32) {
    reg.Write(uint32(p.Base)+0x0014, uint32(val))
}

// ReadT2MATCH1 reads Timer 2 First Match Register (TMC18).
func (p *TimerV1TIMER) ReadT2MATCH1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0018))
}

// WriteT2MATCH1 writes Timer 2 First Match Register (TMC18).
func (p *TimerV1TIMER) WriteT2MATCH1(val uint32) {
    reg.Write(uint32(p.Base)+0x0018, uint32(val))
}

// ReadT3STATUS reads Timer 3 Counter Status (TMC20).
func (p *TimerV1TIMER) ReadT3STATUS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0020))
}

// WriteT3STATUS writes Timer 3 Counter Status (TMC20).
func (p *TimerV1TIMER) WriteT3STATUS(val uint32) {
    reg.Write(uint32(p.Base)+0x0020, uint32(val))
}

// ReadT3RELOAD reads Timer 3 Reload Value (TMC24).
func (p *TimerV1TIMER) ReadT3RELOAD() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0024))
}

// WriteT3RELOAD writes Timer 3 Reload Value (TMC24).
func (p *TimerV1TIMER) WriteT3RELOAD(val uint32) {
    reg.Write(uint32(p.Base)+0x0024, uint32(val))
}

// ReadT3MATCH1 reads Timer 3 First Match Register (TMC28).
func (p *TimerV1TIMER) ReadT3MATCH1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0028))
}

// WriteT3MATCH1 writes Timer 3 First Match Register (TMC28).
func (p *TimerV1TIMER) WriteT3MATCH1(val uint32) {
    reg.Write(uint32(p.Base)+0x0028, uint32(val))
}

// ReadCTRL reads Global Timer Control Register (TMC30). Write 1 to set specific bits; write 1 to TMC3C to clear. 4 bits per timer: [WDT_EN, OVF_INTR, CLK_SEL, EN], timer 1 in bits [3:0].
func (p *TimerV1TIMER) ReadCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0030))
}

// WriteCTRL writes Global Timer Control Register (TMC30). Write 1 to set specific bits; write 1 to TMC3C to clear. 4 bits per timer: [WDT_EN, OVF_INTR, CLK_SEL, EN], timer 1 in bits [3:0].
func (p *TimerV1TIMER) WriteCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x0030, uint32(val))
}

// ReadINTSTATUS reads Timer Interrupt Status Register (TMC34). RW1C. Bit N-1 set when timer N overflows and OVF_INTR is enabled. Clear by writing 1 to the bit.
func (p *TimerV1TIMER) ReadINTSTATUS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0034))
}

// WriteINTSTATUS writes Timer Interrupt Status Register (TMC34). RW1C. Bit N-1 set when timer N overflows and OVF_INTR is enabled. Clear by writing 1 to the bit.
func (p *TimerV1TIMER) WriteINTSTATUS(val uint32) {
    reg.Write(uint32(p.Base)+0x0034, uint32(val))
}

// ReadCTRLCLR reads TMC30 Clear Register (TMC3C). Write-only. Write 1 to a bit to clear the same bit in CTRL (TMC30).
func (p *TimerV1TIMER) ReadCTRLCLR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x003c))
}

// WriteCTRLCLR writes TMC30 Clear Register (TMC3C). Write-only. Write 1 to a bit to clear the same bit in CTRL (TMC30).
func (p *TimerV1TIMER) WriteCTRLCLR(val uint32) {
    reg.Write(uint32(p.Base)+0x003c, uint32(val))
}

// ReadT4STATUS reads Timer 4 Counter Status (TMC40).
func (p *TimerV1TIMER) ReadT4STATUS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0040))
}

// WriteT4STATUS writes Timer 4 Counter Status (TMC40).
func (p *TimerV1TIMER) WriteT4STATUS(val uint32) {
    reg.Write(uint32(p.Base)+0x0040, uint32(val))
}

// ReadT4RELOAD reads Timer 4 Reload Value (TMC44).
func (p *TimerV1TIMER) ReadT4RELOAD() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0044))
}

// WriteT4RELOAD writes Timer 4 Reload Value (TMC44).
func (p *TimerV1TIMER) WriteT4RELOAD(val uint32) {
    reg.Write(uint32(p.Base)+0x0044, uint32(val))
}

// ReadT4MATCH1 reads Timer 4 First Match Register (TMC48).
func (p *TimerV1TIMER) ReadT4MATCH1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0048))
}

// WriteT4MATCH1 writes Timer 4 First Match Register (TMC48).
func (p *TimerV1TIMER) WriteT4MATCH1(val uint32) {
    reg.Write(uint32(p.Base)+0x0048, uint32(val))
}

// ReadT5STATUS reads Timer 5 Counter Status (TMC50).
func (p *TimerV1TIMER) ReadT5STATUS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0050))
}

// WriteT5STATUS writes Timer 5 Counter Status (TMC50).
func (p *TimerV1TIMER) WriteT5STATUS(val uint32) {
    reg.Write(uint32(p.Base)+0x0050, uint32(val))
}

// ReadT5RELOAD reads Timer 5 Reload Value (TMC54).
func (p *TimerV1TIMER) ReadT5RELOAD() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0054))
}

// WriteT5RELOAD writes Timer 5 Reload Value (TMC54).
func (p *TimerV1TIMER) WriteT5RELOAD(val uint32) {
    reg.Write(uint32(p.Base)+0x0054, uint32(val))
}

// ReadT5MATCH1 reads Timer 5 First Match Register (TMC58).
func (p *TimerV1TIMER) ReadT5MATCH1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0058))
}

// WriteT5MATCH1 writes Timer 5 First Match Register (TMC58).
func (p *TimerV1TIMER) WriteT5MATCH1(val uint32) {
    reg.Write(uint32(p.Base)+0x0058, uint32(val))
}

// ReadT6STATUS reads Timer 6 Counter Status (TMC60).
func (p *TimerV1TIMER) ReadT6STATUS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0060))
}

// WriteT6STATUS writes Timer 6 Counter Status (TMC60).
func (p *TimerV1TIMER) WriteT6STATUS(val uint32) {
    reg.Write(uint32(p.Base)+0x0060, uint32(val))
}

// ReadT6RELOAD reads Timer 6 Reload Value (TMC64).
func (p *TimerV1TIMER) ReadT6RELOAD() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0064))
}

// WriteT6RELOAD writes Timer 6 Reload Value (TMC64).
func (p *TimerV1TIMER) WriteT6RELOAD(val uint32) {
    reg.Write(uint32(p.Base)+0x0064, uint32(val))
}

// ReadT6MATCH1 reads Timer 6 First Match Register (TMC68).
func (p *TimerV1TIMER) ReadT6MATCH1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0068))
}

// WriteT6MATCH1 writes Timer 6 First Match Register (TMC68).
func (p *TimerV1TIMER) WriteT6MATCH1(val uint32) {
    reg.Write(uint32(p.Base)+0x0068, uint32(val))
}

// ReadT7STATUS reads Timer 7 Counter Status (TMC70).
func (p *TimerV1TIMER) ReadT7STATUS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0070))
}

// WriteT7STATUS writes Timer 7 Counter Status (TMC70).
func (p *TimerV1TIMER) WriteT7STATUS(val uint32) {
    reg.Write(uint32(p.Base)+0x0070, uint32(val))
}

// ReadT7RELOAD reads Timer 7 Reload Value (TMC74).
func (p *TimerV1TIMER) ReadT7RELOAD() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0074))
}

// WriteT7RELOAD writes Timer 7 Reload Value (TMC74).
func (p *TimerV1TIMER) WriteT7RELOAD(val uint32) {
    reg.Write(uint32(p.Base)+0x0074, uint32(val))
}

// ReadT7MATCH1 reads Timer 7 First Match Register (TMC78).
func (p *TimerV1TIMER) ReadT7MATCH1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0078))
}

// WriteT7MATCH1 writes Timer 7 First Match Register (TMC78).
func (p *TimerV1TIMER) WriteT7MATCH1(val uint32) {
    reg.Write(uint32(p.Base)+0x0078, uint32(val))
}

// ReadT8STATUS reads Timer 8 Counter Status (TMC80).
func (p *TimerV1TIMER) ReadT8STATUS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0080))
}

// WriteT8STATUS writes Timer 8 Counter Status (TMC80).
func (p *TimerV1TIMER) WriteT8STATUS(val uint32) {
    reg.Write(uint32(p.Base)+0x0080, uint32(val))
}

// ReadT8RELOAD reads Timer 8 Reload Value (TMC84).
func (p *TimerV1TIMER) ReadT8RELOAD() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0084))
}

// WriteT8RELOAD writes Timer 8 Reload Value (TMC84).
func (p *TimerV1TIMER) WriteT8RELOAD(val uint32) {
    reg.Write(uint32(p.Base)+0x0084, uint32(val))
}

// ReadT8MATCH1 reads Timer 8 First Match Register (TMC88).
func (p *TimerV1TIMER) ReadT8MATCH1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0088))
}

// WriteT8MATCH1 writes Timer 8 First Match Register (TMC88).
func (p *TimerV1TIMER) WriteT8MATCH1(val uint32) {
    reg.Write(uint32(p.Base)+0x0088, uint32(val))
}

