// Code generated by chiptool; DO NOT EDIT.

package pac

import "github.com/kyanitecomputer/aspeed-go/reg"

// UartdmaV1UARTDMA ASPEED UART DMA Controller. Base: 0x7E79_E000. Supports UART1, UART2, and UART5.
type UartdmaV1UARTDMA struct {
    Base uintptr
}

// ReadTXENABLE reads UART TX DMA enable register (UDMA000). Set bit to enable DMA TX for the corresponding UART channel.
func (p *UartdmaV1UARTDMA) ReadTXENABLE() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0000))
}

// WriteTXENABLE writes UART TX DMA enable register (UDMA000). Set bit to enable DMA TX for the corresponding UART channel.
func (p *UartdmaV1UARTDMA) WriteTXENABLE(val uint32) {
    reg.Write(uint32(p.Base)+0x0000, uint32(val))
}

// ReadRXENABLE reads UART RX DMA enable register (UDMA004). Set bit to enable DMA RX for the corresponding UART channel.
func (p *UartdmaV1UARTDMA) ReadRXENABLE() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0004))
}

// WriteRXENABLE writes UART RX DMA enable register (UDMA004). Set bit to enable DMA RX for the corresponding UART channel.
func (p *UartdmaV1UARTDMA) WriteRXENABLE(val uint32) {
    reg.Write(uint32(p.Base)+0x0004, uint32(val))
}

// ReadTIMEOUTTIMER reads DMA timeout timer (UDMA00C). If a DMA transfer stalls for longer than this period, a timeout event occurs. Unit: PCLK cycles × 14400.
func (p *UartdmaV1UARTDMA) ReadTIMEOUTTIMER() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x000c))
}

// WriteTIMEOUTTIMER writes DMA timeout timer (UDMA00C). If a DMA transfer stalls for longer than this period, a timeout event occurs. Unit: PCLK cycles × 14400.
func (p *UartdmaV1UARTDMA) WriteTIMEOUTTIMER(val uint32) {
    reg.Write(uint32(p.Base)+0x000c, uint32(val))
}

// ReadTXRESET reads UART TX DMA reset register (UDMA020). Write 1 to reset DMA TX state for the corresponding UART channel. Returns to 0 when reset completes.
func (p *UartdmaV1UARTDMA) ReadTXRESET() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0020))
}

// WriteTXRESET writes UART TX DMA reset register (UDMA020). Write 1 to reset DMA TX state for the corresponding UART channel. Returns to 0 when reset completes.
func (p *UartdmaV1UARTDMA) WriteTXRESET(val uint32) {
    reg.Write(uint32(p.Base)+0x0020, uint32(val))
}

// ReadRXRESET reads UART RX DMA reset register (UDMA024). Write 1 to reset DMA RX state for the corresponding UART channel.
func (p *UartdmaV1UARTDMA) ReadRXRESET() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0024))
}

// WriteRXRESET writes UART RX DMA reset register (UDMA024). Write 1 to reset DMA RX state for the corresponding UART channel.
func (p *UartdmaV1UARTDMA) WriteRXRESET(val uint32) {
    reg.Write(uint32(p.Base)+0x0024, uint32(val))
}

// ReadTXIRQENABLE reads TX DMA interrupt enable register (UDMA030). TX interrupt fires when TX buffer becomes empty (transmitter drained).
func (p *UartdmaV1UARTDMA) ReadTXIRQENABLE() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0030))
}

// WriteTXIRQENABLE writes TX DMA interrupt enable register (UDMA030). TX interrupt fires when TX buffer becomes empty (transmitter drained).
func (p *UartdmaV1UARTDMA) WriteTXIRQENABLE(val uint32) {
    reg.Write(uint32(p.Base)+0x0030, uint32(val))
}

// ReadTXIRQSTATUS reads TX DMA interrupt status register (UDMA034). Write-1-to-clear. Bit set when TX DMA buffer empties for the corresponding UART.
func (p *UartdmaV1UARTDMA) ReadTXIRQSTATUS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0034))
}

// WriteTXIRQSTATUS writes TX DMA interrupt status register (UDMA034). Write-1-to-clear. Bit set when TX DMA buffer empties for the corresponding UART.
func (p *UartdmaV1UARTDMA) WriteTXIRQSTATUS(val uint32) {
    reg.Write(uint32(p.Base)+0x0034, uint32(val))
}

// ReadRXIRQENABLE reads RX DMA interrupt enable register (UDMA038). RX interrupt fires when RX buffer becomes full.
func (p *UartdmaV1UARTDMA) ReadRXIRQENABLE() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0038))
}

// WriteRXIRQENABLE writes RX DMA interrupt enable register (UDMA038). RX interrupt fires when RX buffer becomes full.
func (p *UartdmaV1UARTDMA) WriteRXIRQENABLE(val uint32) {
    reg.Write(uint32(p.Base)+0x0038, uint32(val))
}

// ReadRXIRQSTATUS reads RX DMA interrupt status register (UDMA03C). Write-1-to-clear. Bit set when RX DMA buffer fills for the corresponding UART.
func (p *UartdmaV1UARTDMA) ReadRXIRQSTATUS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x003c))
}

// WriteRXIRQSTATUS writes RX DMA interrupt status register (UDMA03C). Write-1-to-clear. Bit set when RX DMA buffer fills for the corresponding UART.
func (p *UartdmaV1UARTDMA) WriteRXIRQSTATUS(val uint32) {
    reg.Write(uint32(p.Base)+0x003c, uint32(val))
}

// ReadUART1TXRDPTR reads UART1 TX DMA read pointer (UDMA040, hardware-managed, read-only).
func (p *UartdmaV1UARTDMA) ReadUART1TXRDPTR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0040))
}

// WriteUART1TXRDPTR writes UART1 TX DMA read pointer (UDMA040, hardware-managed, read-only).
func (p *UartdmaV1UARTDMA) WriteUART1TXRDPTR(val uint32) {
    reg.Write(uint32(p.Base)+0x0040, uint32(val))
}

// ReadUART1TXWRPTR reads UART1 TX DMA write pointer (UDMA044, software-managed).
func (p *UartdmaV1UARTDMA) ReadUART1TXWRPTR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0044))
}

// WriteUART1TXWRPTR writes UART1 TX DMA write pointer (UDMA044, software-managed).
func (p *UartdmaV1UARTDMA) WriteUART1TXWRPTR(val uint32) {
    reg.Write(uint32(p.Base)+0x0044, uint32(val))
}

// ReadUART1TXBASE reads UART1 TX DMA buffer base address (UDMA048, physical, 4-byte aligned).
func (p *UartdmaV1UARTDMA) ReadUART1TXBASE() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0048))
}

// WriteUART1TXBASE writes UART1 TX DMA buffer base address (UDMA048, physical, 4-byte aligned).
func (p *UartdmaV1UARTDMA) WriteUART1TXBASE(val uint32) {
    reg.Write(uint32(p.Base)+0x0048, uint32(val))
}

// ReadUART1TXCTRL reads UART1 TX DMA control — timeout enable and buffer size (UDMA04C).
func (p *UartdmaV1UARTDMA) ReadUART1TXCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x004c))
}

// WriteUART1TXCTRL writes UART1 TX DMA control — timeout enable and buffer size (UDMA04C).
func (p *UartdmaV1UARTDMA) WriteUART1TXCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x004c, uint32(val))
}

// ReadUART1RXRDPTR reads UART1 RX DMA read pointer (UDMA050, software-managed).
func (p *UartdmaV1UARTDMA) ReadUART1RXRDPTR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0050))
}

// WriteUART1RXRDPTR writes UART1 RX DMA read pointer (UDMA050, software-managed).
func (p *UartdmaV1UARTDMA) WriteUART1RXRDPTR(val uint32) {
    reg.Write(uint32(p.Base)+0x0050, uint32(val))
}

// ReadUART1RXWRPTR reads UART1 RX DMA write pointer (UDMA054, hardware-managed, read-only).
func (p *UartdmaV1UARTDMA) ReadUART1RXWRPTR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0054))
}

// WriteUART1RXWRPTR writes UART1 RX DMA write pointer (UDMA054, hardware-managed, read-only).
func (p *UartdmaV1UARTDMA) WriteUART1RXWRPTR(val uint32) {
    reg.Write(uint32(p.Base)+0x0054, uint32(val))
}

// ReadUART1RXBASE reads UART1 RX DMA buffer base address (UDMA058, physical, 4-byte aligned).
func (p *UartdmaV1UARTDMA) ReadUART1RXBASE() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0058))
}

// WriteUART1RXBASE writes UART1 RX DMA buffer base address (UDMA058, physical, 4-byte aligned).
func (p *UartdmaV1UARTDMA) WriteUART1RXBASE(val uint32) {
    reg.Write(uint32(p.Base)+0x0058, uint32(val))
}

// ReadUART1RXCTRL reads UART1 RX DMA control — full mode, timeout enable, buffer size (UDMA05C).
func (p *UartdmaV1UARTDMA) ReadUART1RXCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x005c))
}

// WriteUART1RXCTRL writes UART1 RX DMA control — full mode, timeout enable, buffer size (UDMA05C).
func (p *UartdmaV1UARTDMA) WriteUART1RXCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x005c, uint32(val))
}

// ReadUART2TXRDPTR reads UART2 TX DMA read pointer (UDMA060, hardware-managed, read-only).
func (p *UartdmaV1UARTDMA) ReadUART2TXRDPTR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0060))
}

// WriteUART2TXRDPTR writes UART2 TX DMA read pointer (UDMA060, hardware-managed, read-only).
func (p *UartdmaV1UARTDMA) WriteUART2TXRDPTR(val uint32) {
    reg.Write(uint32(p.Base)+0x0060, uint32(val))
}

// ReadUART2TXWRPTR reads UART2 TX DMA write pointer (UDMA064, software-managed).
func (p *UartdmaV1UARTDMA) ReadUART2TXWRPTR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0064))
}

// WriteUART2TXWRPTR writes UART2 TX DMA write pointer (UDMA064, software-managed).
func (p *UartdmaV1UARTDMA) WriteUART2TXWRPTR(val uint32) {
    reg.Write(uint32(p.Base)+0x0064, uint32(val))
}

// ReadUART2TXBASE reads UART2 TX DMA buffer base address (UDMA068).
func (p *UartdmaV1UARTDMA) ReadUART2TXBASE() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0068))
}

// WriteUART2TXBASE writes UART2 TX DMA buffer base address (UDMA068).
func (p *UartdmaV1UARTDMA) WriteUART2TXBASE(val uint32) {
    reg.Write(uint32(p.Base)+0x0068, uint32(val))
}

// ReadUART2TXCTRL reads UART2 TX DMA control (UDMA06C).
func (p *UartdmaV1UARTDMA) ReadUART2TXCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x006c))
}

// WriteUART2TXCTRL writes UART2 TX DMA control (UDMA06C).
func (p *UartdmaV1UARTDMA) WriteUART2TXCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x006c, uint32(val))
}

// ReadUART2RXRDPTR reads UART2 RX DMA read pointer (UDMA070, software-managed).
func (p *UartdmaV1UARTDMA) ReadUART2RXRDPTR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0070))
}

// WriteUART2RXRDPTR writes UART2 RX DMA read pointer (UDMA070, software-managed).
func (p *UartdmaV1UARTDMA) WriteUART2RXRDPTR(val uint32) {
    reg.Write(uint32(p.Base)+0x0070, uint32(val))
}

// ReadUART2RXWRPTR reads UART2 RX DMA write pointer (UDMA074, hardware-managed, read-only).
func (p *UartdmaV1UARTDMA) ReadUART2RXWRPTR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0074))
}

// WriteUART2RXWRPTR writes UART2 RX DMA write pointer (UDMA074, hardware-managed, read-only).
func (p *UartdmaV1UARTDMA) WriteUART2RXWRPTR(val uint32) {
    reg.Write(uint32(p.Base)+0x0074, uint32(val))
}

// ReadUART2RXBASE reads UART2 RX DMA buffer base address (UDMA078).
func (p *UartdmaV1UARTDMA) ReadUART2RXBASE() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0078))
}

// WriteUART2RXBASE writes UART2 RX DMA buffer base address (UDMA078).
func (p *UartdmaV1UARTDMA) WriteUART2RXBASE(val uint32) {
    reg.Write(uint32(p.Base)+0x0078, uint32(val))
}

// ReadUART2RXCTRL reads UART2 RX DMA control (UDMA07C).
func (p *UartdmaV1UARTDMA) ReadUART2RXCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x007c))
}

// WriteUART2RXCTRL writes UART2 RX DMA control (UDMA07C).
func (p *UartdmaV1UARTDMA) WriteUART2RXCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x007c, uint32(val))
}

// ReadUART5TXRDPTR reads UART5 TX DMA read pointer (UDMA0C0, hardware-managed, read-only).
func (p *UartdmaV1UARTDMA) ReadUART5TXRDPTR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00c0))
}

// WriteUART5TXRDPTR writes UART5 TX DMA read pointer (UDMA0C0, hardware-managed, read-only).
func (p *UartdmaV1UARTDMA) WriteUART5TXRDPTR(val uint32) {
    reg.Write(uint32(p.Base)+0x00c0, uint32(val))
}

// ReadUART5TXWRPTR reads UART5 TX DMA write pointer (UDMA0C4, software-managed).
func (p *UartdmaV1UARTDMA) ReadUART5TXWRPTR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00c4))
}

// WriteUART5TXWRPTR writes UART5 TX DMA write pointer (UDMA0C4, software-managed).
func (p *UartdmaV1UARTDMA) WriteUART5TXWRPTR(val uint32) {
    reg.Write(uint32(p.Base)+0x00c4, uint32(val))
}

// ReadUART5TXBASE reads UART5 TX DMA buffer base address (UDMA0C8).
func (p *UartdmaV1UARTDMA) ReadUART5TXBASE() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00c8))
}

// WriteUART5TXBASE writes UART5 TX DMA buffer base address (UDMA0C8).
func (p *UartdmaV1UARTDMA) WriteUART5TXBASE(val uint32) {
    reg.Write(uint32(p.Base)+0x00c8, uint32(val))
}

// ReadUART5TXCTRL reads UART5 TX DMA control (UDMA0CC).
func (p *UartdmaV1UARTDMA) ReadUART5TXCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00cc))
}

// WriteUART5TXCTRL writes UART5 TX DMA control (UDMA0CC).
func (p *UartdmaV1UARTDMA) WriteUART5TXCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x00cc, uint32(val))
}

// ReadUART5RXRDPTR reads UART5 RX DMA read pointer (UDMA0D0, software-managed).
func (p *UartdmaV1UARTDMA) ReadUART5RXRDPTR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00d0))
}

// WriteUART5RXRDPTR writes UART5 RX DMA read pointer (UDMA0D0, software-managed).
func (p *UartdmaV1UARTDMA) WriteUART5RXRDPTR(val uint32) {
    reg.Write(uint32(p.Base)+0x00d0, uint32(val))
}

// ReadUART5RXWRPTR reads UART5 RX DMA write pointer (UDMA0D4, hardware-managed, read-only).
func (p *UartdmaV1UARTDMA) ReadUART5RXWRPTR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00d4))
}

// WriteUART5RXWRPTR writes UART5 RX DMA write pointer (UDMA0D4, hardware-managed, read-only).
func (p *UartdmaV1UARTDMA) WriteUART5RXWRPTR(val uint32) {
    reg.Write(uint32(p.Base)+0x00d4, uint32(val))
}

// ReadUART5RXBASE reads UART5 RX DMA buffer base address (UDMA0D8).
func (p *UartdmaV1UARTDMA) ReadUART5RXBASE() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00d8))
}

// WriteUART5RXBASE writes UART5 RX DMA buffer base address (UDMA0D8).
func (p *UartdmaV1UARTDMA) WriteUART5RXBASE(val uint32) {
    reg.Write(uint32(p.Base)+0x00d8, uint32(val))
}

// ReadUART5RXCTRL reads UART5 RX DMA control (UDMA0DC).
func (p *UartdmaV1UARTDMA) ReadUART5RXCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00dc))
}

// WriteUART5RXCTRL writes UART5 RX DMA control (UDMA0DC).
func (p *UartdmaV1UARTDMA) WriteUART5RXCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x00dc, uint32(val))
}

