// Code generated by chiptool; DO NOT EDIT.

package pac

// gpr_v1::GPR_REG General-purpose 32-bit read/write register.
const (
    // VALUE Register value (32-bit, software-defined meaning).
    GprV1GPRREGVALUEPos = 0
    GprV1GPRREGVALUEMsk = 0xffffffff << 0
)

// gpr_v1::S_PAGE_REG AHB page select register. Selects 512 KB AHB page for CM4F DMA.
const (
    // PAGE AHB page index (bits [31:0]; effective bits hardware-defined).
    GprV1SPAGEREGPAGEPos = 0
    GprV1SPAGEREGPAGEMsk = 0xffffffff << 0
)

// ssp_v2::CACHE_AREA Cacheable area bitmask for one bus (I-bus or D-bus). Same layout as AST2600 CACHE_AREA: 32 bits × 16 MB per bit.
const (
    // REGION Cacheable region bitmask (bit N = 16 MB region starting at N×16 MB).
    SspV2CACHEAREAREGIONPos = 0
    SspV2CACHEAREAREGIONMsk = 0xffffffff << 0
)

// ssp_v2::CACHE_FUNC Cache Function Control Register (AST2700 v2 layout). INCOMPATIBLE with ssp_v1 — bits 0-5 completely redefined. No CCM or IRQ monitoring bits (those were v1 only).
const (
    // DCACHEEN D-cache enable (bit 0). Independent of I-cache.
    SspV2CACHEFUNCDCACHEENPos = 0
    SspV2CACHEFUNCDCACHEENMsk = 0x1 << 0
    // ICACHEEN I-cache enable (bit 1). New in v2.
    SspV2CACHEFUNCICACHEENPos = 1
    SspV2CACHEFUNCICACHEENMsk = 0x1 << 1
    // DCACHECLEAR D-cache bulk clear (one-shot, bit 2).
    SspV2CACHEFUNCDCACHECLEARPos = 2
    SspV2CACHEFUNCDCACHECLEARMsk = 0x1 << 2
    // ICACHECLEAR I-cache bulk clear (one-shot, bit 3).
    SspV2CACHEFUNCICACHECLEARPos = 3
    SspV2CACHEFUNCICACHECLEARMsk = 0x1 << 3
    // DCACHEPREFETCHCLEAR D-cache prefetch buffer clear (one-shot, bit 4). New in v2.
    SspV2CACHEFUNCDCACHEPREFETCHCLEARPos = 4
    SspV2CACHEFUNCDCACHEPREFETCHCLEARMsk = 0x1 << 4
    // ICACHEPREFETCHCLEAR I-cache prefetch buffer clear (one-shot, bit 5). New in v2.
    SspV2CACHEFUNCICACHEPREFETCHCLEARPos = 5
    SspV2CACHEFUNCICACHEPREFETCHCLEARMsk = 0x1 << 5
)

// ssp_v2::CACHE_INVAL Cache Invalidation Control (SCU134/SCU174). Same layout as v1.
const (
    // ICACHEADDR I-cache line address for targeted invalidation (bits [10:0]).
    SspV2CACHEINVALICACHEADDRPos = 0
    SspV2CACHEINVALICACHEADDRMsk = 0x7ff << 0
    // ICACHEEN I-cache line invalidation trigger (bit 15).
    SspV2CACHEINVALICACHEENPos = 15
    SspV2CACHEINVALICACHEENMsk = 0x1 << 15
    // DCACHEADDR D-cache line address for targeted invalidation (bits [26:16]).
    SspV2CACHEINVALDCACHEADDRPos = 16
    SspV2CACHEINVALDCACHEADDRMsk = 0x7ff << 16
    // DCACHEEN D-cache line invalidation trigger (bit 31).
    SspV2CACHEINVALDCACHEENPos = 31
    SspV2CACHEINVALDCACHEENMsk = 0x1 << 31
)

// ssp_v2::CTRL CM4F Coprocessor Control Register (AST2700 v2).
const (
    // EN CM4F Coprocessor Enable (0=disabled/reset, 1=enabled).
    SspV2CTRLENPos = 0
    SspV2CTRLENMsk = 0x1 << 0
    // RESET CM4F Coprocessor Reset (active-high).
    SspV2CTRLRESETPos = 1
    SspV2CTRLRESETMsk = 0x1 << 1
    // DEBUGEN CM4F external debug enable (new in v2).
    SspV2CTRLDEBUGENPos = 2
    SspV2CTRLDEBUGENMsk = 0x1 << 2
    // SRAMSLEEP Coprocessor SRAM sleep mode (new in v2).
    SspV2CTRLSRAMSLEEPPos = 5
    SspV2CTRLSRAMSLEEPMsk = 0x1 << 5
    // SRAMDEEPSLEEP Coprocessor SRAM deep sleep mode (new in v2).
    SspV2CTRLSRAMDEEPSLEEPPos = 6
    SspV2CTRLSRAMDEEPSLEEPMsk = 0x1 << 6
    // SRAMSHUTDOWN Coprocessor SRAM shutdown mode (new in v2).
    SspV2CTRLSRAMSHUTDOWNPos = 7
    SspV2CTRLSRAMSHUTDOWNMsk = 0x1 << 7
)

// ssp_v2::REMAP_BASE Memory remap base address register. Physical address = field_value << 4 (word-aligned 31-bit field).
const (
    // PHYSBASE Physical base address bits [31:4] (bits [30:0] in register, << 4 to get address).
    SspV2REMAPBASEPHYSBASEPos = 0
    SspV2REMAPBASEPHYSBASEMsk = 0x7fffffff << 0
)

// ssp_v2::VIRT_ADDR Virtual address for a memory window (TCM, SRAM, or DRAM).
const (
    // ADDR Virtual start address (32-bit aligned).
    SspV2VIRTADDRADDRPos = 0
    SspV2VIRTADDRADDRMsk = 0xffffffff << 0
)

// ssp_v2::VIRT_SIZE Size of a virtual memory window.
const (
    // SIZE Window size in bytes.
    SspV2VIRTSIZESIZEPos = 0
    SspV2VIRTSIZESIZEMsk = 0xffffffff << 0
)

