// Code generated by chiptool; DO NOT EDIT.

package pac

import "github.com/kyanitecomputer/aspeed-go/reg"

// GprV1GPR AST2700 CM4F General-Purpose Register bank. Base: 0x5000_0000 (CM4F private bus). 32 GPRs at 0x00–0x7C plus S_PAGE at 0x80.
type GprV1GPR struct {
    Base uintptr
}

// ReadGPR0 reads General-Purpose Register 0.
func (p *GprV1GPR) ReadGPR0() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0000))
}

// WriteGPR0 writes General-Purpose Register 0.
func (p *GprV1GPR) WriteGPR0(val uint32) {
    reg.Write(uint32(p.Base)+0x0000, uint32(val))
}

// ReadGPR1 reads General-Purpose Register 1.
func (p *GprV1GPR) ReadGPR1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0004))
}

// WriteGPR1 writes General-Purpose Register 1.
func (p *GprV1GPR) WriteGPR1(val uint32) {
    reg.Write(uint32(p.Base)+0x0004, uint32(val))
}

// ReadGPR2 reads General-Purpose Register 2.
func (p *GprV1GPR) ReadGPR2() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0008))
}

// WriteGPR2 writes General-Purpose Register 2.
func (p *GprV1GPR) WriteGPR2(val uint32) {
    reg.Write(uint32(p.Base)+0x0008, uint32(val))
}

// ReadGPR3 reads General-Purpose Register 3.
func (p *GprV1GPR) ReadGPR3() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x000c))
}

// WriteGPR3 writes General-Purpose Register 3.
func (p *GprV1GPR) WriteGPR3(val uint32) {
    reg.Write(uint32(p.Base)+0x000c, uint32(val))
}

// ReadGPR4 reads General-Purpose Register 4.
func (p *GprV1GPR) ReadGPR4() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0010))
}

// WriteGPR4 writes General-Purpose Register 4.
func (p *GprV1GPR) WriteGPR4(val uint32) {
    reg.Write(uint32(p.Base)+0x0010, uint32(val))
}

// ReadGPR5 reads General-Purpose Register 5.
func (p *GprV1GPR) ReadGPR5() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0014))
}

// WriteGPR5 writes General-Purpose Register 5.
func (p *GprV1GPR) WriteGPR5(val uint32) {
    reg.Write(uint32(p.Base)+0x0014, uint32(val))
}

// ReadGPR6 reads General-Purpose Register 6.
func (p *GprV1GPR) ReadGPR6() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0018))
}

// WriteGPR6 writes General-Purpose Register 6.
func (p *GprV1GPR) WriteGPR6(val uint32) {
    reg.Write(uint32(p.Base)+0x0018, uint32(val))
}

// ReadGPR7 reads General-Purpose Register 7.
func (p *GprV1GPR) ReadGPR7() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x001c))
}

// WriteGPR7 writes General-Purpose Register 7.
func (p *GprV1GPR) WriteGPR7(val uint32) {
    reg.Write(uint32(p.Base)+0x001c, uint32(val))
}

// ReadGPR8 reads General-Purpose Register 8.
func (p *GprV1GPR) ReadGPR8() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0020))
}

// WriteGPR8 writes General-Purpose Register 8.
func (p *GprV1GPR) WriteGPR8(val uint32) {
    reg.Write(uint32(p.Base)+0x0020, uint32(val))
}

// ReadGPR9 reads General-Purpose Register 9.
func (p *GprV1GPR) ReadGPR9() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0024))
}

// WriteGPR9 writes General-Purpose Register 9.
func (p *GprV1GPR) WriteGPR9(val uint32) {
    reg.Write(uint32(p.Base)+0x0024, uint32(val))
}

// ReadGPR10 reads General-Purpose Register 10.
func (p *GprV1GPR) ReadGPR10() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0028))
}

// WriteGPR10 writes General-Purpose Register 10.
func (p *GprV1GPR) WriteGPR10(val uint32) {
    reg.Write(uint32(p.Base)+0x0028, uint32(val))
}

// ReadGPR11 reads General-Purpose Register 11.
func (p *GprV1GPR) ReadGPR11() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x002c))
}

// WriteGPR11 writes General-Purpose Register 11.
func (p *GprV1GPR) WriteGPR11(val uint32) {
    reg.Write(uint32(p.Base)+0x002c, uint32(val))
}

// ReadGPR12 reads General-Purpose Register 12.
func (p *GprV1GPR) ReadGPR12() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0030))
}

// WriteGPR12 writes General-Purpose Register 12.
func (p *GprV1GPR) WriteGPR12(val uint32) {
    reg.Write(uint32(p.Base)+0x0030, uint32(val))
}

// ReadGPR13 reads General-Purpose Register 13.
func (p *GprV1GPR) ReadGPR13() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0034))
}

// WriteGPR13 writes General-Purpose Register 13.
func (p *GprV1GPR) WriteGPR13(val uint32) {
    reg.Write(uint32(p.Base)+0x0034, uint32(val))
}

// ReadGPR14 reads General-Purpose Register 14.
func (p *GprV1GPR) ReadGPR14() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0038))
}

// WriteGPR14 writes General-Purpose Register 14.
func (p *GprV1GPR) WriteGPR14(val uint32) {
    reg.Write(uint32(p.Base)+0x0038, uint32(val))
}

// ReadGPR15 reads General-Purpose Register 15.
func (p *GprV1GPR) ReadGPR15() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x003c))
}

// WriteGPR15 writes General-Purpose Register 15.
func (p *GprV1GPR) WriteGPR15(val uint32) {
    reg.Write(uint32(p.Base)+0x003c, uint32(val))
}

// ReadGPR16 reads General-Purpose Register 16.
func (p *GprV1GPR) ReadGPR16() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0040))
}

// WriteGPR16 writes General-Purpose Register 16.
func (p *GprV1GPR) WriteGPR16(val uint32) {
    reg.Write(uint32(p.Base)+0x0040, uint32(val))
}

// ReadGPR17 reads General-Purpose Register 17.
func (p *GprV1GPR) ReadGPR17() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0044))
}

// WriteGPR17 writes General-Purpose Register 17.
func (p *GprV1GPR) WriteGPR17(val uint32) {
    reg.Write(uint32(p.Base)+0x0044, uint32(val))
}

// ReadGPR18 reads General-Purpose Register 18.
func (p *GprV1GPR) ReadGPR18() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0048))
}

// WriteGPR18 writes General-Purpose Register 18.
func (p *GprV1GPR) WriteGPR18(val uint32) {
    reg.Write(uint32(p.Base)+0x0048, uint32(val))
}

// ReadGPR19 reads General-Purpose Register 19.
func (p *GprV1GPR) ReadGPR19() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x004c))
}

// WriteGPR19 writes General-Purpose Register 19.
func (p *GprV1GPR) WriteGPR19(val uint32) {
    reg.Write(uint32(p.Base)+0x004c, uint32(val))
}

// ReadGPR20 reads General-Purpose Register 20.
func (p *GprV1GPR) ReadGPR20() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0050))
}

// WriteGPR20 writes General-Purpose Register 20.
func (p *GprV1GPR) WriteGPR20(val uint32) {
    reg.Write(uint32(p.Base)+0x0050, uint32(val))
}

// ReadGPR21 reads General-Purpose Register 21.
func (p *GprV1GPR) ReadGPR21() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0054))
}

// WriteGPR21 writes General-Purpose Register 21.
func (p *GprV1GPR) WriteGPR21(val uint32) {
    reg.Write(uint32(p.Base)+0x0054, uint32(val))
}

// ReadGPR22 reads General-Purpose Register 22.
func (p *GprV1GPR) ReadGPR22() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0058))
}

// WriteGPR22 writes General-Purpose Register 22.
func (p *GprV1GPR) WriteGPR22(val uint32) {
    reg.Write(uint32(p.Base)+0x0058, uint32(val))
}

// ReadGPR23 reads General-Purpose Register 23.
func (p *GprV1GPR) ReadGPR23() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x005c))
}

// WriteGPR23 writes General-Purpose Register 23.
func (p *GprV1GPR) WriteGPR23(val uint32) {
    reg.Write(uint32(p.Base)+0x005c, uint32(val))
}

// ReadGPR24 reads General-Purpose Register 24.
func (p *GprV1GPR) ReadGPR24() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0060))
}

// WriteGPR24 writes General-Purpose Register 24.
func (p *GprV1GPR) WriteGPR24(val uint32) {
    reg.Write(uint32(p.Base)+0x0060, uint32(val))
}

// ReadGPR25 reads General-Purpose Register 25.
func (p *GprV1GPR) ReadGPR25() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0064))
}

// WriteGPR25 writes General-Purpose Register 25.
func (p *GprV1GPR) WriteGPR25(val uint32) {
    reg.Write(uint32(p.Base)+0x0064, uint32(val))
}

// ReadGPR26 reads General-Purpose Register 26.
func (p *GprV1GPR) ReadGPR26() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0068))
}

// WriteGPR26 writes General-Purpose Register 26.
func (p *GprV1GPR) WriteGPR26(val uint32) {
    reg.Write(uint32(p.Base)+0x0068, uint32(val))
}

// ReadGPR27 reads General-Purpose Register 27.
func (p *GprV1GPR) ReadGPR27() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x006c))
}

// WriteGPR27 writes General-Purpose Register 27.
func (p *GprV1GPR) WriteGPR27(val uint32) {
    reg.Write(uint32(p.Base)+0x006c, uint32(val))
}

// ReadGPR28 reads General-Purpose Register 28.
func (p *GprV1GPR) ReadGPR28() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0070))
}

// WriteGPR28 writes General-Purpose Register 28.
func (p *GprV1GPR) WriteGPR28(val uint32) {
    reg.Write(uint32(p.Base)+0x0070, uint32(val))
}

// ReadGPR29 reads General-Purpose Register 29.
func (p *GprV1GPR) ReadGPR29() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0074))
}

// WriteGPR29 writes General-Purpose Register 29.
func (p *GprV1GPR) WriteGPR29(val uint32) {
    reg.Write(uint32(p.Base)+0x0074, uint32(val))
}

// ReadGPR30 reads General-Purpose Register 30.
func (p *GprV1GPR) ReadGPR30() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0078))
}

// WriteGPR30 writes General-Purpose Register 30.
func (p *GprV1GPR) WriteGPR30(val uint32) {
    reg.Write(uint32(p.Base)+0x0078, uint32(val))
}

// ReadGPR31 reads General-Purpose Register 31.
func (p *GprV1GPR) ReadGPR31() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x007c))
}

// WriteGPR31 writes General-Purpose Register 31.
func (p *GprV1GPR) WriteGPR31(val uint32) {
    reg.Write(uint32(p.Base)+0x007c, uint32(val))
}

// ReadSPAGE reads AHB Page Select Register (0x80). Selects which 512 KB page of the AHB address space is accessible for DMA operations by the CM4F.
func (p *GprV1GPR) ReadSPAGE() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0080))
}

// WriteSPAGE writes AHB Page Select Register (0x80). Selects which 512 KB page of the AHB address space is accessible for DMA operations by the CM4F.
func (p *GprV1GPR) WriteSPAGE(val uint32) {
    reg.Write(uint32(p.Base)+0x0080, uint32(val))
}

