// Code generated by chiptool; DO NOT EDIT.

package pac

import "github.com/kyanitecomputer/aspeed-go/reg"

// ClockV1CLOCK AST2600 SCU clock-gating and PLL registers. Base: 0x7E6E_2000 (CM3 view = SCU base).
type ClockV1CLOCK struct {
    Base uintptr
}

// ReadCLKSTOP0SET reads Clock Stop Control Group 0 – Set Register (SCU080). Write 1 to any bit to STOP (gate) the corresponding clock. Write 0 has no effect.  Bits 0–31 match ASPEED_CLK_GRP_0_OFFSET.
func (p *ClockV1CLOCK) ReadCLKSTOP0SET() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0080))
}

// WriteCLKSTOP0SET writes Clock Stop Control Group 0 – Set Register (SCU080). Write 1 to any bit to STOP (gate) the corresponding clock. Write 0 has no effect.  Bits 0–31 match ASPEED_CLK_GRP_0_OFFSET.
func (p *ClockV1CLOCK) WriteCLKSTOP0SET(val uint32) {
    reg.Write(uint32(p.Base)+0x0080, uint32(val))
}

// ReadCLKSTOP0CLR reads Clock Stop Control Group 0 – Clear Register (SCU084). Write 1 to any bit to START (un-gate) the corresponding clock. Write 0 has no effect.  Same bit assignment as CLK_STOP0_SET.
func (p *ClockV1CLOCK) ReadCLKSTOP0CLR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0084))
}

// WriteCLKSTOP0CLR writes Clock Stop Control Group 0 – Clear Register (SCU084). Write 1 to any bit to START (un-gate) the corresponding clock. Write 0 has no effect.  Same bit assignment as CLK_STOP0_SET.
func (p *ClockV1CLOCK) WriteCLKSTOP0CLR(val uint32) {
    reg.Write(uint32(p.Base)+0x0084, uint32(val))
}

// ReadCLKSTOP1SET reads Clock Stop Control Group 1 – Set Register (SCU090). Write 1 to STOP the corresponding clock. Bits 0–30 map to ASPEED_CLK_GRP_1_OFFSET+0 through ASPEED_CLK_GRP_1_OFFSET+30.
func (p *ClockV1CLOCK) ReadCLKSTOP1SET() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0090))
}

// WriteCLKSTOP1SET writes Clock Stop Control Group 1 – Set Register (SCU090). Write 1 to STOP the corresponding clock. Bits 0–30 map to ASPEED_CLK_GRP_1_OFFSET+0 through ASPEED_CLK_GRP_1_OFFSET+30.
func (p *ClockV1CLOCK) WriteCLKSTOP1SET(val uint32) {
    reg.Write(uint32(p.Base)+0x0090, uint32(val))
}

// ReadCLKSTOP1CLR reads Clock Stop Control Group 1 – Clear Register (SCU094). Write 1 to START the corresponding clock.
func (p *ClockV1CLOCK) ReadCLKSTOP1CLR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0094))
}

// WriteCLKSTOP1CLR writes Clock Stop Control Group 1 – Clear Register (SCU094). Write 1 to START the corresponding clock.
func (p *ClockV1CLOCK) WriteCLKSTOP1CLR(val uint32) {
    reg.Write(uint32(p.Base)+0x0094, uint32(val))
}

// ReadAPLLPARAM reads APLL Parameter Register (SCU210). Controls the Audio PLL frequency: f_APLL = 25 MHz × (M+1) / ((N+1) × (P+1)). When BYPASS=1 the PLL is bypassed and f_APLL = 25 MHz.
func (p *ClockV1CLOCK) ReadAPLLPARAM() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0210))
}

// WriteAPLLPARAM writes APLL Parameter Register (SCU210). Controls the Audio PLL frequency: f_APLL = 25 MHz × (M+1) / ((N+1) × (P+1)). When BYPASS=1 the PLL is bypassed and f_APLL = 25 MHz.
func (p *ClockV1CLOCK) WriteAPLLPARAM(val uint32) {
    reg.Write(uint32(p.Base)+0x0210, uint32(val))
}

// ReadCLKSEL0 reads Clock Selection Register 0 (SCU300). APB1 clock divider from HPLL (1200 MHz). APB1 freq = 1200 MHz / ((APB1_DIV + 1) × 4).
func (p *ClockV1CLOCK) ReadCLKSEL0() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0300))
}

// WriteCLKSEL0 writes Clock Selection Register 0 (SCU300). APB1 clock divider from HPLL (1200 MHz). APB1 freq = 1200 MHz / ((APB1_DIV + 1) × 4).
func (p *ClockV1CLOCK) WriteCLKSEL0(val uint32) {
    reg.Write(uint32(p.Base)+0x0300, uint32(val))
}

// ReadCLKSEL4 reads Clock Selection Register 4 (SCU310). APB2 clock divider from HCLK (200 MHz). APB2 freq = 200 MHz / ((APB2_DIV + 1) × 2).
func (p *ClockV1CLOCK) ReadCLKSEL4() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0310))
}

// WriteCLKSEL4 writes Clock Selection Register 4 (SCU310). APB2 clock divider from HCLK (200 MHz). APB2 freq = 200 MHz / ((APB2_DIV + 1) × 2).
func (p *ClockV1CLOCK) WriteCLKSEL4(val uint32) {
    reg.Write(uint32(p.Base)+0x0310, uint32(val))
}

// ReadCLKSEL5 reads Clock Selection Register 5 (SCU314). I3C and UART7–13 clock source selection.
func (p *ClockV1CLOCK) ReadCLKSEL5() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0314))
}

// WriteCLKSEL5 writes Clock Selection Register 5 (SCU314). I3C and UART7–13 clock source selection.
func (p *ClockV1CLOCK) WriteCLKSEL5(val uint32) {
    reg.Write(uint32(p.Base)+0x0314, uint32(val))
}

