// Code generated by chiptool; DO NOT EDIT.

package pac

// clock_v1::CLK_SEL0 Clock Selection Register 0 (SCU300). Selects APB1 divider.
const (
    // APB1DIV APB1 clock divider selection (bits [25:23]). APB1 freq = HPLL (1200 MHz) / ((APB1_DIV + 1) × 4). Example: 0 → 1200/4 = 300 MHz, 1 → 1200/8 = 150 MHz, ...
    ClockV1CLKSEL0APB1DIVPos = 23
    ClockV1CLKSEL0APB1DIVMsk = 0x7 << 23
)

// clock_v1::CLK_SEL4 Clock Selection Register 4 (SCU310). Selects APB2 divider.
const (
    // APB2DIV APB2 clock divider selection (bits [11:9]). APB2 freq = HCLK (200 MHz) / ((APB2_DIV + 1) × 2). Example: 0 → 200/2 = 100 MHz, 1 → 200/4 = 50 MHz, ...
    ClockV1CLKSEL4APB2DIVPos = 9
    ClockV1CLKSEL4APB2DIVMsk = 0x7 << 9
)

// clock_v1::CLK_SEL5 Clock Selection Register 5 (SCU314). Selects I3C and UART7-13 clock source.
const (
    // I3CCLKAPLLDIV I3C clock APLL divider (bits [30:28]). When I3C_CLK_SRC=1: I3C freq = APLL / I3C_CLK_APLL_DIV_NUM where I3C_CLK_APLL_DIV_NUM = (value == 0) ? 2 : (value + 1).
    ClockV1CLKSEL5I3CCLKAPLLDIVPos = 28
    ClockV1CLKSEL5I3CCLKAPLLDIVMsk = 0x7 << 28
    // I3CCLKSRC I3C clock source selection (bit [31]). 0 = HCLK (200 MHz); 1 = APLL divided by I3C_CLK_APLL_DIV.
    ClockV1CLKSEL5I3CCLKSRCPos = 31
    ClockV1CLKSEL5I3CCLKSRCMsk = 0x1 << 31
)

// clock_v1::CLK_STOP0 Clock Stop Control, Group 0 (SCU080 / SCU084). Each bit controls one clock gate.  Writing the SET register stops the clock; writing the CLR register starts it.  Bit positions match ASPEED_CLK_GRP_0_OFFSET values from Zephyr ast26xx_clock.h.
const (
    // MCLK Memory controller clock (MCLK).
    ClockV1CLKSTOP0MCLKPos = 0
    ClockV1CLKSTOP0MCLKMsk = 0x1 << 0
    // ECLK Ethernet MAC clock (ECLK).
    ClockV1CLKSTOP0ECLKPos = 1
    ClockV1CLKSTOP0ECLKMsk = 0x1 << 1
    // GCLK Graphics engine clock (GCLK).
    ClockV1CLKSTOP0GCLKPos = 2
    ClockV1CLKSTOP0GCLKMsk = 0x1 << 2
    // VCLK Video engine clock (VCLK).
    ClockV1CLKSTOP0VCLKPos = 3
    ClockV1CLKSTOP0VCLKMsk = 0x1 << 3
    // BCLK USB bus clock (BCLK).
    ClockV1CLKSTOP0BCLKPos = 4
    ClockV1CLKSTOP0BCLKMsk = 0x1 << 4
    // DCLK DP/DisplayPort clock (DCLK).
    ClockV1CLKSTOP0DCLKPos = 5
    ClockV1CLKSTOP0DCLKMsk = 0x1 << 5
    // REF0CLK Reference clock 0.
    ClockV1CLKSTOP0REF0CLKPos = 6
    ClockV1CLKSTOP0REF0CLKMsk = 0x1 << 6
    // USBPORT2CLK USB port 2 clock.
    ClockV1CLKSTOP0USBPORT2CLKPos = 7
    ClockV1CLKSTOP0USBPORT2CLKMsk = 0x1 << 7
    // USBUHCICLK USB UHCI host controller clock.
    ClockV1CLKSTOP0USBUHCICLKPos = 9
    ClockV1CLKSTOP0USBUHCICLKMsk = 0x1 << 9
    // D1CLK DisplayPort MN divider clock (D1CLK).
    ClockV1CLKSTOP0D1CLKPos = 10
    ClockV1CLKSTOP0D1CLKMsk = 0x1 << 10
    // YCLK Y/video clock.
    ClockV1CLKSTOP0YCLKPos = 13
    ClockV1CLKSTOP0YCLKMsk = 0x1 << 13
    // USBPORT1CLK USB port 1 clock.
    ClockV1CLKSTOP0USBPORT1CLKPos = 14
    ClockV1CLKSTOP0USBPORT1CLKMsk = 0x1 << 14
    // UART5CLK UART5 clock.
    ClockV1CLKSTOP0UART5CLKPos = 15
    ClockV1CLKSTOP0UART5CLKMsk = 0x1 << 15
    // MAC1CLK Gigabit MAC 1 clock.
    ClockV1CLKSTOP0MAC1CLKPos = 20
    ClockV1CLKSTOP0MAC1CLKMsk = 0x1 << 20
    // MAC2CLK Gigabit MAC 2 clock.
    ClockV1CLKSTOP0MAC2CLKPos = 21
    ClockV1CLKSTOP0MAC2CLKMsk = 0x1 << 21
    // RSACLK RSA/ECC hardware accelerator clock.
    ClockV1CLKSTOP0RSACLKPos = 24
    ClockV1CLKSTOP0RSACLKMsk = 0x1 << 24
    // RVASCLK RVAS engine clock.
    ClockV1CLKSTOP0RVASCLKPos = 25
    ClockV1CLKSTOP0RVASCLKMsk = 0x1 << 25
    // EMMCCLK eMMC controller clock.
    ClockV1CLKSTOP0EMMCCLKPos = 27
    ClockV1CLKSTOP0EMMCCLKMsk = 0x1 << 27
)

// clock_v1::CLK_STOP1 Clock Stop Control, Group 1 (SCU090 / SCU094). Bit positions match ASPEED_CLK_GRP_1_OFFSET+N (subtract 32 for the bit).
const (
    // LCLK LPC clock (LCLK).
    ClockV1CLKSTOP1LCLKPos = 0
    ClockV1CLKSTOP1LCLKMsk = 0x1 << 0
    // ESPICLK eSPI controller clock.
    ClockV1CLKSTOP1ESPICLKPos = 1
    ClockV1CLKSTOP1ESPICLKMsk = 0x1 << 1
    // REF1CLK Reference clock 1.
    ClockV1CLKSTOP1REF1CLKPos = 2
    ClockV1CLKSTOP1REF1CLKMsk = 0x1 << 2
    // SDCLK SD/SDIO controller clock.
    ClockV1CLKSTOP1SDCLKPos = 4
    ClockV1CLKSTOP1SDCLKMsk = 0x1 << 4
    // LHCCLK LPC host controller clock.
    ClockV1CLKSTOP1LHCCLKPos = 5
    ClockV1CLKSTOP1LHCCLKMsk = 0x1 << 5
    // I3C0CLK I3C controller 0 clock.
    ClockV1CLKSTOP1I3C0CLKPos = 8
    ClockV1CLKSTOP1I3C0CLKMsk = 0x1 << 8
    // I3C1CLK I3C controller 1 clock.
    ClockV1CLKSTOP1I3C1CLKPos = 9
    ClockV1CLKSTOP1I3C1CLKMsk = 0x1 << 9
    // I3C2CLK I3C controller 2 clock.
    ClockV1CLKSTOP1I3C2CLKPos = 10
    ClockV1CLKSTOP1I3C2CLKMsk = 0x1 << 10
    // I3C3CLK I3C controller 3 clock.
    ClockV1CLKSTOP1I3C3CLKPos = 11
    ClockV1CLKSTOP1I3C3CLKMsk = 0x1 << 11
    // I3C4CLK I3C controller 4 clock.
    ClockV1CLKSTOP1I3C4CLKPos = 12
    ClockV1CLKSTOP1I3C4CLKMsk = 0x1 << 12
    // I3C5CLK I3C controller 5 clock.
    ClockV1CLKSTOP1I3C5CLKPos = 13
    ClockV1CLKSTOP1I3C5CLKMsk = 0x1 << 13
    // UART1CLK UART1 clock.
    ClockV1CLKSTOP1UART1CLKPos = 16
    ClockV1CLKSTOP1UART1CLKMsk = 0x1 << 16
    // UART2CLK UART2 clock.
    ClockV1CLKSTOP1UART2CLKPos = 17
    ClockV1CLKSTOP1UART2CLKMsk = 0x1 << 17
    // UART3CLK UART3 clock.
    ClockV1CLKSTOP1UART3CLKPos = 18
    ClockV1CLKSTOP1UART3CLKMsk = 0x1 << 18
    // UART4CLK UART4 clock.
    ClockV1CLKSTOP1UART4CLKPos = 19
    ClockV1CLKSTOP1UART4CLKMsk = 0x1 << 19
    // MAC3CLK Gigabit MAC 3 clock.
    ClockV1CLKSTOP1MAC3CLKPos = 20
    ClockV1CLKSTOP1MAC3CLKMsk = 0x1 << 20
    // MAC4CLK Gigabit MAC 4 clock.
    ClockV1CLKSTOP1MAC4CLKPos = 21
    ClockV1CLKSTOP1MAC4CLKMsk = 0x1 << 21
    // UART6CLK UART6 clock.
    ClockV1CLKSTOP1UART6CLKPos = 22
    ClockV1CLKSTOP1UART6CLKMsk = 0x1 << 22
    // UART7CLK UART7 clock.
    ClockV1CLKSTOP1UART7CLKPos = 23
    ClockV1CLKSTOP1UART7CLKMsk = 0x1 << 23
    // UART8CLK UART8 clock.
    ClockV1CLKSTOP1UART8CLKPos = 24
    ClockV1CLKSTOP1UART8CLKMsk = 0x1 << 24
    // UART9CLK UART9 clock.
    ClockV1CLKSTOP1UART9CLKPos = 25
    ClockV1CLKSTOP1UART9CLKMsk = 0x1 << 25
    // UART10CLK UART10 clock.
    ClockV1CLKSTOP1UART10CLKPos = 26
    ClockV1CLKSTOP1UART10CLKMsk = 0x1 << 26
    // UART11CLK UART11 clock (SSP console UART).
    ClockV1CLKSTOP1UART11CLKPos = 27
    ClockV1CLKSTOP1UART11CLKMsk = 0x1 << 27
    // UART12CLK UART12 clock.
    ClockV1CLKSTOP1UART12CLKPos = 28
    ClockV1CLKSTOP1UART12CLKMsk = 0x1 << 28
    // UART13CLK UART13 clock.
    ClockV1CLKSTOP1UART13CLKPos = 29
    ClockV1CLKSTOP1UART13CLKMsk = 0x1 << 29
    // FSICLK FSI (Flexible Service Interface) clock.
    ClockV1CLKSTOP1FSICLKPos = 30
    ClockV1CLKSTOP1FSICLKMsk = 0x1 << 30
)

// clock_v1::PLL_PARAM PLL Parameter Register layout (SCU200 = HPLL, SCU210 = APLL). f_PLL = 25 MHz × (M+1) / ((N+1) × (P+1)) when BYPASS=0. When BYPASS=1: f_PLL = 25 MHz (input passed through). Default (reset) for APLL: bypass mode active.
const (
    // M PLL M parameter (feedback divider minus 1). Range 0–8191. Multiplier = M+1.
    ClockV1PLLPARAMMPos = 0
    ClockV1PLLPARAMMMsk = 0x1fff << 0
    // N PLL N parameter (input pre-divider minus 1). Range 0–63. Pre-divider = N+1.
    ClockV1PLLPARAMNPos = 13
    ClockV1PLLPARAMNMsk = 0x3f << 13
    // P PLL P parameter (output divider minus 1). Range 0–15. Post-divider = P+1.
    ClockV1PLLPARAMPPos = 19
    ClockV1PLLPARAMPMsk = 0xf << 19
    // BYPASS PLL bypass mode. 0 = normal PLL operation (f_out = 25 MHz × (M+1) / ((N+1) × (P+1))); 1 = bypass (f_out = 25 MHz clock-in).
    ClockV1PLLPARAMBYPASSPos = 24
    ClockV1PLLPARAMBYPASSMsk = 0x1 << 24
)

// gpio_v1::GPIO32 Generic 32-bit GPIO register (data, direction, interrupt enable/status, reset tolerant, command source, input mask, data read). Each bit corresponds to one GPIO pin within the group.
const (
    // PINS Per-pin bitmask. Bit 0 = port_A pin 0 (or first port in group).
    GpioV1GPIO32PINSPos = 0
    GpioV1GPIO32PINSMsk = 0xffffffff << 0
)

// gpio_v1::GPIO_CMD_SRC_SEL GPIO Command Source Selection (GPIO2D0). Five 5-bit fields selecting the bus master index for each slot. SSP = master index 6 (ASPEED_GPIO_SEL_SSP).
const (
    // MST1 Master 1 bus ID selection (bits [4:0]).
    GpioV1GPIOCMDSRCSELMST1Pos = 0
    GpioV1GPIOCMDSRCSELMST1Msk = 0x1f << 0
    // MST2 Master 2 bus ID selection (bits [9:5]).
    GpioV1GPIOCMDSRCSELMST2Pos = 5
    GpioV1GPIOCMDSRCSELMST2Msk = 0x1f << 5
    // MST3 Master 3 bus ID selection (bits [14:10]).
    GpioV1GPIOCMDSRCSELMST3Pos = 10
    GpioV1GPIOCMDSRCSELMST3Msk = 0x1f << 10
    // MST4 Master 4 bus ID selection (bits [19:15]).
    GpioV1GPIOCMDSRCSELMST4Pos = 15
    GpioV1GPIOCMDSRCSELMST4Msk = 0x1f << 15
    // MST5 Master 5 bus ID selection (bits [24:20]).
    GpioV1GPIOCMDSRCSELMST5Pos = 20
    GpioV1GPIOCMDSRCSELMST5Msk = 0x1f << 20
    // LOCK Lock this register (1 = write-protect until next reset).
    GpioV1GPIOCMDSRCSELLOCKPos = 31
    GpioV1GPIOCMDSRCSELLOCKMsk = 0x1 << 31
)

// gpio_v1::GPIO_INDEX GPIO Index Register (GPIO2AC). Command-based per-pin control.
const (
    // INDEXNUMBER Pin number (0–207).
    GpioV1GPIOINDEXINDEXNUMBERPos = 0
    GpioV1GPIOINDEXINDEXNUMBERMsk = 0xff << 0
    // INDEXCMD Command direction. 0=write, 1=read.
    GpioV1GPIOINDEXINDEXCMDPos = 12
    GpioV1GPIOINDEXINDEXCMDMsk = 0x1 << 12
    // INDEXTYPE Operation type: 0=DATA, 1=DIR, 2=INTERRUPT, 3=DEBOUNCE, 4=TOLERANCE, 5=CMD_SRC, 6=INPUT_MASK.
    GpioV1GPIOINDEXINDEXTYPEPos = 16
    GpioV1GPIOINDEXINDEXTYPEMsk = 0xf << 16
    // INDEXDATA Data for the operation. For INTERRUPT: bit0=enable, bits[4:1]=type (0=fall, 1=rise, 2=level_low, 3=level_high, 4=both).
    GpioV1GPIOINDEXINDEXDATAPos = 20
    GpioV1GPIOINDEXINDEXDATAMsk = 0x1f << 20
)

// ipc_v1::IPC_CHANNELS IPC 15-channel bitmask. Bit n corresponds to IPC channel n (n = 0..14).
const (
    // CH IPC channel bitmask (bits [14:0]). Bit 0 = channel 0 (IRQ 182); bit 14 = channel 14 (IRQ 196).
    IpcV1IPCCHANNELSCHPos = 0
    IpcV1IPCCHANNELSCHMsk = 0x7fff << 0
)

// ssp_v1::CACHE_AREA CM3 Cacheable Area Declaration (SCUA40). Reset value 0xFFFF_FFFF. Modify only while CM3 is in reset (CTRL.RESET=1 or CTRL.EN=0).
const (
    // REGION Cacheable region bitmask (32 bits × 16 MB per bit). Bit 0  → CM3 0x0000_0000–0x00FF_FFFF cacheable when set. Bit 31 → CM3 0x1F00_0000–0x1FFF_FFFF cacheable when set. Non-cached accesses bypass the cache controller and go directly to DRAM.  The CM3 non-cached DMA region (typically at 0x0100_0000, bit 1) must be kept clear so IPC shared-memory coherency is maintained without explicit invalidation.
    SspV1CACHEAREAREGIONPos = 0
    SspV1CACHEAREAREGIONMsk = 0xffffffff << 0
)

// ssp_v1::CACHE_FUNC CM3 Cache Function Control (SCUA48). Reset value 0x0. 4 KB I-cache + 4 KB D-cache, 32-byte line size, 2-way set-associative, write-through (no dirty state; only invalidation, no flush needed).
const (
    // CACHEEN Cache enable. 0 = I-cache and D-cache disabled (all accesses go to DRAM); 1 = both caches active. Must configure CACHE_AREA before enabling.
    SspV1CACHEFUNCCACHEENPos = 0
    SspV1CACHEFUNCCACHEENMsk = 0x1 << 0
    // DCACHECLEAR D-cache bulk clear (one-shot). Write sequence: write 0 first, then write 1. Hardware clears all D-cache entries and resets this bit to 0. Do not use while CM3 is executing; intended for startup/shutdown.
    SspV1CACHEFUNCDCACHECLEARPos = 1
    SspV1CACHEFUNCDCACHECLEARMsk = 0x1 << 1
    // ICACHECLEAR I-cache bulk clear (one-shot). Write sequence: write 0 first, then write 1. Hardware clears all I-cache entries and resets this bit to 0. Do not use while CM3 is executing.
    SspV1CACHEFUNCICACHECLEARPos = 2
    SspV1CACHEFUNCICACHECLEARMsk = 0x1 << 2
    // CCMEN Closely-coupled memory (CCM) mode enable. Enables 4 KB × 2 internal SRAM as CM3 I-bus/D-bus tightly coupled memory.  Programming sequence: 1. Set CCM_SYS_OWN=1 so CA7 can write code to 0x1A00_0000. 2. CA7 writes firmware to 0x1A00_0000–0x1A03_FFFF. 3. Set CCM_EN=1. 4. Clear CCM_SYS_OWN=0 to hand SRAM ownership to CM3. Modify only while CM3 is in reset.
    SspV1CACHEFUNCCCMENPos = 10
    SspV1CACHEFUNCCCMENMsk = 0x1 << 10
    // CCMSYSOWN CCM master select. 0 = CM3 I/D-bus owns the tightly coupled SRAM; 1 = system bus (CA7 and other AHB masters) owns the SRAM. Modify only while CM3 is in reset.
    SspV1CACHEFUNCCCMSYSOWNPos = 11
    SspV1CACHEFUNCCCMSYSOWNMsk = 0x1 << 11
    // IRQEN IRQ enable for CM3 address-range monitoring. When set, out-of-range accesses on I-bus/D-bus/S-bus generate an interrupt to the CA7.
    SspV1CACHEFUNCIRQENPos = 12
    SspV1CACHEFUNCIRQENMsk = 0x1 << 12
    // IRQMASK IRQ mask for address-range monitoring. 1 = suppress the interrupt (raw flags still set in IRQ_RAW_*).
    SspV1CACHEFUNCIRQMASKPos = 13
    SspV1CACHEFUNCIRQMASKMsk = 0x1 << 13
    // IRQCLEAR Write 1 to clear the address-monitoring IRQ status flags (IRQ_RAW_IBUS, IRQ_RAW_DBUS, IRQ_RAW_SBUS).
    SspV1CACHEFUNCIRQCLEARPos = 14
    SspV1CACHEFUNCIRQCLEARMsk = 0x1 << 14
    // IRQRAWIBUS Raw IRQ flag (read-only): CM3 instruction-bus (I-bus) access was outside the range defined by MEM_BASE / IMEM_LIMIT. Cleared by writing IRQ_CLEAR=1.
    SspV1CACHEFUNCIRQRAWIBUSPos = 24
    SspV1CACHEFUNCIRQRAWIBUSMsk = 0x1 << 24
    // IRQRAWDBUS Raw IRQ flag (read-only): CM3 data-bus (D-bus) access was outside the range defined by MEM_BASE / DMEM_LIMIT. Cleared by writing IRQ_CLEAR=1.
    SspV1CACHEFUNCIRQRAWDBUSPos = 25
    SspV1CACHEFUNCIRQRAWDBUSMsk = 0x1 << 25
    // IRQRAWSBUS Raw IRQ flag (read-only): CM3 system-bus (S-bus) access was outside the AHB bridge window 0x6000_0000–0xE000_0000. Cleared by writing IRQ_CLEAR=1.
    SspV1CACHEFUNCIRQRAWSBUSPos = 26
    SspV1CACHEFUNCIRQRAWSBUSMsk = 0x1 << 26
    // IRQIBUS Masked IRQ (read-only): IRQ_RAW_IBUS AND NOT IRQ_MASK AND IRQ_EN.
    SspV1CACHEFUNCIRQIBUSPos = 28
    SspV1CACHEFUNCIRQIBUSMsk = 0x1 << 28
    // IRQDBUS Masked IRQ (read-only): IRQ_RAW_DBUS AND NOT IRQ_MASK AND IRQ_EN.
    SspV1CACHEFUNCIRQDBUSPos = 29
    SspV1CACHEFUNCIRQDBUSMsk = 0x1 << 29
    // IRQSBUS Masked IRQ (read-only): IRQ_RAW_SBUS AND NOT IRQ_MASK AND IRQ_EN.
    SspV1CACHEFUNCIRQSBUSPos = 30
    SspV1CACHEFUNCIRQSBUSMsk = 0x1 << 30
)

// ssp_v1::CACHE_INVAL CM3 Cache Invalidation Control (SCUA44). Reset value 0x0. Write-protocol (per datasheet): write 0 to the register first, then write the target address + trigger bit together. The cache is write-through, so only invalidation (not flush) is needed.
const (
    // ICACHEADDR I-cache line address for targeted invalidation. 11-bit LSB of the cache line address (each cache line is 32 B, so bits [15:5] of the virtual address; hardware ignores [4:0]). Write together with ICACHE_EN=1.
    SspV1CACHEINVALICACHEADDRPos = 0
    SspV1CACHEINVALICACHEADDRMsk = 0x7ff << 0
    // ICACHEEN I-cache line invalidation trigger. Write 1 to invalidate the instruction-cache line identified by ICACHE_ADDR.  Self-clearing (reads back 0 after invalidation). Datasheet protocol: write 0x0000 first, then write {ICACHE_EN=1, ICACHE_ADDR=<line>} in a single write.
    SspV1CACHEINVALICACHEENPos = 15
    SspV1CACHEINVALICACHEENMsk = 0x1 << 15
    // DCACHEADDR D-cache line address for targeted invalidation. 11-bit LSB of the cache line address. Corresponds to register bits [26:16]. Write together with DCACHE_EN=1.
    SspV1CACHEINVALDCACHEADDRPos = 16
    SspV1CACHEINVALDCACHEADDRMsk = 0x7ff << 16
    // DCACHEEN D-cache line invalidation trigger. Write 1 to invalidate the data-cache line identified by DCACHE_ADDR. Self-clearing (reads back 0 after invalidation). Datasheet protocol: write 0x0000_0000 first, then write {DCACHE_EN=1, DCACHE_ADDR=<line>} in a single write.
    SspV1CACHEINVALDCACHEENPos = 31
    SspV1CACHEINVALDCACHEENMsk = 0x1 << 31
)

// ssp_v1::CTRL CM3 Coprocessor Control (SCUA00). Reset value 0x0.
const (
    // EN CM3 Coprocessor Enable. 0 = disabled (also forces the CM3 into reset); 1 = enabled. Hold disabled for ≥1 µs before re-enabling. Programming sequence: disable → configure MEM_BASE/limits/cache → release reset → enable.
    SspV1CTRLENPos = 0
    SspV1CTRLENMsk = 0x1 << 0
    // RESET CM3 Coprocessor Reset. 0 = normal operation; 1 = reset asserted (active-high). When EN=0 the CM3 is also forced into reset regardless of this bit. Hold for ≥1 µs.  Release reset before asserting EN.
    SspV1CTRLRESETPos = 1
    SspV1CTRLRESETMsk = 0x1 << 1
)

// ssp_v1::MEM_BASE CM3 Memory Base Address (SCUA04). Reset value 0x0. Modify only while CM3 is in reset (CTRL.RESET=1 or CTRL.EN=0).
const (
    // BASE Physical DRAM base address bits [31:20]. CM3 virtual address 0x0000_0000 maps to this 1 MB-aligned physical address.  The CA7-to-CM3 address window is CM3 [0x0000_0000, 0x1FFF_FFFF] ↔ phys [BASE, BASE+512 MB).
    SspV1MEMBASEBASEPos = 20
    SspV1MEMBASEBASEMsk = 0xfff << 20
)

// ssp_v1::MEM_LIMIT CM3 Instruction or Data Memory Address Limit (SCUA08 / SCUA0C). Both registers share this layout.  Reset value 0x0. Modify only while CM3 is in reset (CTRL.RESET=1 or CTRL.EN=0).
const (
    // LIMIT Physical DRAM upper-bound address bits [31:20]. Accesses at or above this 1 MB-aligned boundary are rejected by the hardware access-checker (generates an IRQ; see CACHE_FUNC).
    SspV1MEMLIMITLIMITPos = 20
    SspV1MEMLIMITLIMITMsk = 0xfff << 20
)

// timer_v1::TMC_COUNTER 32-bit timer counter or reload value.
const (
    // VALUE Counter / reload value (32-bit).
    TimerV1TMCCOUNTERVALUEPos = 0
    TimerV1TMCCOUNTERVALUEMsk = 0xffffffff << 0
)

// timer_v1::TMC_CTRL Global Timer Control Register (TMC30 / TMC3C). 4 bits per timer. Bit layout for timer N (N=1..8), starting at bit (N-1)*4: bit+0: EN         — timer enable (0=disable, 1=enable) bit+1: CLK_SEL    — clock source (0=PCLK, 1=1 MHz) bit+2: OVF_INTR   — overflow interrupt enable bit+3: WDT_EN     — WDT tolerance (can be reset by WDT) Write '1' to TMC30 to set bits; write '1' to TMC3C to clear bits.
const (
    // T1EN Timer 1 enable.
    TimerV1TMCCTRLT1ENPos = 0
    TimerV1TMCCTRLT1ENMsk = 0x1 << 0
    // T1CLKSEL Timer 1 clock source: 0=PCLK, 1=1 MHz.
    TimerV1TMCCTRLT1CLKSELPos = 1
    TimerV1TMCCTRLT1CLKSELMsk = 0x1 << 1
    // T1OVFINTR Timer 1 overflow interrupt enable.
    TimerV1TMCCTRLT1OVFINTRPos = 2
    TimerV1TMCCTRLT1OVFINTRMsk = 0x1 << 2
    // T1WDTEN Timer 1 WDT tolerance.
    TimerV1TMCCTRLT1WDTENPos = 3
    TimerV1TMCCTRLT1WDTENMsk = 0x1 << 3
    // T2EN Timer 2 enable.
    TimerV1TMCCTRLT2ENPos = 4
    TimerV1TMCCTRLT2ENMsk = 0x1 << 4
    // T2CLKSEL Timer 2 clock source: 0=PCLK, 1=1 MHz.
    TimerV1TMCCTRLT2CLKSELPos = 5
    TimerV1TMCCTRLT2CLKSELMsk = 0x1 << 5
    // T2OVFINTR Timer 2 overflow interrupt enable.
    TimerV1TMCCTRLT2OVFINTRPos = 6
    TimerV1TMCCTRLT2OVFINTRMsk = 0x1 << 6
    // T2WDTEN Timer 2 WDT tolerance.
    TimerV1TMCCTRLT2WDTENPos = 7
    TimerV1TMCCTRLT2WDTENMsk = 0x1 << 7
    // T3EN Timer 3 enable.
    TimerV1TMCCTRLT3ENPos = 8
    TimerV1TMCCTRLT3ENMsk = 0x1 << 8
    // T3CLKSEL Timer 3 clock source: 0=PCLK, 1=1 MHz.
    TimerV1TMCCTRLT3CLKSELPos = 9
    TimerV1TMCCTRLT3CLKSELMsk = 0x1 << 9
    // T3OVFINTR Timer 3 overflow interrupt enable.
    TimerV1TMCCTRLT3OVFINTRPos = 10
    TimerV1TMCCTRLT3OVFINTRMsk = 0x1 << 10
    // T3WDTEN Timer 3 WDT tolerance.
    TimerV1TMCCTRLT3WDTENPos = 11
    TimerV1TMCCTRLT3WDTENMsk = 0x1 << 11
    // T4EN Timer 4 enable.
    TimerV1TMCCTRLT4ENPos = 12
    TimerV1TMCCTRLT4ENMsk = 0x1 << 12
    // T4CLKSEL Timer 4 clock source: 0=PCLK, 1=1 MHz.
    TimerV1TMCCTRLT4CLKSELPos = 13
    TimerV1TMCCTRLT4CLKSELMsk = 0x1 << 13
    // T4OVFINTR Timer 4 overflow interrupt enable.
    TimerV1TMCCTRLT4OVFINTRPos = 14
    TimerV1TMCCTRLT4OVFINTRMsk = 0x1 << 14
    // T4WDTEN Timer 4 WDT tolerance.
    TimerV1TMCCTRLT4WDTENPos = 15
    TimerV1TMCCTRLT4WDTENMsk = 0x1 << 15
    // T5EN Timer 5 enable.
    TimerV1TMCCTRLT5ENPos = 16
    TimerV1TMCCTRLT5ENMsk = 0x1 << 16
    // T5CLKSEL Timer 5 clock source: 0=PCLK, 1=1 MHz.
    TimerV1TMCCTRLT5CLKSELPos = 17
    TimerV1TMCCTRLT5CLKSELMsk = 0x1 << 17
    // T5OVFINTR Timer 5 overflow interrupt enable.
    TimerV1TMCCTRLT5OVFINTRPos = 18
    TimerV1TMCCTRLT5OVFINTRMsk = 0x1 << 18
    // T5WDTEN Timer 5 WDT tolerance.
    TimerV1TMCCTRLT5WDTENPos = 19
    TimerV1TMCCTRLT5WDTENMsk = 0x1 << 19
    // T6EN Timer 6 enable.
    TimerV1TMCCTRLT6ENPos = 20
    TimerV1TMCCTRLT6ENMsk = 0x1 << 20
    // T6CLKSEL Timer 6 clock source: 0=PCLK, 1=1 MHz.
    TimerV1TMCCTRLT6CLKSELPos = 21
    TimerV1TMCCTRLT6CLKSELMsk = 0x1 << 21
    // T6OVFINTR Timer 6 overflow interrupt enable.
    TimerV1TMCCTRLT6OVFINTRPos = 22
    TimerV1TMCCTRLT6OVFINTRMsk = 0x1 << 22
    // T6WDTEN Timer 6 WDT tolerance.
    TimerV1TMCCTRLT6WDTENPos = 23
    TimerV1TMCCTRLT6WDTENMsk = 0x1 << 23
    // T7EN Timer 7 enable.
    TimerV1TMCCTRLT7ENPos = 24
    TimerV1TMCCTRLT7ENMsk = 0x1 << 24
    // T7CLKSEL Timer 7 clock source: 0=PCLK, 1=1 MHz.
    TimerV1TMCCTRLT7CLKSELPos = 25
    TimerV1TMCCTRLT7CLKSELMsk = 0x1 << 25
    // T7OVFINTR Timer 7 overflow interrupt enable.
    TimerV1TMCCTRLT7OVFINTRPos = 26
    TimerV1TMCCTRLT7OVFINTRMsk = 0x1 << 26
    // T7WDTEN Timer 7 WDT tolerance.
    TimerV1TMCCTRLT7WDTENPos = 27
    TimerV1TMCCTRLT7WDTENMsk = 0x1 << 27
    // T8EN Timer 8 enable.
    TimerV1TMCCTRLT8ENPos = 28
    TimerV1TMCCTRLT8ENMsk = 0x1 << 28
    // T8CLKSEL Timer 8 clock source: 0=PCLK, 1=1 MHz.
    TimerV1TMCCTRLT8CLKSELPos = 29
    TimerV1TMCCTRLT8CLKSELMsk = 0x1 << 29
    // T8OVFINTR Timer 8 overflow interrupt enable.
    TimerV1TMCCTRLT8OVFINTRPos = 30
    TimerV1TMCCTRLT8OVFINTRMsk = 0x1 << 30
    // T8WDTEN Timer 8 WDT tolerance.
    TimerV1TMCCTRLT8WDTENPos = 31
    TimerV1TMCCTRLT8WDTENMsk = 0x1 << 31
)

// timer_v1::TMC_INT_STATUS Timer Interrupt Status Register (TMC34). RW1C. Bit N-1 is set when timer N overflow interrupt fires.
const (
    // T1INT Timer 1 interrupt event.
    TimerV1TMCINTSTATUST1INTPos = 0
    TimerV1TMCINTSTATUST1INTMsk = 0x1 << 0
    // T2INT Timer 2 interrupt event.
    TimerV1TMCINTSTATUST2INTPos = 1
    TimerV1TMCINTSTATUST2INTMsk = 0x1 << 1
    // T3INT Timer 3 interrupt event.
    TimerV1TMCINTSTATUST3INTPos = 2
    TimerV1TMCINTSTATUST3INTMsk = 0x1 << 2
    // T4INT Timer 4 interrupt event.
    TimerV1TMCINTSTATUST4INTPos = 3
    TimerV1TMCINTSTATUST4INTMsk = 0x1 << 3
    // T5INT Timer 5 interrupt event.
    TimerV1TMCINTSTATUST5INTPos = 4
    TimerV1TMCINTSTATUST5INTMsk = 0x1 << 4
    // T6INT Timer 6 interrupt event.
    TimerV1TMCINTSTATUST6INTPos = 5
    TimerV1TMCINTSTATUST6INTMsk = 0x1 << 5
    // T7INT Timer 7 interrupt event.
    TimerV1TMCINTSTATUST7INTPos = 6
    TimerV1TMCINTSTATUST7INTMsk = 0x1 << 6
    // T8INT Timer 8 interrupt event.
    TimerV1TMCINTSTATUST8INTPos = 7
    TimerV1TMCINTSTATUST8INTMsk = 0x1 << 7
)

// uart_v1::DATA8 8-bit data register (RBR/THR and SCR share this layout).
const (
    // DATA Data byte (bits [7:0]).
    UartV1DATA8DATAPos = 0
    UartV1DATA8DATAMsk = 0xff << 0
)

// uart_v1::FCR_IIR FIFO Control Register (write) / Interrupt Identification Register (read). Write access configures FIFO; read access returns interrupt status.
const (
    // FIFOEORIP Write (FCR): FIFO Enable.  1 = enable TX and RX FIFOs; clearing this bit resets both FIFOs. Read (IIR): Interrupt Pending (active-low).  0 = interrupt pending.
    UartV1FCRIIRFIFOEORIPPos = 0
    UartV1FCRIIRFIFOEORIPMsk = 0x1 << 0
    // RFIFORORIID1 Write (FCR): Receiver FIFO Reset.  Write 1 to flush RX FIFO. Read (IIR): Interrupt ID bit 1.
    UartV1FCRIIRRFIFORORIID1Pos = 1
    UartV1FCRIIRRFIFORORIID1Msk = 0x1 << 1
    // XFIFORORIID2 Write (FCR): Transmitter FIFO Reset.  Write 1 to flush TX FIFO. Read (IIR): Interrupt ID bit 2.
    UartV1FCRIIRXFIFORORIID2Pos = 2
    UartV1FCRIIRXFIFORORIID2Msk = 0x1 << 2
    // DMAORIID3 Write (FCR): DMA mode select.  0 = mode 0; 1 = mode 1. Read (IIR): Interrupt ID bit 3 (FIFO timeout indicator on 16550D).
    UartV1FCRIIRDMAORIID3Pos = 3
    UartV1FCRIIRDMAORIID3Msk = 0x1 << 3
    // TXTRIG Write (FCR): TX FIFO trigger threshold. 00=empty; 01=2 bytes; 10=quarter full; 11=half full.
    UartV1FCRIIRTXTRIGPos = 4
    UartV1FCRIIRTXTRIGMsk = 0x3 << 4
    // RXTRIG Write (FCR): RX FIFO trigger threshold. 00=1 byte; 01=quarter full; 10=half full; 11=2 from full. Read (IIR): FIFO enabled status bits [7:6] (11=FIFOs enabled).
    UartV1FCRIIRRXTRIGPos = 6
    UartV1FCRIIRRXTRIGMsk = 0x3 << 6
)

// uart_v1::IER Interrupt Enable Register (DLAB=0).
const (
    // ERBFI Enable Received Data Available Interrupt. 1 = generate IRQ when RBR has received data (LSR.DR=1) or FIFO reaches trigger level.
    UartV1IERERBFIPos = 0
    UartV1IERERBFIMsk = 0x1 << 0
    // ETBEI Enable Transmitter Holding Register Empty Interrupt. 1 = generate IRQ when THR is empty (LSR.THRE=1).
    UartV1IERETBEIPos = 1
    UartV1IERETBEIMsk = 0x1 << 1
    // ELSI Enable Receiver Line Status Interrupt. 1 = generate IRQ on OE/PE/FE/BI errors (LSR bits 1-4).
    UartV1IERELSIPos = 2
    UartV1IERELSIMsk = 0x1 << 2
    // EDSSI Enable Modem Status Interrupt. 1 = generate IRQ on CTS/DSR/RI/DCD changes (MSR bits 0-3).
    UartV1IEREDSSIPos = 3
    UartV1IEREDSSIMsk = 0x1 << 3
)

// uart_v1::LCR Line Control Register.
const (
    // WLS Word Length Select. 00=5 bits; 01=6 bits; 10=7 bits; 11=8 bits.
    UartV1LCRWLSPos = 0
    UartV1LCRWLSMsk = 0x3 << 0
    // STB Stop Bits. 0 = 1 stop bit; 1 = 2 stop bits (or 1.5 for 5-bit words).
    UartV1LCRSTBPos = 2
    UartV1LCRSTBMsk = 0x1 << 2
    // PEN Parity Enable. 1 = enable parity generation/checking.
    UartV1LCRPENPos = 3
    UartV1LCRPENMsk = 0x1 << 3
    // EPS Even Parity Select (when PEN=1). 0 = odd parity; 1 = even parity.
    UartV1LCREPSPos = 4
    UartV1LCREPSMsk = 0x1 << 4
    // SP Stick Parity. 1 = parity bit forced to 0 (EPS=1) or 1 (EPS=0).
    UartV1LCRSPPos = 5
    UartV1LCRSPMsk = 0x1 << 5
    // BC Break Control. 1 = force TX line to spacing (break) state.
    UartV1LCRBCPos = 6
    UartV1LCRBCMsk = 0x1 << 6
    // DLAB Divisor Latch Access Bit. 1 = offsets 0x00 and 0x04 address DLL/DLH (baud rate divisor); 0 = offsets 0x00 and 0x04 address RBR/THR and IER. Clear to 0 after configuring baud rate.
    UartV1LCRDLABPos = 7
    UartV1LCRDLABMsk = 0x1 << 7
)

// uart_v1::LSR Line Status Register. Read-only status bits.
const (
    // DR Data Ready. 1 = at least one character is in the RX buffer / RX FIFO.
    UartV1LSRDRPos = 0
    UartV1LSRDRMsk = 0x1 << 0
    // OE Overrun Error. 1 = a new character arrived before the previous was read. Cleared by reading LSR.
    UartV1LSROEPos = 1
    UartV1LSROEMsk = 0x1 << 1
    // PE Parity Error. 1 = received character has wrong parity. Cleared by reading LSR.
    UartV1LSRPEPos = 2
    UartV1LSRPEMsk = 0x1 << 2
    // FE Framing Error. 1 = received character has no valid stop bit. Cleared by reading LSR.
    UartV1LSRFEPos = 3
    UartV1LSRFEMsk = 0x1 << 3
    // BI Break Interrupt. 1 = RX line has been held at 0 (spacing) for more than one character time. Cleared by reading LSR.
    UartV1LSRBIPos = 4
    UartV1LSRBIMsk = 0x1 << 4
    // THRE Transmitter Holding Register Empty. 1 = THR is empty; safe to write next byte (or FIFO below threshold).
    UartV1LSRTHREPos = 5
    UartV1LSRTHREMsk = 0x1 << 5
    // TEMT Transmitter Empty. 1 = both THR and transmitter shift register are empty.
    UartV1LSRTEMTPos = 6
    UartV1LSRTEMTMsk = 0x1 << 6
    // FIFOERR FIFO data error (FIFO mode only). 1 = at least one PE/FE/BI error is present in the RX FIFO. Cleared when the erroneous byte is read out.
    UartV1LSRFIFOERRPos = 7
    UartV1LSRFIFOERRMsk = 0x1 << 7
)

// uart_v1::MCR Modem Control Register.
const (
    // DTR Data Terminal Ready output (active-low nDTR pin).
    UartV1MCRDTRPos = 0
    UartV1MCRDTRMsk = 0x1 << 0
    // RTS Request To Send output (active-low nRTS pin).
    UartV1MCRRTSPos = 1
    UartV1MCRRTSMsk = 0x1 << 1
    // OUT1 Output 1 (general-purpose output, active-low).
    UartV1MCROUT1Pos = 2
    UartV1MCROUT1Msk = 0x1 << 2
    // OUT2 Output 2 (active-low). On PC hardware this gates the interrupt; on ASPEED UARTs it must be set to 1 to enable interrupts.
    UartV1MCROUT2Pos = 3
    UartV1MCROUT2Msk = 0x1 << 3
    // LOOP Internal loopback mode. 1 = TX connected to RX internally; modem lines looped.
    UartV1MCRLOOPPos = 4
    UartV1MCRLOOPMsk = 0x1 << 4
)

// uart_v1::MSR Modem Status Register. CTS/DSR/RI/DCD change and current state.
const (
    // DCTS Delta CTS – CTS changed since last MSR read.
    UartV1MSRDCTSPos = 0
    UartV1MSRDCTSMsk = 0x1 << 0
    // DDSR Delta DSR – DSR changed since last MSR read.
    UartV1MSRDDSRPos = 1
    UartV1MSRDDSRMsk = 0x1 << 1
    // TERI Trailing Edge Ring Indicator – RI went from active to inactive.
    UartV1MSRTERIPos = 2
    UartV1MSRTERIMsk = 0x1 << 2
    // DDCD Delta DCD – DCD changed since last MSR read.
    UartV1MSRDDCDPos = 3
    UartV1MSRDDCDMsk = 0x1 << 3
    // CTS Clear To Send (complement of nCTS input).
    UartV1MSRCTSPos = 4
    UartV1MSRCTSMsk = 0x1 << 4
    // DSR Data Set Ready (complement of nDSR input).
    UartV1MSRDSRPos = 5
    UartV1MSRDSRMsk = 0x1 << 5
    // RI Ring Indicator (complement of nRI input).
    UartV1MSRRIPos = 6
    UartV1MSRRIMsk = 0x1 << 6
    // DCD Data Carrier Detect (complement of nDCD input).
    UartV1MSRDCDPos = 7
    UartV1MSRDCDMsk = 0x1 << 7
)

// wdt_v1::WDT_COUNTER 32-bit counter / reload value (WDT00 and WDT04 share this layout).
const (
    // VALUE Counter value in microseconds.
    WdtV1WDTCOUNTERVALUEPos = 0
    WdtV1WDTCOUNTERVALUEMsk = 0xffffffff << 0
)

// wdt_v1::WDT_CTRL WDT Control Register (WDT0C).
const (
    // WDTEN WDT Enable. 0 = disabled (counter holds current value); 1 = enabled (counter counts down).
    WdtV1WDTCTRLWDTENPos = 0
    WdtV1WDTCTRLWDTENMsk = 0x1 << 0
    // RSTSYS Reset system after timeout. 0 = disabled; 1 = assert SoC / CPU reset when counter reaches 0. Must clear WDT10[0] before enabling this bit.
    WdtV1WDTCTRLRSTSYSPos = 1
    WdtV1WDTCTRLRSTSYSMsk = 0x1 << 1
    // WDTRESETBYSOC Allow SOC-level reset to reset this WDT instance. 0 = only SRST# or full-chip reset can reset this WDT; 1 = SOC system reset also resets this WDT.
    WdtV1WDTCTRLWDTRESETBYSOCPos = 4
    WdtV1WDTCTRLWDTRESETBYSOCMsk = 0x1 << 4
    // RSTMODE Reset system mode (bits [6:5]). 00 = SOC system reset (gated by reset mask registers); 01 = Full chip reset; 1x = CPU/FMC only (firmware reboot, no peripheral reset).
    WdtV1WDTCTRLRSTMODEPos = 5
    WdtV1WDTCTRLRSTMODEMsk = 0x3 << 5
    // WDTEXT External signal enable after timeout. 1 = pulse generated on an external output pin.
    WdtV1WDTCTRLWDTEXTPos = 27
    WdtV1WDTCTRLWDTEXTMsk = 0x1 << 27
    // WDTINTR Interrupt before timeout. 1 = generate interrupt when counter reaches pre-timeout value (set in CTRL bits [31:10]).
    WdtV1WDTCTRLWDTINTRPos = 28
    WdtV1WDTCTRLWDTINTRMsk = 0x1 << 28
)

// wdt_v1::WDT_RESTART Counter Restart Register (WDT08).
const (
    // KEY Write 0x4755 to reload and restart the counter. Read returns 0 (write-only hardware).
    WdtV1WDTRESTARTKEYPos = 0
    WdtV1WDTRESTARTKEYMsk = 0xffff << 0
)

// wdt_v1::WDT_SW_RESET_CTRL Software Mode Reset Control Register (WDT24).
const (
    // TRIGGER Write 0xAEEDF123 to fire a software-mode SOC reset immediately. After reset this bit clears to 0 automatically. Only SOC reset mode is supported for software-triggered resets.
    WdtV1WDTSWRESETCTRLTRIGGERPos = 0
    WdtV1WDTSWRESETCTRLTRIGGERMsk = 0xffffffff << 0
)

// wdt_v1::WDT_SW_RESET_MASK1 Software Mode Reset Mask Register #1 (WDT28). Each bit enables (1) or disables (0) the reset of the corresponding subsystem when SW_RESET_CTRL is triggered.
const (
    // MASK Subsystem reset enable bitmask. Zephyr sets 0x03FF_FFF1 to reset the standard set of subsystems (ARM, SDRAM, AHB bridges, coprocessor, SOC controllers, USB, etc.).
    WdtV1WDTSWRESETMASK1MASKPos = 0
    WdtV1WDTSWRESETMASK1MASKMsk = 0xffffffff << 0
)

