// Code generated by chiptool; DO NOT EDIT.

package pac

import "github.com/kyanitecomputer/aspeed-go/reg"

// GpioV1GPIO AST2600 3.3 V GPIO controller (208 pins, ports A–Z). Base: 0x7E78_0000 (CM3 view).
type GpioV1GPIO struct {
    Base uintptr
}

// ReadG0DATA reads Group 0 (A/B/C/D) Data Value Register (GPIO000).
func (p *GpioV1GPIO) ReadG0DATA() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0000))
}

// WriteG0DATA writes Group 0 (A/B/C/D) Data Value Register (GPIO000).
func (p *GpioV1GPIO) WriteG0DATA(val uint32) {
    reg.Write(uint32(p.Base)+0x0000, uint32(val))
}

// ReadG0DIR reads Group 0 (A/B/C/D) Direction Register (GPIO004). 1=output.
func (p *GpioV1GPIO) ReadG0DIR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0004))
}

// WriteG0DIR writes Group 0 (A/B/C/D) Direction Register (GPIO004). 1=output.
func (p *GpioV1GPIO) WriteG0DIR(val uint32) {
    reg.Write(uint32(p.Base)+0x0004, uint32(val))
}

// ReadG0INTEN reads Group 0 (A/B/C/D) Interrupt Enable Register (GPIO008).
func (p *GpioV1GPIO) ReadG0INTEN() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0008))
}

// WriteG0INTEN writes Group 0 (A/B/C/D) Interrupt Enable Register (GPIO008).
func (p *GpioV1GPIO) WriteG0INTEN(val uint32) {
    reg.Write(uint32(p.Base)+0x0008, uint32(val))
}

// ReadG0INTTYPE0 reads Group 0 Interrupt Sensitivity Type 0 (GPIO00C).
func (p *GpioV1GPIO) ReadG0INTTYPE0() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x000c))
}

// WriteG0INTTYPE0 writes Group 0 Interrupt Sensitivity Type 0 (GPIO00C).
func (p *GpioV1GPIO) WriteG0INTTYPE0(val uint32) {
    reg.Write(uint32(p.Base)+0x000c, uint32(val))
}

// ReadG0INTTYPE1 reads Group 0 Interrupt Sensitivity Type 1 (GPIO010).
func (p *GpioV1GPIO) ReadG0INTTYPE1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0010))
}

// WriteG0INTTYPE1 writes Group 0 Interrupt Sensitivity Type 1 (GPIO010).
func (p *GpioV1GPIO) WriteG0INTTYPE1(val uint32) {
    reg.Write(uint32(p.Base)+0x0010, uint32(val))
}

// ReadG0INTTYPE2 reads Group 0 Interrupt Sensitivity Type 2 (GPIO014).
func (p *GpioV1GPIO) ReadG0INTTYPE2() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0014))
}

// WriteG0INTTYPE2 writes Group 0 Interrupt Sensitivity Type 2 (GPIO014).
func (p *GpioV1GPIO) WriteG0INTTYPE2(val uint32) {
    reg.Write(uint32(p.Base)+0x0014, uint32(val))
}

// ReadG0INTSTATUS reads Group 0 (A/B/C/D) Interrupt Status Register (GPIO018). RW1C.
func (p *GpioV1GPIO) ReadG0INTSTATUS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0018))
}

// WriteG0INTSTATUS writes Group 0 (A/B/C/D) Interrupt Status Register (GPIO018). RW1C.
func (p *GpioV1GPIO) WriteG0INTSTATUS(val uint32) {
    reg.Write(uint32(p.Base)+0x0018, uint32(val))
}

// ReadG0RESETTOL reads Group 0 WDT Reset Tolerant Register (GPIO01C).
func (p *GpioV1GPIO) ReadG0RESETTOL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x001c))
}

// WriteG0RESETTOL writes Group 0 WDT Reset Tolerant Register (GPIO01C).
func (p *GpioV1GPIO) WriteG0RESETTOL(val uint32) {
    reg.Write(uint32(p.Base)+0x001c, uint32(val))
}

// ReadG1DATA reads Group 1 (E/F/G/H) Data Value Register (GPIO020).
func (p *GpioV1GPIO) ReadG1DATA() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0020))
}

// WriteG1DATA writes Group 1 (E/F/G/H) Data Value Register (GPIO020).
func (p *GpioV1GPIO) WriteG1DATA(val uint32) {
    reg.Write(uint32(p.Base)+0x0020, uint32(val))
}

// ReadG1DIR reads Group 1 (E/F/G/H) Direction Register (GPIO024).
func (p *GpioV1GPIO) ReadG1DIR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0024))
}

// WriteG1DIR writes Group 1 (E/F/G/H) Direction Register (GPIO024).
func (p *GpioV1GPIO) WriteG1DIR(val uint32) {
    reg.Write(uint32(p.Base)+0x0024, uint32(val))
}

// ReadG1INTEN reads Group 1 (E/F/G/H) Interrupt Enable Register (GPIO028).
func (p *GpioV1GPIO) ReadG1INTEN() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0028))
}

// WriteG1INTEN writes Group 1 (E/F/G/H) Interrupt Enable Register (GPIO028).
func (p *GpioV1GPIO) WriteG1INTEN(val uint32) {
    reg.Write(uint32(p.Base)+0x0028, uint32(val))
}

// ReadG1INTTYPE0 reads Group 1 Interrupt Sensitivity Type 0 (GPIO02C).
func (p *GpioV1GPIO) ReadG1INTTYPE0() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x002c))
}

// WriteG1INTTYPE0 writes Group 1 Interrupt Sensitivity Type 0 (GPIO02C).
func (p *GpioV1GPIO) WriteG1INTTYPE0(val uint32) {
    reg.Write(uint32(p.Base)+0x002c, uint32(val))
}

// ReadG1INTTYPE1 reads Group 1 Interrupt Sensitivity Type 1 (GPIO030).
func (p *GpioV1GPIO) ReadG1INTTYPE1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0030))
}

// WriteG1INTTYPE1 writes Group 1 Interrupt Sensitivity Type 1 (GPIO030).
func (p *GpioV1GPIO) WriteG1INTTYPE1(val uint32) {
    reg.Write(uint32(p.Base)+0x0030, uint32(val))
}

// ReadG1INTTYPE2 reads Group 1 Interrupt Sensitivity Type 2 (GPIO034).
func (p *GpioV1GPIO) ReadG1INTTYPE2() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0034))
}

// WriteG1INTTYPE2 writes Group 1 Interrupt Sensitivity Type 2 (GPIO034).
func (p *GpioV1GPIO) WriteG1INTTYPE2(val uint32) {
    reg.Write(uint32(p.Base)+0x0034, uint32(val))
}

// ReadG1INTSTATUS reads Group 1 (E/F/G/H) Interrupt Status Register (GPIO038). RW1C.
func (p *GpioV1GPIO) ReadG1INTSTATUS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0038))
}

// WriteG1INTSTATUS writes Group 1 (E/F/G/H) Interrupt Status Register (GPIO038). RW1C.
func (p *GpioV1GPIO) WriteG1INTSTATUS(val uint32) {
    reg.Write(uint32(p.Base)+0x0038, uint32(val))
}

// ReadG1RESETTOL reads Group 1 WDT Reset Tolerant Register (GPIO03C).
func (p *GpioV1GPIO) ReadG1RESETTOL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x003c))
}

// WriteG1RESETTOL writes Group 1 WDT Reset Tolerant Register (GPIO03C).
func (p *GpioV1GPIO) WriteG1RESETTOL(val uint32) {
    reg.Write(uint32(p.Base)+0x003c, uint32(val))
}

// ReadG0CMDSRC0 reads Group 0 (A/B/C/D) Command Source Register 0 (GPIO060). Each bit is bit 0 of the 2-bit command source for that pin. {CMD_SRC1[n], CMD_SRC0[n]}: 0b00=ARM, 0b10=SSP.
func (p *GpioV1GPIO) ReadG0CMDSRC0() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0060))
}

// WriteG0CMDSRC0 writes Group 0 (A/B/C/D) Command Source Register 0 (GPIO060). Each bit is bit 0 of the 2-bit command source for that pin. {CMD_SRC1[n], CMD_SRC0[n]}: 0b00=ARM, 0b10=SSP.
func (p *GpioV1GPIO) WriteG0CMDSRC0(val uint32) {
    reg.Write(uint32(p.Base)+0x0060, uint32(val))
}

// ReadG0CMDSRC1 reads Group 0 Command Source Register 1 (GPIO064). Bit 1 of each 2-bit source.
func (p *GpioV1GPIO) ReadG0CMDSRC1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0064))
}

// WriteG0CMDSRC1 writes Group 0 Command Source Register 1 (GPIO064). Bit 1 of each 2-bit source.
func (p *GpioV1GPIO) WriteG0CMDSRC1(val uint32) {
    reg.Write(uint32(p.Base)+0x0064, uint32(val))
}

// ReadG1CMDSRC0 reads Group 1 (E/F/G/H) Command Source Register 0 (GPIO068).
func (p *GpioV1GPIO) ReadG1CMDSRC0() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0068))
}

// WriteG1CMDSRC0 writes Group 1 (E/F/G/H) Command Source Register 0 (GPIO068).
func (p *GpioV1GPIO) WriteG1CMDSRC0(val uint32) {
    reg.Write(uint32(p.Base)+0x0068, uint32(val))
}

// ReadG1CMDSRC1 reads Group 1 Command Source Register 1 (GPIO06C).
func (p *GpioV1GPIO) ReadG1CMDSRC1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x006c))
}

// WriteG1CMDSRC1 writes Group 1 Command Source Register 1 (GPIO06C).
func (p *GpioV1GPIO) WriteG1CMDSRC1(val uint32) {
    reg.Write(uint32(p.Base)+0x006c, uint32(val))
}

// ReadG2DATA reads Group 2 (I/J/K/L) Data Value Register (GPIO070).
func (p *GpioV1GPIO) ReadG2DATA() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0070))
}

// WriteG2DATA writes Group 2 (I/J/K/L) Data Value Register (GPIO070).
func (p *GpioV1GPIO) WriteG2DATA(val uint32) {
    reg.Write(uint32(p.Base)+0x0070, uint32(val))
}

// ReadG2DIR reads Group 2 (I/J/K/L) Direction Register (GPIO074).
func (p *GpioV1GPIO) ReadG2DIR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0074))
}

// WriteG2DIR writes Group 2 (I/J/K/L) Direction Register (GPIO074).
func (p *GpioV1GPIO) WriteG2DIR(val uint32) {
    reg.Write(uint32(p.Base)+0x0074, uint32(val))
}

// ReadG3DATA reads Group 3 (M/N/O/P) Data Value Register (GPIO078).
func (p *GpioV1GPIO) ReadG3DATA() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0078))
}

// WriteG3DATA writes Group 3 (M/N/O/P) Data Value Register (GPIO078).
func (p *GpioV1GPIO) WriteG3DATA(val uint32) {
    reg.Write(uint32(p.Base)+0x0078, uint32(val))
}

// ReadG3DIR reads Group 3 (M/N/O/P) Direction Register (GPIO07C).
func (p *GpioV1GPIO) ReadG3DIR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x007c))
}

// WriteG3DIR writes Group 3 (M/N/O/P) Direction Register (GPIO07C).
func (p *GpioV1GPIO) WriteG3DIR(val uint32) {
    reg.Write(uint32(p.Base)+0x007c, uint32(val))
}

// ReadG4DATA reads Group 4 (Q/R/S/T) Data Value Register (GPIO080).
func (p *GpioV1GPIO) ReadG4DATA() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0080))
}

// WriteG4DATA writes Group 4 (Q/R/S/T) Data Value Register (GPIO080).
func (p *GpioV1GPIO) WriteG4DATA(val uint32) {
    reg.Write(uint32(p.Base)+0x0080, uint32(val))
}

// ReadG4DIR reads Group 4 (Q/R/S/T) Direction Register (GPIO084).
func (p *GpioV1GPIO) ReadG4DIR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0084))
}

// WriteG4DIR writes Group 4 (Q/R/S/T) Direction Register (GPIO084).
func (p *GpioV1GPIO) WriteG4DIR(val uint32) {
    reg.Write(uint32(p.Base)+0x0084, uint32(val))
}

// ReadG5DATA reads Group 5 (U/V/W/X) Data Value Register (GPIO088).
func (p *GpioV1GPIO) ReadG5DATA() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0088))
}

// WriteG5DATA writes Group 5 (U/V/W/X) Data Value Register (GPIO088).
func (p *GpioV1GPIO) WriteG5DATA(val uint32) {
    reg.Write(uint32(p.Base)+0x0088, uint32(val))
}

// ReadG5DIR reads Group 5 (U/V/W/X) Direction Register (GPIO08C).
func (p *GpioV1GPIO) ReadG5DIR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x008c))
}

// WriteG5DIR writes Group 5 (U/V/W/X) Direction Register (GPIO08C).
func (p *GpioV1GPIO) WriteG5DIR(val uint32) {
    reg.Write(uint32(p.Base)+0x008c, uint32(val))
}

// ReadG2CMDSRC0 reads Group 2 (I/J/K/L) Command Source Register 0 (GPIO090).
func (p *GpioV1GPIO) ReadG2CMDSRC0() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0090))
}

// WriteG2CMDSRC0 writes Group 2 (I/J/K/L) Command Source Register 0 (GPIO090).
func (p *GpioV1GPIO) WriteG2CMDSRC0(val uint32) {
    reg.Write(uint32(p.Base)+0x0090, uint32(val))
}

// ReadG2CMDSRC1 reads Group 2 Command Source Register 1 (GPIO094).
func (p *GpioV1GPIO) ReadG2CMDSRC1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0094))
}

// WriteG2CMDSRC1 writes Group 2 Command Source Register 1 (GPIO094).
func (p *GpioV1GPIO) WriteG2CMDSRC1(val uint32) {
    reg.Write(uint32(p.Base)+0x0094, uint32(val))
}

// ReadG2INTEN reads Group 2 (I/J/K/L) Interrupt Enable Register (GPIO098).
func (p *GpioV1GPIO) ReadG2INTEN() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0098))
}

// WriteG2INTEN writes Group 2 (I/J/K/L) Interrupt Enable Register (GPIO098).
func (p *GpioV1GPIO) WriteG2INTEN(val uint32) {
    reg.Write(uint32(p.Base)+0x0098, uint32(val))
}

// ReadG2INTTYPE0 reads Group 2 Interrupt Sensitivity Type 0 (GPIO09C).
func (p *GpioV1GPIO) ReadG2INTTYPE0() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x009c))
}

// WriteG2INTTYPE0 writes Group 2 Interrupt Sensitivity Type 0 (GPIO09C).
func (p *GpioV1GPIO) WriteG2INTTYPE0(val uint32) {
    reg.Write(uint32(p.Base)+0x009c, uint32(val))
}

// ReadG2INTTYPE1 reads Group 2 Interrupt Sensitivity Type 1 (GPIO0A0).
func (p *GpioV1GPIO) ReadG2INTTYPE1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00a0))
}

// WriteG2INTTYPE1 writes Group 2 Interrupt Sensitivity Type 1 (GPIO0A0).
func (p *GpioV1GPIO) WriteG2INTTYPE1(val uint32) {
    reg.Write(uint32(p.Base)+0x00a0, uint32(val))
}

// ReadG2INTTYPE2 reads Group 2 Interrupt Sensitivity Type 2 (GPIO0A4).
func (p *GpioV1GPIO) ReadG2INTTYPE2() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00a4))
}

// WriteG2INTTYPE2 writes Group 2 Interrupt Sensitivity Type 2 (GPIO0A4).
func (p *GpioV1GPIO) WriteG2INTTYPE2(val uint32) {
    reg.Write(uint32(p.Base)+0x00a4, uint32(val))
}

// ReadG2INTSTATUS reads Group 2 (I/J/K/L) Interrupt Status Register (GPIO0A8). RW1C.
func (p *GpioV1GPIO) ReadG2INTSTATUS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00a8))
}

// WriteG2INTSTATUS writes Group 2 (I/J/K/L) Interrupt Status Register (GPIO0A8). RW1C.
func (p *GpioV1GPIO) WriteG2INTSTATUS(val uint32) {
    reg.Write(uint32(p.Base)+0x00a8, uint32(val))
}

// ReadG2RESETTOL reads Group 2 WDT Reset Tolerant Register (GPIO0AC).
func (p *GpioV1GPIO) ReadG2RESETTOL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00ac))
}

// WriteG2RESETTOL writes Group 2 WDT Reset Tolerant Register (GPIO0AC).
func (p *GpioV1GPIO) WriteG2RESETTOL(val uint32) {
    reg.Write(uint32(p.Base)+0x00ac, uint32(val))
}

// ReadG2INPUTMASK reads Group 2 (I/J/K/L) Input Mask Register (GPIO0B8).
func (p *GpioV1GPIO) ReadG2INPUTMASK() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00b8))
}

// WriteG2INPUTMASK writes Group 2 (I/J/K/L) Input Mask Register (GPIO0B8).
func (p *GpioV1GPIO) WriteG2INPUTMASK(val uint32) {
    reg.Write(uint32(p.Base)+0x00b8, uint32(val))
}

// ReadG0DATAREAD reads Group 0 (A/B/C/D) Data Read Register (GPIO0C0). Input state.
func (p *GpioV1GPIO) ReadG0DATAREAD() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00c0))
}

// WriteG0DATAREAD writes Group 0 (A/B/C/D) Data Read Register (GPIO0C0). Input state.
func (p *GpioV1GPIO) WriteG0DATAREAD(val uint32) {
    reg.Write(uint32(p.Base)+0x00c0, uint32(val))
}

// ReadG1DATAREAD reads Group 1 (E/F/G/H) Data Read Register (GPIO0C4).
func (p *GpioV1GPIO) ReadG1DATAREAD() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00c4))
}

// WriteG1DATAREAD writes Group 1 (E/F/G/H) Data Read Register (GPIO0C4).
func (p *GpioV1GPIO) WriteG1DATAREAD(val uint32) {
    reg.Write(uint32(p.Base)+0x00c4, uint32(val))
}

// ReadG2DATAREAD reads Group 2 (I/J/K/L) Data Read Register (GPIO0C8).
func (p *GpioV1GPIO) ReadG2DATAREAD() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00c8))
}

// WriteG2DATAREAD writes Group 2 (I/J/K/L) Data Read Register (GPIO0C8).
func (p *GpioV1GPIO) WriteG2DATAREAD(val uint32) {
    reg.Write(uint32(p.Base)+0x00c8, uint32(val))
}

// ReadG3DATAREAD reads Group 3 (M/N/O/P) Data Read Register (GPIO0CC).
func (p *GpioV1GPIO) ReadG3DATAREAD() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00cc))
}

// WriteG3DATAREAD writes Group 3 (M/N/O/P) Data Read Register (GPIO0CC).
func (p *GpioV1GPIO) WriteG3DATAREAD(val uint32) {
    reg.Write(uint32(p.Base)+0x00cc, uint32(val))
}

// ReadG4DATAREAD reads Group 4 (Q/R/S/T) Data Read Register (GPIO0D0).
func (p *GpioV1GPIO) ReadG4DATAREAD() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00d0))
}

// WriteG4DATAREAD writes Group 4 (Q/R/S/T) Data Read Register (GPIO0D0).
func (p *GpioV1GPIO) WriteG4DATAREAD(val uint32) {
    reg.Write(uint32(p.Base)+0x00d0, uint32(val))
}

// ReadG5DATAREAD reads Group 5 (U/V/W/X) Data Read Register (GPIO0D4).
func (p *GpioV1GPIO) ReadG5DATAREAD() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00d4))
}

// WriteG5DATAREAD writes Group 5 (U/V/W/X) Data Read Register (GPIO0D4).
func (p *GpioV1GPIO) WriteG5DATAREAD(val uint32) {
    reg.Write(uint32(p.Base)+0x00d4, uint32(val))
}

// ReadG6DATAREAD reads Group 6 (Y/Z) Data Read Register (GPIO0D8). Only bits [15:0] valid.
func (p *GpioV1GPIO) ReadG6DATAREAD() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00d8))
}

// WriteG6DATAREAD writes Group 6 (Y/Z) Data Read Register (GPIO0D8). Only bits [15:0] valid.
func (p *GpioV1GPIO) WriteG6DATAREAD(val uint32) {
    reg.Write(uint32(p.Base)+0x00d8, uint32(val))
}

// ReadG3CMDSRC0 reads Group 3 (M/N/O/P) Command Source Register 0 (GPIO0E0).
func (p *GpioV1GPIO) ReadG3CMDSRC0() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00e0))
}

// WriteG3CMDSRC0 writes Group 3 (M/N/O/P) Command Source Register 0 (GPIO0E0).
func (p *GpioV1GPIO) WriteG3CMDSRC0(val uint32) {
    reg.Write(uint32(p.Base)+0x00e0, uint32(val))
}

// ReadG3CMDSRC1 reads Group 3 Command Source Register 1 (GPIO0E4).
func (p *GpioV1GPIO) ReadG3CMDSRC1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00e4))
}

// WriteG3CMDSRC1 writes Group 3 Command Source Register 1 (GPIO0E4).
func (p *GpioV1GPIO) WriteG3CMDSRC1(val uint32) {
    reg.Write(uint32(p.Base)+0x00e4, uint32(val))
}

// ReadG3INTEN reads Group 3 (M/N/O/P) Interrupt Enable Register (GPIO0E8).
func (p *GpioV1GPIO) ReadG3INTEN() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00e8))
}

// WriteG3INTEN writes Group 3 (M/N/O/P) Interrupt Enable Register (GPIO0E8).
func (p *GpioV1GPIO) WriteG3INTEN(val uint32) {
    reg.Write(uint32(p.Base)+0x00e8, uint32(val))
}

// ReadG3INTTYPE0 reads Group 3 Interrupt Sensitivity Type 0 (GPIO0EC).
func (p *GpioV1GPIO) ReadG3INTTYPE0() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00ec))
}

// WriteG3INTTYPE0 writes Group 3 Interrupt Sensitivity Type 0 (GPIO0EC).
func (p *GpioV1GPIO) WriteG3INTTYPE0(val uint32) {
    reg.Write(uint32(p.Base)+0x00ec, uint32(val))
}

// ReadG3INTTYPE1 reads Group 3 Interrupt Sensitivity Type 1 (GPIO0F0).
func (p *GpioV1GPIO) ReadG3INTTYPE1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00f0))
}

// WriteG3INTTYPE1 writes Group 3 Interrupt Sensitivity Type 1 (GPIO0F0).
func (p *GpioV1GPIO) WriteG3INTTYPE1(val uint32) {
    reg.Write(uint32(p.Base)+0x00f0, uint32(val))
}

// ReadG3INTTYPE2 reads Group 3 Interrupt Sensitivity Type 2 (GPIO0F4).
func (p *GpioV1GPIO) ReadG3INTTYPE2() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00f4))
}

// WriteG3INTTYPE2 writes Group 3 Interrupt Sensitivity Type 2 (GPIO0F4).
func (p *GpioV1GPIO) WriteG3INTTYPE2(val uint32) {
    reg.Write(uint32(p.Base)+0x00f4, uint32(val))
}

// ReadG3INTSTATUS reads Group 3 (M/N/O/P) Interrupt Status Register (GPIO0F8). RW1C.
func (p *GpioV1GPIO) ReadG3INTSTATUS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00f8))
}

// WriteG3INTSTATUS writes Group 3 (M/N/O/P) Interrupt Status Register (GPIO0F8). RW1C.
func (p *GpioV1GPIO) WriteG3INTSTATUS(val uint32) {
    reg.Write(uint32(p.Base)+0x00f8, uint32(val))
}

// ReadG3RESETTOL reads Group 3 WDT Reset Tolerant Register (GPIO0FC).
func (p *GpioV1GPIO) ReadG3RESETTOL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x00fc))
}

// WriteG3RESETTOL writes Group 3 WDT Reset Tolerant Register (GPIO0FC).
func (p *GpioV1GPIO) WriteG3RESETTOL(val uint32) {
    reg.Write(uint32(p.Base)+0x00fc, uint32(val))
}

// ReadG3INPUTMASK reads Group 3 (M/N/O/P) Input Mask Register (GPIO108).
func (p *GpioV1GPIO) ReadG3INPUTMASK() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0108))
}

// WriteG3INPUTMASK writes Group 3 (M/N/O/P) Input Mask Register (GPIO108).
func (p *GpioV1GPIO) WriteG3INPUTMASK(val uint32) {
    reg.Write(uint32(p.Base)+0x0108, uint32(val))
}

// ReadG4CMDSRC0 reads Group 4 (Q/R/S/T) Command Source Register 0 (GPIO110).
func (p *GpioV1GPIO) ReadG4CMDSRC0() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0110))
}

// WriteG4CMDSRC0 writes Group 4 (Q/R/S/T) Command Source Register 0 (GPIO110).
func (p *GpioV1GPIO) WriteG4CMDSRC0(val uint32) {
    reg.Write(uint32(p.Base)+0x0110, uint32(val))
}

// ReadG4CMDSRC1 reads Group 4 Command Source Register 1 (GPIO114).
func (p *GpioV1GPIO) ReadG4CMDSRC1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0114))
}

// WriteG4CMDSRC1 writes Group 4 Command Source Register 1 (GPIO114).
func (p *GpioV1GPIO) WriteG4CMDSRC1(val uint32) {
    reg.Write(uint32(p.Base)+0x0114, uint32(val))
}

// ReadG4INTEN reads Group 4 (Q/R/S/T) Interrupt Enable Register (GPIO118).
func (p *GpioV1GPIO) ReadG4INTEN() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0118))
}

// WriteG4INTEN writes Group 4 (Q/R/S/T) Interrupt Enable Register (GPIO118).
func (p *GpioV1GPIO) WriteG4INTEN(val uint32) {
    reg.Write(uint32(p.Base)+0x0118, uint32(val))
}

// ReadG4INTTYPE0 reads Group 4 Interrupt Sensitivity Type 0 (GPIO11C).
func (p *GpioV1GPIO) ReadG4INTTYPE0() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x011c))
}

// WriteG4INTTYPE0 writes Group 4 Interrupt Sensitivity Type 0 (GPIO11C).
func (p *GpioV1GPIO) WriteG4INTTYPE0(val uint32) {
    reg.Write(uint32(p.Base)+0x011c, uint32(val))
}

// ReadG4INTTYPE1 reads Group 4 Interrupt Sensitivity Type 1 (GPIO120).
func (p *GpioV1GPIO) ReadG4INTTYPE1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0120))
}

// WriteG4INTTYPE1 writes Group 4 Interrupt Sensitivity Type 1 (GPIO120).
func (p *GpioV1GPIO) WriteG4INTTYPE1(val uint32) {
    reg.Write(uint32(p.Base)+0x0120, uint32(val))
}

// ReadG4INTTYPE2 reads Group 4 Interrupt Sensitivity Type 2 (GPIO124).
func (p *GpioV1GPIO) ReadG4INTTYPE2() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0124))
}

// WriteG4INTTYPE2 writes Group 4 Interrupt Sensitivity Type 2 (GPIO124).
func (p *GpioV1GPIO) WriteG4INTTYPE2(val uint32) {
    reg.Write(uint32(p.Base)+0x0124, uint32(val))
}

// ReadG4INTSTATUS reads Group 4 (Q/R/S/T) Interrupt Status Register (GPIO128). RW1C.
func (p *GpioV1GPIO) ReadG4INTSTATUS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0128))
}

// WriteG4INTSTATUS writes Group 4 (Q/R/S/T) Interrupt Status Register (GPIO128). RW1C.
func (p *GpioV1GPIO) WriteG4INTSTATUS(val uint32) {
    reg.Write(uint32(p.Base)+0x0128, uint32(val))
}

// ReadG4RESETTOL reads Group 4 WDT Reset Tolerant Register (GPIO12C).
func (p *GpioV1GPIO) ReadG4RESETTOL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x012c))
}

// WriteG4RESETTOL writes Group 4 WDT Reset Tolerant Register (GPIO12C).
func (p *GpioV1GPIO) WriteG4RESETTOL(val uint32) {
    reg.Write(uint32(p.Base)+0x012c, uint32(val))
}

// ReadG4INPUTMASK reads Group 4 (Q/R/S/T) Input Mask Register (GPIO138).
func (p *GpioV1GPIO) ReadG4INPUTMASK() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0138))
}

// WriteG4INPUTMASK writes Group 4 (Q/R/S/T) Input Mask Register (GPIO138).
func (p *GpioV1GPIO) WriteG4INPUTMASK(val uint32) {
    reg.Write(uint32(p.Base)+0x0138, uint32(val))
}

// ReadG5CMDSRC0 reads Group 5 (U/V/W/X) Command Source Register 0 (GPIO140).
func (p *GpioV1GPIO) ReadG5CMDSRC0() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0140))
}

// WriteG5CMDSRC0 writes Group 5 (U/V/W/X) Command Source Register 0 (GPIO140).
func (p *GpioV1GPIO) WriteG5CMDSRC0(val uint32) {
    reg.Write(uint32(p.Base)+0x0140, uint32(val))
}

// ReadG5CMDSRC1 reads Group 5 Command Source Register 1 (GPIO144).
func (p *GpioV1GPIO) ReadG5CMDSRC1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0144))
}

// WriteG5CMDSRC1 writes Group 5 Command Source Register 1 (GPIO144).
func (p *GpioV1GPIO) WriteG5CMDSRC1(val uint32) {
    reg.Write(uint32(p.Base)+0x0144, uint32(val))
}

// ReadG5INTEN reads Group 5 (U/V/W/X) Interrupt Enable Register (GPIO148).
func (p *GpioV1GPIO) ReadG5INTEN() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0148))
}

// WriteG5INTEN writes Group 5 (U/V/W/X) Interrupt Enable Register (GPIO148).
func (p *GpioV1GPIO) WriteG5INTEN(val uint32) {
    reg.Write(uint32(p.Base)+0x0148, uint32(val))
}

// ReadG5INTTYPE0 reads Group 5 Interrupt Sensitivity Type 0 (GPIO14C).
func (p *GpioV1GPIO) ReadG5INTTYPE0() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x014c))
}

// WriteG5INTTYPE0 writes Group 5 Interrupt Sensitivity Type 0 (GPIO14C).
func (p *GpioV1GPIO) WriteG5INTTYPE0(val uint32) {
    reg.Write(uint32(p.Base)+0x014c, uint32(val))
}

// ReadG5INTTYPE1 reads Group 5 Interrupt Sensitivity Type 1 (GPIO150).
func (p *GpioV1GPIO) ReadG5INTTYPE1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0150))
}

// WriteG5INTTYPE1 writes Group 5 Interrupt Sensitivity Type 1 (GPIO150).
func (p *GpioV1GPIO) WriteG5INTTYPE1(val uint32) {
    reg.Write(uint32(p.Base)+0x0150, uint32(val))
}

// ReadG5INTTYPE2 reads Group 5 Interrupt Sensitivity Type 2 (GPIO154).
func (p *GpioV1GPIO) ReadG5INTTYPE2() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0154))
}

// WriteG5INTTYPE2 writes Group 5 Interrupt Sensitivity Type 2 (GPIO154).
func (p *GpioV1GPIO) WriteG5INTTYPE2(val uint32) {
    reg.Write(uint32(p.Base)+0x0154, uint32(val))
}

// ReadG5INTSTATUS reads Group 5 (U/V/W/X) Interrupt Status Register (GPIO158). RW1C.
func (p *GpioV1GPIO) ReadG5INTSTATUS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0158))
}

// WriteG5INTSTATUS writes Group 5 (U/V/W/X) Interrupt Status Register (GPIO158). RW1C.
func (p *GpioV1GPIO) WriteG5INTSTATUS(val uint32) {
    reg.Write(uint32(p.Base)+0x0158, uint32(val))
}

// ReadG5RESETTOL reads Group 5 WDT Reset Tolerant Register (GPIO15C).
func (p *GpioV1GPIO) ReadG5RESETTOL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x015c))
}

// WriteG5RESETTOL writes Group 5 WDT Reset Tolerant Register (GPIO15C).
func (p *GpioV1GPIO) WriteG5RESETTOL(val uint32) {
    reg.Write(uint32(p.Base)+0x015c, uint32(val))
}

// ReadG5INPUTMASK reads Group 5 (U/V/W/X) Input Mask Register (GPIO168).
func (p *GpioV1GPIO) ReadG5INPUTMASK() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0168))
}

// WriteG5INPUTMASK writes Group 5 (U/V/W/X) Input Mask Register (GPIO168).
func (p *GpioV1GPIO) WriteG5INPUTMASK(val uint32) {
    reg.Write(uint32(p.Base)+0x0168, uint32(val))
}

// ReadG6CMDSRC0 reads Group 6 (Y/Z) Command Source Register 0 (GPIO170).
func (p *GpioV1GPIO) ReadG6CMDSRC0() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0170))
}

// WriteG6CMDSRC0 writes Group 6 (Y/Z) Command Source Register 0 (GPIO170).
func (p *GpioV1GPIO) WriteG6CMDSRC0(val uint32) {
    reg.Write(uint32(p.Base)+0x0170, uint32(val))
}

// ReadG6CMDSRC1 reads Group 6 Command Source Register 1 (GPIO174).
func (p *GpioV1GPIO) ReadG6CMDSRC1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0174))
}

// WriteG6CMDSRC1 writes Group 6 Command Source Register 1 (GPIO174).
func (p *GpioV1GPIO) WriteG6CMDSRC1(val uint32) {
    reg.Write(uint32(p.Base)+0x0174, uint32(val))
}

// ReadG6INTEN reads Group 6 (Y/Z) Interrupt Enable Register (GPIO178).
func (p *GpioV1GPIO) ReadG6INTEN() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0178))
}

// WriteG6INTEN writes Group 6 (Y/Z) Interrupt Enable Register (GPIO178).
func (p *GpioV1GPIO) WriteG6INTEN(val uint32) {
    reg.Write(uint32(p.Base)+0x0178, uint32(val))
}

// ReadG6INTTYPE0 reads Group 6 Interrupt Sensitivity Type 0 (GPIO17C).
func (p *GpioV1GPIO) ReadG6INTTYPE0() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x017c))
}

// WriteG6INTTYPE0 writes Group 6 Interrupt Sensitivity Type 0 (GPIO17C).
func (p *GpioV1GPIO) WriteG6INTTYPE0(val uint32) {
    reg.Write(uint32(p.Base)+0x017c, uint32(val))
}

// ReadG6INTTYPE1 reads Group 6 Interrupt Sensitivity Type 1 (GPIO180).
func (p *GpioV1GPIO) ReadG6INTTYPE1() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0180))
}

// WriteG6INTTYPE1 writes Group 6 Interrupt Sensitivity Type 1 (GPIO180).
func (p *GpioV1GPIO) WriteG6INTTYPE1(val uint32) {
    reg.Write(uint32(p.Base)+0x0180, uint32(val))
}

// ReadG6INTTYPE2 reads Group 6 Interrupt Sensitivity Type 2 (GPIO184).
func (p *GpioV1GPIO) ReadG6INTTYPE2() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0184))
}

// WriteG6INTTYPE2 writes Group 6 Interrupt Sensitivity Type 2 (GPIO184).
func (p *GpioV1GPIO) WriteG6INTTYPE2(val uint32) {
    reg.Write(uint32(p.Base)+0x0184, uint32(val))
}

// ReadG6INTSTATUS reads Group 6 (Y/Z) Interrupt Status Register (GPIO188). RW1C.
func (p *GpioV1GPIO) ReadG6INTSTATUS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0188))
}

// WriteG6INTSTATUS writes Group 6 (Y/Z) Interrupt Status Register (GPIO188). RW1C.
func (p *GpioV1GPIO) WriteG6INTSTATUS(val uint32) {
    reg.Write(uint32(p.Base)+0x0188, uint32(val))
}

// ReadG6RESETTOL reads Group 6 WDT Reset Tolerant Register (GPIO18C).
func (p *GpioV1GPIO) ReadG6RESETTOL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x018c))
}

// WriteG6RESETTOL writes Group 6 WDT Reset Tolerant Register (GPIO18C).
func (p *GpioV1GPIO) WriteG6RESETTOL(val uint32) {
    reg.Write(uint32(p.Base)+0x018c, uint32(val))
}

// ReadG6INPUTMASK reads Group 6 (Y/Z) Input Mask Register (GPIO198).
func (p *GpioV1GPIO) ReadG6INPUTMASK() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0198))
}

// WriteG6INPUTMASK writes Group 6 (Y/Z) Input Mask Register (GPIO198).
func (p *GpioV1GPIO) WriteG6INPUTMASK(val uint32) {
    reg.Write(uint32(p.Base)+0x0198, uint32(val))
}

// ReadG0INPUTMASK reads Group 0 (A/B/C/D) Input Mask Register (GPIO1D0).
func (p *GpioV1GPIO) ReadG0INPUTMASK() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x01d0))
}

// WriteG0INPUTMASK writes Group 0 (A/B/C/D) Input Mask Register (GPIO1D0).
func (p *GpioV1GPIO) WriteG0INPUTMASK(val uint32) {
    reg.Write(uint32(p.Base)+0x01d0, uint32(val))
}

// ReadG1INPUTMASK reads Group 1 (E/F/G/H) Input Mask Register (GPIO1D4).
func (p *GpioV1GPIO) ReadG1INPUTMASK() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x01d4))
}

// WriteG1INPUTMASK writes Group 1 (E/F/G/H) Input Mask Register (GPIO1D4).
func (p *GpioV1GPIO) WriteG1INPUTMASK(val uint32) {
    reg.Write(uint32(p.Base)+0x01d4, uint32(val))
}

// ReadG6DATA reads Group 6 (Y/Z) Data Value Register (GPIO1E0). Only bits [15:0] valid.
func (p *GpioV1GPIO) ReadG6DATA() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x01e0))
}

// WriteG6DATA writes Group 6 (Y/Z) Data Value Register (GPIO1E0). Only bits [15:0] valid.
func (p *GpioV1GPIO) WriteG6DATA(val uint32) {
    reg.Write(uint32(p.Base)+0x01e0, uint32(val))
}

// ReadG6DIR reads Group 6 (Y/Z) Direction Register (GPIO1E4).
func (p *GpioV1GPIO) ReadG6DIR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x01e4))
}

// WriteG6DIR writes Group 6 (Y/Z) Direction Register (GPIO1E4).
func (p *GpioV1GPIO) WriteG6DIR(val uint32) {
    reg.Write(uint32(p.Base)+0x01e4, uint32(val))
}

// ReadINDEX reads GPIO Index Register (GPIO2AC). Command-based interface for per-pin configuration. bits [7:0]   = pin number (0–207) bit  [12]    = command (0=write, 1=read) bits [19:16] = type (0=DATA, 1=DIR, 2=INTERRUPT, 3=DEBOUNCE,
//                      4=TOLERANCE, 5=CMD_SRC, 6=INPUT_MASK)
// bits [24:20] = data (for INTERRUPT: bit0=int_enable,
//                      bits[4:1]=int_type 0=FALL 1=RISE 2=LOW 3=HIGH 4=BOTH)
func (p *GpioV1GPIO) ReadINDEX() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x02ac))
}

// WriteINDEX writes GPIO Index Register (GPIO2AC). Command-based interface for per-pin configuration. bits [7:0]   = pin number (0–207) bit  [12]    = command (0=write, 1=read) bits [19:16] = type (0=DATA, 1=DIR, 2=INTERRUPT, 3=DEBOUNCE,
//                      4=TOLERANCE, 5=CMD_SRC, 6=INPUT_MASK)
// bits [24:20] = data (for INTERRUPT: bit0=int_enable,
//                      bits[4:1]=int_type 0=FALL 1=RISE 2=LOW 3=HIGH 4=BOTH)
func (p *GpioV1GPIO) WriteINDEX(val uint32) {
    reg.Write(uint32(p.Base)+0x02ac, uint32(val))
}

// ReadCMDSRCSEL reads GPIO Command Source Selection Register (GPIO2D0). Assigns a bus master index to each of the 5 master slots. SSP master number = 6 (ASPEED_GPIO_SEL_SSP). Configure to allow SSP to write GPIO via CMD_SRC registers.
func (p *GpioV1GPIO) ReadCMDSRCSEL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x02d0))
}

// WriteCMDSRCSEL writes GPIO Command Source Selection Register (GPIO2D0). Assigns a bus master index to each of the 5 master slots. SSP master number = 6 (ASPEED_GPIO_SEL_SSP). Configure to allow SSP to write GPIO via CMD_SRC registers.
func (p *GpioV1GPIO) WriteCMDSRCSEL(val uint32) {
    reg.Write(uint32(p.Base)+0x02d0, uint32(val))
}

