// Code generated by chiptool; DO NOT EDIT.

package pac

import "github.com/kyanitecomputer/aspeed-go/reg"

// IpcV1IPC AST2600 IPC doorbell mailbox. Base: 0x7E6C_0000 (CM3 view). 15-channel doorbell between CM3 SSP (IRQs 182-196) and CA7.
type IpcV1IPC struct {
    Base uintptr
}

// ReadTRIG reads IPC Trigger Register (offset 0x18). Write BIT(n) to ring doorbell on channel n to the CA7. Bits [14:0] correspond to channels 0-14. Writing this register is a pulse; it does not hold state.
func (p *IpcV1IPC) ReadTRIG() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0018))
}

// WriteTRIG writes IPC Trigger Register (offset 0x18). Write BIT(n) to ring doorbell on channel n to the CA7. Bits [14:0] correspond to channels 0-14. Writing this register is a pulse; it does not hold state.
func (p *IpcV1IPC) WriteTRIG(val uint32) {
    reg.Write(uint32(p.Base)+0x0018, uint32(val))
}

// ReadSTATUS reads IPC Status Register (offset 0x28). Read-only. Each bit indicates a pending channel:
//   - Bit set by CA7 write → bit is pending for CM3 to handle.
//   - Bit set by CM3 TRIG  → still waiting for CA7 acknowledgement.
// Read STATUS before TRIG to check if a send would be busy.
func (p *IpcV1IPC) ReadSTATUS() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0028))
}

// WriteSTATUS writes IPC Status Register (offset 0x28). Read-only. Each bit indicates a pending channel:
//   - Bit set by CA7 write → bit is pending for CM3 to handle.
//   - Bit set by CM3 TRIG  → still waiting for CA7 acknowledgement.
// Read STATUS before TRIG to check if a send would be busy.
func (p *IpcV1IPC) WriteSTATUS(val uint32) {
    reg.Write(uint32(p.Base)+0x0028, uint32(val))
}

// ReadCLEAR reads IPC Clear Register (offset 0x2C). Write-only. Write the STATUS value (or BIT(n)) to acknowledge received CA7→CM3 interrupts. Clears the corresponding STATUS bits.
func (p *IpcV1IPC) ReadCLEAR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x002c))
}

// WriteCLEAR writes IPC Clear Register (offset 0x2C). Write-only. Write the STATUS value (or BIT(n)) to acknowledge received CA7→CM3 interrupts. Clears the corresponding STATUS bits.
func (p *IpcV1IPC) WriteCLEAR(val uint32) {
    reg.Write(uint32(p.Base)+0x002c, uint32(val))
}

