// Code generated by chiptool; DO NOT EDIT.

package pac

import "github.com/kyanitecomputer/aspeed-go/reg"

// SspV1SSP CM3 coprocessor control registers. Base address: SCU + 0xA00  (CM3 view: 0x7E6E_2A00).
type SspV1SSP struct {
    Base uintptr
}

// ReadCTRL reads CM3 Coprocessor Control Register (SCUA00)
func (p *SspV1SSP) ReadCTRL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0000))
}

// WriteCTRL writes CM3 Coprocessor Control Register (SCUA00)
func (p *SspV1SSP) WriteCTRL(val uint32) {
    reg.Write(uint32(p.Base)+0x0000, uint32(val))
}

// ReadMEMBASE reads CM3 Memory Base Address Register (SCUA04)
func (p *SspV1SSP) ReadMEMBASE() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0004))
}

// WriteMEMBASE writes CM3 Memory Base Address Register (SCUA04)
func (p *SspV1SSP) WriteMEMBASE(val uint32) {
    reg.Write(uint32(p.Base)+0x0004, uint32(val))
}

// ReadIMEMLIMIT reads CM3 Instruction Memory Address Limit Register (SCUA08)
func (p *SspV1SSP) ReadIMEMLIMIT() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0008))
}

// WriteIMEMLIMIT writes CM3 Instruction Memory Address Limit Register (SCUA08)
func (p *SspV1SSP) WriteIMEMLIMIT(val uint32) {
    reg.Write(uint32(p.Base)+0x0008, uint32(val))
}

// ReadDMEMLIMIT reads CM3 Data Memory Address Limit Register (SCUA0C)
func (p *SspV1SSP) ReadDMEMLIMIT() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x000c))
}

// WriteDMEMLIMIT writes CM3 Data Memory Address Limit Register (SCUA0C)
func (p *SspV1SSP) WriteDMEMLIMIT(val uint32) {
    reg.Write(uint32(p.Base)+0x000c, uint32(val))
}

// ReadCACHEAREA reads CM3 Cacheable Area Declaration Register (SCUA40)
func (p *SspV1SSP) ReadCACHEAREA() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0040))
}

// WriteCACHEAREA writes CM3 Cacheable Area Declaration Register (SCUA40)
func (p *SspV1SSP) WriteCACHEAREA(val uint32) {
    reg.Write(uint32(p.Base)+0x0040, uint32(val))
}

// ReadCACHEINVAL reads CM3 Cache Invalidation Control Register (SCUA44)
func (p *SspV1SSP) ReadCACHEINVAL() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0044))
}

// WriteCACHEINVAL writes CM3 Cache Invalidation Control Register (SCUA44)
func (p *SspV1SSP) WriteCACHEINVAL(val uint32) {
    reg.Write(uint32(p.Base)+0x0044, uint32(val))
}

// ReadCACHEFUNC reads CM3 Cache Function Control Register (SCUA48)
func (p *SspV1SSP) ReadCACHEFUNC() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0048))
}

// WriteCACHEFUNC writes CM3 Cache Function Control Register (SCUA48)
func (p *SspV1SSP) WriteCACHEFUNC(val uint32) {
    reg.Write(uint32(p.Base)+0x0048, uint32(val))
}

