// Code generated by chiptool; DO NOT EDIT.

package pac

import "github.com/kyanitecomputer/aspeed-go/reg"

// UartV1UART 16550-compatible UART register block. Base address: UART11 at 0x7E79_0500 (CM3 view). All registers at 4-byte stride; only bits [7:0] carry data.
type UartV1UART struct {
    Base uintptr
}

// ReadRBRTHR reads Receiver Buffer Register (read, DLAB=0) / Transmit Holding Register (write, DLAB=0) / Baud Divisor Low byte (DLAB=1). Read: received byte.  Write: byte to transmit. DLAB=1 access handled in HAL code via raw pointer.
func (p *UartV1UART) ReadRBRTHR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0000))
}

// WriteRBRTHR writes Receiver Buffer Register (read, DLAB=0) / Transmit Holding Register (write, DLAB=0) / Baud Divisor Low byte (DLAB=1). Read: received byte.  Write: byte to transmit. DLAB=1 access handled in HAL code via raw pointer.
func (p *UartV1UART) WriteRBRTHR(val uint32) {
    reg.Write(uint32(p.Base)+0x0000, uint32(val))
}

// ReadIER reads Interrupt Enable Register (DLAB=0) / Baud Divisor High byte (DLAB=1). DLAB=1 access handled in HAL code via raw pointer.
func (p *UartV1UART) ReadIER() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0004))
}

// WriteIER writes Interrupt Enable Register (DLAB=0) / Baud Divisor High byte (DLAB=1). DLAB=1 access handled in HAL code via raw pointer.
func (p *UartV1UART) WriteIER(val uint32) {
    reg.Write(uint32(p.Base)+0x0004, uint32(val))
}

// ReadFCRIIR reads FIFO Control Register (write) / Interrupt Identification Register (read). Reads return IIR; writes configure FIFO via FCR fields. FCR is write-only; IIR is read-only.
func (p *UartV1UART) ReadFCRIIR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0008))
}

// WriteFCRIIR writes FIFO Control Register (write) / Interrupt Identification Register (read). Reads return IIR; writes configure FIFO via FCR fields. FCR is write-only; IIR is read-only.
func (p *UartV1UART) WriteFCRIIR(val uint32) {
    reg.Write(uint32(p.Base)+0x0008, uint32(val))
}

// ReadLCR reads Line Control Register. Controls data format and DLAB.
func (p *UartV1UART) ReadLCR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x000c))
}

// WriteLCR writes Line Control Register. Controls data format and DLAB.
func (p *UartV1UART) WriteLCR(val uint32) {
    reg.Write(uint32(p.Base)+0x000c, uint32(val))
}

// ReadMCR reads Modem Control Register.
func (p *UartV1UART) ReadMCR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0010))
}

// WriteMCR writes Modem Control Register.
func (p *UartV1UART) WriteMCR(val uint32) {
    reg.Write(uint32(p.Base)+0x0010, uint32(val))
}

// ReadLSR reads Line Status Register. TX/RX status flags.
func (p *UartV1UART) ReadLSR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0014))
}

// WriteLSR writes Line Status Register. TX/RX status flags.
func (p *UartV1UART) WriteLSR(val uint32) {
    reg.Write(uint32(p.Base)+0x0014, uint32(val))
}

// ReadMSR reads Modem Status Register.
func (p *UartV1UART) ReadMSR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x0018))
}

// WriteMSR writes Modem Status Register.
func (p *UartV1UART) WriteMSR(val uint32) {
    reg.Write(uint32(p.Base)+0x0018, uint32(val))
}

// ReadSCR reads Scratch Register. Read/write with no hardware effect.
func (p *UartV1UART) ReadSCR() uint32 {
    return uint32(reg.Read(uint32(p.Base) + 0x001c))
}

// WriteSCR writes Scratch Register. Read/write with no hardware effect.
func (p *UartV1UART) WriteSCR(val uint32) {
    reg.Write(uint32(p.Base)+0x001c, uint32(val))
}

